// tools/lib/days-farm.mjs
//
// Dev-only, zero-dependency Node ESM module. NOT shipped (tools/ is never
// copied into www/ — see tools/build-www.mjs's copy list), NOT a node:test
// file (no assertions, so `node --test` never picks it up).
//
// THIS IS A TUNING PROXY, NOT A PASS/FAIL GATE — same status as
// tools/lib/tuning-bot.mjs itself (see that file's own header). Phase 82
// (FARM-01/FARM-02): the ONE exploit measurement of v2.2 — does a hero who
// never leaves floor 1 (and, as a follow-up, floor 2) bank more DAYS than an
// honest descending run? This module builds the farmer policy, run
// classification, summaries and the mechanical verdict rule; it never plays
// a run on its own (that is tools/days-farm.mjs, the CLI). Engine, content
// and test/parity are untouched by this module — it talks to the engine only
// through tools/lib/tuning-bot.mjs's playRun/decideAction black box (Phase
// 82's opt-in policy/stopWhen hooks, tools/lib/tuning-bot.mjs#playRun) and
// two READ-ONLY engine helpers with an existing tuning-bot precedent:
// nightlyEats (engine/movement.js — the ONE appetite definition makeCamp and
// newDay both read) and BAGS (content/bags.js — the ration carry cap).
// Nothing here writes engine state.

import { playRun, decideAction, BOT_DEFAULTS, bfsFirstStep, legalDirs, DIRS, HAZARD_FEATS, chooseStorePurchase, percentile, distribution } from "./tuning-bot.mjs";
import { nightlyEats } from "../../engine/movement.js";
import { rationsLeft, storeBuyRefusal } from "../../engine/economy.js";
import { BAGS } from "../../content/bags.js";

// FARM_CAPS — the hard safety stop (Pitfall 4 precedent, T-82-02): a farmer
// alive at either cap is `unbounded` (farmingUnbounded, a farming win per
// 82-CONTEXT.md), never a runaway hang.
export const FARM_CAPS = Object.freeze({ maxActions: 20000, maxDays: 500 });

// FARM_VARIANTS — the two farmer variants the verdict compares; the verdict
// uses whichever is STRONGER (82-CONTEXT.md: "humans play better than the
// bot").
export const FARM_VARIANTS = Object.freeze(["noStairs", "hoarder"]);

// CLOCK_WINDOW — an `unbounded` row's own clockMoving flag (ledger-only; it
// never removes a run from the win count) is true when the last `dayBegan`
// landed within this many actions of the run's end.
export const CLOCK_WINDOW = 2000;

// BREAKER_LIMIT — makeFarmerPolicy's forced-move breaker: this many
// consecutive out-of-combat, no-open-decision, non-move actions force a
// farmer move instead, so a farmer policy can never spin forever on a
// no-op decision loop the fair bot itself would eventually break out of
// with a floor change (which the farmer forbids).
export const BREAKER_LIMIT = 50;

/**
 * isStairsCell(cell) — true for a floor-changing tile. `resolveFeature`
 * (engine/movement.js) is the ONLY caller of `descend()`, and only for
 * `feat === "exit"` (current genFloor output) or the legacy `"gate"` tile
 * (an in-flight save generated by an OLD genFloor, RUN-04 compatibility). A
 * teleport landing never descends, so `"tele"` is not a stairs cell.
 */
export function isStairsCell(cell) {
  return !!cell && (cell.feat === "exit" || cell.feat === "gate");
}

/** destCell(state, dir) — the floor cell one step from the player in `dir`, or null off-grid. */
function destCell(state, dir) {
  const f = state.floor;
  const [dx, dy] = DIRS[dir];
  const row = f.g[f.py + dy];
  return row ? row[f.px + dx] ?? null : null;
}

/** pickAmongLegal(state, policyRng, avoid) — policyRng.pick among legalDirs whose destination fails `avoid`; null when none qualify. */
function pickAmongLegal(state, policyRng, avoid) {
  const dirs = legalDirs(state).filter((dir) => {
    const cell = destCell(state, dir);
    return cell && !avoid(cell);
  });
  return dirs.length ? policyRng.pick(dirs) : null;
}

/**
 * farmDir(state, policyRng) — the farmer's own movement, replacing
 * `decideAction`'s move whenever the fair bot would move on the farm floor
 * (`makeFarmerPolicy` step iv). NEVER returns a direction whose destination
 * is a stairs cell (`isStairsCell`). Goal order (all via `bfsFirstStep`,
 * mirroring `nearestUnseenDir`/`dirTowardExit`'s own two-pass hazard
 * shape):
 *   (a) nearest unseen cell, avoiding stairs and seen hazards;
 *   (b) nearest unseen cell, avoiding stairs only;
 *   (c) nearest seen dot or chest, avoiding stairs and seen hazards —
 *       Claude's Discretion (82-CONTEXT.md): a human farmer takes every
 *       dot, and dots are the only stores;
 *   (d) the same, avoiding stairs only;
 *   (e) a random legal step (policyRng.pick), avoiding stairs and seen
 *       hazards — Claude's Discretion: the wander after the floor is
 *       cleared, a random legal step that never takes the stairs and keeps
 *       the 100-squares day clock moving;
 *   (f) the same, avoiding stairs only;
 *   (g) null (boxed in — every legal step is the stairs).
 */
export function farmDir(state, policyRng) {
  const seenHazard = (cell) => cell.seen && HAZARD_FEATS.has(cell.feat);
  const stairsOrHazard = (cell) => isStairsCell(cell) || seenHazard(cell);
  const stairsOnly = (cell) => isStairsCell(cell);
  const unseenGoal = (cell) => !cell.seen;
  const dotOrChestGoal = (cell) => cell.seen && (cell.feat === "dot" || cell.feat === "chest");

  return (
    bfsFirstStep(state, unseenGoal, stairsOrHazard) ??
    bfsFirstStep(state, unseenGoal, stairsOnly) ??
    bfsFirstStep(state, dotOrChestGoal, stairsOrHazard) ??
    bfsFirstStep(state, dotOrChestGoal, stairsOnly) ??
    pickAmongLegal(state, policyRng, stairsOrHazard) ??
    pickAmongLegal(state, policyRng, stairsOnly) ??
    null
  );
}

/**
 * hoarderStorePick(state) — the hoarder variant's store policy: buy the
 * store's Rations line with all its gold before anything else, every store
 * visit. There is no GOLD_RESERVE (`chooseStorePurchase`'s own reserve,
 * tools/lib/tuning-bot.mjs) — the hoarder spends everything on food. Returns
 * `{type:"buyItem", idx}` for the first `"buyRations"` stock line with stock
 * left (`rationsLeft`) that the engine's own `storeBuyRefusal` lets through
 * (affordable, and not past the pack's ration cap); `null` when there is none
 * or `c.rations` is already at `BAGS[c.bag].rations` (its target).
 *
 * Phase 87 (STORE-04): the engine now sells the Rations line PER RATION (a d10
 * of them per store, `buyFrom` decrements `left`), so this buys ONE ration per
 * purchase and is asked again on each decision, until the cap, the purse or
 * the shelf runs out. The old one-ration-per-visit note is retired. It reads
 * the engine's refusal, so it can never loop on a buy the engine would refuse.
 */
export function hoarderStorePick(state) {
  const st = state.store;
  if (!st || !Array.isArray(st.stock)) return null;
  const c = state.c;
  const cap = BAGS[c.bag] && BAGS[c.bag].rations;
  if (cap !== undefined && c.rations >= cap) return null;
  const idx = st.stock.findIndex((line) => line.effectId === "buyRations" && !line.sold && rationsLeft(line) > 0 && storeBuyRefusal(c, line) === null);
  return idx === -1 ? null : { type: "buyItem", idx };
}

/**
 * makeFarmerPolicy({variant, farmFloor}) — returns `{policy, stats}` for one
 * `playRun` call. `stats` is a mutable `{campGuard, breaker, boxedIn}`
 * accumulator the returned `policy` closure writes into as it runs.
 *
 * `policy(state, policyRng, ctx)`:
 *   - First, `action = decideAction(state, policyRng, ctx)` — the shipped
 *     fair bot, unmodified. This is a WRAP, never a fork. (Phase 87 STORE-04:
 *     the wrapped fair bot now also tops up rations in a store, one per
 *     purchase, after its gear passes — see tuning-bot.mjs#BOT_RATION_DAYS.)
 *   - Below the farm floor (`state.floor.depth < farmFloor`), `action` is
 *     returned unchanged — a farm-floor-2 run descends exactly like the
 *     honest run until it first reaches floor 2.
 *   - On the farm floor, in order:
 *     (i) hoarder variant, and `action` is `buyItem`/`leaveStore` (the fair
 *         bot's own store branch fired): return `hoarderStorePick(state)`,
 *         or `action` when that is `null` (nothing to buy — leave, exactly
 *         like the fair bot);
 *     (ii) `action` is `camp` but `c.rations < nightlyEats(state)`: the
 *         fair bot's own camp gate (tools/lib/tuning-bot.mjs#decideAction)
 *         reads only the HERO's own appetite (`RACES[c.race].eats`), while
 *         `makeCamp` (engine/movement.js) refuses on the PARTY's real
 *         appetite (`nightlyEats`) — the probe's seed-55434 stall. Increment
 *         `stats.campGuard` and return the farmer move instead of a refused
 *         camp the bot would otherwise repeat until `maxActions`;
 *     (iii) the breaker: `BREAKER_LIMIT` consecutive actions taken out of
 *         combat, with no open decision pending (no store, no
 *         `pendingLoot` items, no `pendingJoiner`, no `pendingFind`, no
 *         `pendingHazard`), whose type is not `move` — increment
 *         `stats.breaker`, reset the counter, and return the farmer move.
 *         The counter resets on any `move` action and on any in-combat
 *         action;
 *     (iv) `action` is `move` and there is no combat: return the farmer
 *         move (`farmDir`) instead — this is what keeps the fair bot's own
 *         `dirTowardExit` from ever walking onto the stairs once the floor
 *         is cleared;
 *     (v) anything else (an in-combat action, or an open-decision action
 *         the breaker above exempted): return `action` unchanged.
 *   - The farmer move is `{type:"move", dir: farmDir(state, policyRng)}`.
 *     When `farmDir` returns `null` (boxed in — every legal step is the
 *     stairs), increment `stats.boxedIn` and return `decideAction`'s own
 *     `action` instead — it may take the stairs, and the run is then tagged
 *     `leftFloor` by `playFarmRun`.
 *   - Neither variant ever adds a camp of its own; both camp only when the
 *     fair bot does (`campThreshold`), never to pass time. The policy never
 *     mutates `state`.
 */
export function makeFarmerPolicy({ variant, farmFloor }) {
  const stats = { campGuard: 0, breaker: 0, boxedIn: 0 };
  let noDecisionStreak = 0;

  const farmerMove = (state, policyRng, fallback) => {
    const dir = farmDir(state, policyRng);
    if (dir === null) {
      stats.boxedIn++;
      return fallback; // decideAction's own action — may take the stairs -> leftFloor
    }
    return { type: "move", dir };
  };

  const policy = (state, policyRng, ctx) => {
    const action = decideAction(state, policyRng, ctx);
    if (state.floor.depth < farmFloor) return action;

    const c = state.c;
    const inCombat = !!state.combat;
    const hasOpenDecision =
      !!state.store ||
      (Array.isArray(state.pendingLoot) && state.pendingLoot.length > 0) ||
      !!state.pendingJoiner ||
      !!state.pendingFind ||
      !!state.pendingHazard ||
      !!state.pendingTeleport;

    // (i) hoarder store branch
    if (variant === "hoarder" && (action.type === "buyItem" || action.type === "leaveStore")) {
      noDecisionStreak = 0; // an open decision (the store) — not a breaker tick
      const pick = hoarderStorePick(state);
      return pick ?? action;
    }

    // (ii) camp guard — the fair bot's own gate reads only the hero's
    // appetite; makeCamp refuses on the party's real one (nightlyEats).
    if (action.type === "camp" && c.rations < nightlyEats(state)) {
      stats.campGuard++;
      noDecisionStreak = 0;
      return farmerMove(state, policyRng, action);
    }

    // Reset the breaker on any move or any in-combat action (checked before
    // the breaker itself fires below).
    if (action.type === "move" || inCombat) {
      noDecisionStreak = 0;
    } else if (!hasOpenDecision) {
      // (iii) the breaker: a consecutive out-of-combat, no-open-decision,
      // non-move action.
      noDecisionStreak++;
      if (noDecisionStreak >= BREAKER_LIMIT) {
        stats.breaker++;
        noDecisionStreak = 0;
        return farmerMove(state, policyRng, action);
      }
      return action;
    }

    // (iv) a move with no combat: the farmer's own movement replaces
    // decideAction's (which may head toward the stairs once the floor is
    // cleared).
    if (action.type === "move" && !inCombat) {
      return farmerMove(state, policyRng, action);
    }

    // (v) anything else (in-combat, or an open decision the breaker above
    // exempted) is unchanged.
    return action;
  };

  return { policy, stats };
}

/**
 * playHonestRun(seed) — the fair bot's normal `playRun`, no policy and no
 * stopWhen, so it is byte-identical to `tune-difficulty`'s own run for this
 * seed (proven by Task 3's honest cross-check against
 * `tools/tune-difficulty.mjs`'s `deathDepth`).
 */
export function playHonestRun(seed) {
  let cause = null;
  const run = playRun(seed, { ...BOT_DEFAULTS }, (events) => {
    for (const e of events) if (e.type === "died") cause = e.cause;
  });
  return {
    seed,
    cls: run.state.c.cls,
    sub: run.state.c.sub,
    race: run.state.c.race,
    day: run.state.day,
    floor: run.state.floor.depth,
    actions: run.actions,
    outcome: run.dead ? "dead" : "stuck",
    cause,
  };
}

/**
 * playFarmRun(seed, {variant, farmFloor, maxActions, maxDays}) — plays one
 * farmer run via `playRun`'s Phase 82 hooks: `policy` from
 * `makeFarmerPolicy`, and `stopWhen` ending the run the instant the run
 * would leave the farm floor upward (`depth > farmFloor` — the farmer is
 * never MADE to stop on first arrival at the farm floor, only once it goes
 * past it) or hits `maxDays`. Returns a row with every field set (`null`,
 * never `undefined`, for anything not applicable to this row's outcome).
 */
export function playFarmRun(seed, { variant, farmFloor, maxActions = FARM_CAPS.maxActions, maxDays = FARM_CAPS.maxDays }) {
  const { policy, stats } = makeFarmerPolicy({ variant, farmFloor });

  let reachedFarmAt = farmFloor === 1 ? 0 : null;
  let leftFloor = false;
  let lastDayBeganAt = 0;
  let rationsBought = 0;
  let cooked = 0;
  let hungryNights = 0;
  let campFailed = 0;
  let cause = null;
  let actionCount = 0;

  const stopWhen = (state) => state.floor.depth > farmFloor || state.day >= maxDays;

  const run = playRun(seed, { ...BOT_DEFAULTS, maxActions, policy, stopWhen }, (events, state) => {
    actionCount++;
    if (reachedFarmAt === null && state.floor.depth === farmFloor) reachedFarmAt = actionCount;
    if (state.floor.depth > farmFloor) leftFloor = true;
    for (const e of events) {
      if (e.type === "dayBegan") lastDayBeganAt = actionCount;
      else if (e.type === "rationsBought") rationsBought += e.amount;
      else if (e.type === "cooked") cooked += e.rations;
      else if (e.type === "wentHungry") hungryNights++;
      else if (e.type === "campFailed") campFailed++;
      else if (e.type === "died") cause = e.cause;
    }
  });

  const day = run.state.day;
  const floor = run.state.floor.depth;
  const actions = run.actions;

  let outcome;
  let capBy = null;
  if (reachedFarmAt === null) {
    outcome = "notReached";
  } else if (leftFloor) {
    outcome = "leftFloor";
  } else if (run.dead) {
    outcome = "dead";
  } else {
    outcome = "unbounded";
    capBy = day >= maxDays ? "days" : "actions";
  }
  const clockMoving = outcome === "unbounded" ? actions - lastDayBeganAt <= CLOCK_WINDOW : null;

  return {
    seed,
    variant,
    farmFloor,
    cls: run.state.c.cls,
    sub: run.state.c.sub,
    race: run.state.c.race,
    day,
    floor,
    actions,
    outcome,
    capBy,
    clockMoving,
    cause,
    reachedFarmAt,
    rationsBought,
    cooked,
    hungryNights,
    campFailed,
    campGuard: stats.campGuard,
    breaker: stats.breaker,
    boxedIn: stats.boxedIn,
  };
}

/** daysDistribution(values) — distribution() (tuning-bot) plus p99, never NaN on an empty set. */
function daysDistribution(values) {
  const sorted = [...values].sort((a, b) => a - b);
  return {
    min: sorted[0] ?? 0,
    p50: percentile(sorted, 0.5),
    p90: percentile(sorted, 0.9),
    p99: percentile(sorted, 0.99),
    max: sorted[sorted.length - 1] ?? 0,
  };
}

/** groupDays(rows, keyFn) — {key: {n, p50, max}} over rows' `.day`, sorted key order. */
function groupDays(rows, keyFn) {
  const groups = {};
  for (const r of rows) (groups[keyFn(r)] ??= []).push(r.day);
  const out = {};
  for (const k of Object.keys(groups).sort()) {
    const sorted = [...groups[k]].sort((a, b) => a - b);
    out[k] = { n: sorted.length, p50: percentile(sorted, 0.5), max: sorted[sorted.length - 1] ?? 0 };
  }
  return out;
}

/** groupDaysWithUnbounded(rows, keyFn) — groupDays plus an `unbounded` count per key. */
function groupDaysWithUnbounded(rows, keyFn) {
  const groups = {};
  for (const r of rows) (groups[keyFn(r)] ??= []).push(r);
  const out = {};
  for (const k of Object.keys(groups).sort()) {
    const list = groups[k];
    const sorted = list.map((r) => r.day).sort((a, b) => a - b);
    out[k] = {
      n: list.length,
      p50: percentile(sorted, 0.5),
      max: sorted[sorted.length - 1] ?? 0,
      unbounded: list.filter((r) => r.outcome === "unbounded").length,
    };
  }
  return out;
}

/**
 * summarizeHonest(rows) — `playHonestRun` rows only. `stuck` rows are
 * excluded from `days`/`depth`/`floor1Deaths` (the same HARN-02 bucketing
 * `tune-difficulty` already applies) but counted in `stuck`. `depth` is the
 * same shape/values as `tune-difficulty --json`'s `deathDepth` (both are
 * `distribution()` over completed rows' floor).
 */
export function summarizeHonest(rows) {
  const completed = rows.filter((r) => r.outcome === "dead");
  const stuck = rows.filter((r) => r.outcome === "stuck");
  const floor1 = completed.filter((r) => r.floor === 1);
  return {
    runs: rows.length,
    completed: completed.length,
    stuck: stuck.length,
    days: daysDistribution(completed.map((r) => r.day)),
    depth: distribution(completed.map((r) => r.floor)),
    floor1Deaths: { n: floor1.length, days: daysDistribution(floor1.map((r) => r.day)) },
    byClass: groupDays(completed, (r) => r.cls),
    byRace: groupDays(completed, (r) => r.race),
  };
}

/**
 * summarizeFarm(rows) — `playFarmRun` rows for ONE variant on ONE farm
 * floor. Only `dead` and `unbounded` rows ("counted") feed the DAYS
 * percentiles; `leftFloor` and `notReached` are counted separately, never
 * folded silently into `counted`. Every numeric field is `0` (never `NaN`)
 * on an empty set.
 */
export function summarizeFarm(rows) {
  const dead = rows.filter((r) => r.outcome === "dead");
  const unbounded = rows.filter((r) => r.outcome === "unbounded");
  const counted = [...dead, ...unbounded];
  const leftFloor = rows.filter((r) => r.outcome === "leftFloor").length;
  const notReached = rows.filter((r) => r.outcome === "notReached").length;
  const unboundedFrozenClock = unbounded.filter((r) => r.clockMoving === false).length;
  const starveDeaths = dead.filter((r) => r.cause === "starve").length;
  const starveShare = dead.length ? starveDeaths / dead.length : 0;

  const sumField = (list, field) => list.reduce((s, r) => s + (r[field] || 0), 0);
  const totals = {
    rationsBought: sumField(rows, "rationsBought"),
    cooked: sumField(rows, "cooked"),
    campGuard: sumField(rows, "campGuard"),
    breaker: sumField(rows, "breaker"),
    boxedIn: sumField(rows, "boxedIn"),
  };
  const hungryNightsMean = counted.length ? Math.round((sumField(counted, "hungryNights") / counted.length) * 10) / 10 : 0;

  return {
    runs: rows.length,
    counted: counted.length,
    dead: dead.length,
    unbounded: unbounded.length,
    unboundedFrozenClock,
    leftFloor,
    notReached,
    days: daysDistribution(counted.map((r) => r.day)),
    starveDeaths,
    starveShare,
    totals,
    hungryNightsMean,
    byClass: groupDaysWithUnbounded(counted, (r) => r.cls),
    byRace: groupDaysWithUnbounded(counted, (r) => r.race),
  };
}

// DAYS_RULES — the three candidate DAYS ranking rules, fixed in code, with
// tests, BEFORE plan 82-02 measures anything (82-CONTEXT.md: "The verdict is
// applied mechanically from the pre-agreed thresholds above"). Consumed by
// Phase 83's SRV-03 (server query) and Phase 84's BOARD-20/26 (YOUR DEAD /
// the DAYS picker copy) — this module only fixes the rule, never applies it
// to a server query itself.
export const DAYS_RULES = Object.freeze({
  mock: Object.freeze({
    ruleLine: "DAYS ranks every run by day (desc), ties by floor (desc).",
    rankKey: Object.freeze({ field: "day", formula: null, filter: null, order: Object.freeze(["day desc", "floor desc"]), display: "day" }),
    voiceLine: null,
  }),
  floor2plus: Object.freeze({
    ruleLine:
      "DAYS ranks only runs that reached floor 2 or deeper (floor >= 2), by day (desc), ties by floor (desc); DEPTH, KILLS and WILMST still list floor-1 deaths.",
    rankKey: Object.freeze({ field: "day", formula: null, filter: "floor >= 2", order: Object.freeze(["day desc", "floor desc"]), display: "day" }),
    voiceLine: "Days on the first floor don't count. That's loitering.",
  }),
  perFloorCap: Object.freeze({
    ruleLine: "DAYS ranks every run by daysKey = min(day, 10 * floor) (desc), ties by floor (desc); the board still displays the true day.",
    rankKey: Object.freeze({ field: "daysKey", formula: "min(day, 10 * floor)", filter: null, order: Object.freeze(["daysKey desc", "floor desc"]), display: "day" }),
    voiceLine: "Only ten days a floor count. The rest is loitering.",
  }),
});

/** strongerVariant(noStairs, hoarder) — the tie-break order: p90, then unbounded count, then max, then "hoarder". */
function strongerVariant(noStairs, hoarder) {
  if (noStairs.days.p90 !== hoarder.days.p90) return noStairs.days.p90 > hoarder.days.p90 ? "noStairs" : "hoarder";
  if (noStairs.unbounded !== hoarder.unbounded) return noStairs.unbounded > hoarder.unbounded ? "noStairs" : "hoarder";
  if (noStairs.days.max !== hoarder.days.max) return noStairs.days.max > hoarder.days.max ? "noStairs" : "hoarder";
  return "hoarder";
}

/**
 * farmVerdict({honest, farm}) — the mechanical verdict, no judgment call.
 * `honest` is `summarizeHonest` output; `farm` is `{"1": {noStairs, hoarder},
 * "2": {...}}` of `summarizeFarm` output (either floor key may be absent —
 * a single-floor measurement is valid input, just gives `branch: null`).
 *
 * Per measured floor: `stronger` is the tie-broken stronger variant;
 * `capHits` is the SUM of both variants' `unbounded` counts (a cap hit by
 * either variant counts, even if it is not the stronger one — 82-CONTEXT.md:
 * "any farmer run hits the cap"); `wins` is `stronger p90 >= honest.days.p99`
 * OR `capHits > 0`; `reason` names which (or both, or neither) fired.
 *
 * `branch` is set ONLY when both floors are measured (a single-floor
 * measurement returns `branch: null` with `note` naming the missing floor —
 * plan 82-02 always measures both floors, so this only matters for a partial
 * smoke run): a floor-2 win gives `"perFloorCap"`; otherwise a floor-1 win
 * gives `"floor2plus"`; otherwise `"mock"`. The corner case where floor 2
 * wins while floor 1 does NOT is deliberately mapped to `"perFloorCap"` —
 * the planner's reading of 82-CONTEXT.md's open corner case, because
 * `perFloorCap` is the only one of the three rules that actually stops
 * floor-2 farming; the user can overrule this reading before plan 82-02
 * records it.
 */
export function farmVerdict({ honest, farm }) {
  const honestP99 = honest.days.p99;
  const floors = {};
  for (const floorKey of Object.keys(farm)) {
    const { noStairs, hoarder } = farm[floorKey];
    const stronger = strongerVariant(noStairs, hoarder);
    const strongerSummary = stronger === "noStairs" ? noStairs : hoarder;
    const strongerP90 = strongerSummary.days.p90;
    const capHits = noStairs.unbounded + hoarder.unbounded;
    const p90Win = strongerP90 >= honestP99;
    const capWin = capHits > 0;
    const wins = p90Win || capWin;
    const reason = p90Win && capWin ? "both" : p90Win ? "p90>=p99" : capWin ? "capHit" : "none";
    floors[floorKey] = { stronger, strongerP90, capHits, wins, reason };
  }

  let branch = null;
  let note = null;
  if (floors["1"] && floors["2"]) {
    if (floors["2"].wins) branch = "perFloorCap";
    else if (floors["1"].wins) branch = "floor2plus";
    else branch = "mock";
  } else {
    const missing = floors["1"] ? "2" : "1";
    note = `Only floor ${missing === "2" ? "1" : "2"} was measured; floor ${missing} is missing — branch is undecided.`;
  }

  const rule = branch ? DAYS_RULES[branch] : null;
  return {
    honestP99,
    floors,
    branch,
    ruleLine: rule ? rule.ruleLine : null,
    rankKey: rule ? rule.rankKey : null,
    voiceLine: rule ? rule.voiceLine : null,
    note,
  };
}

/**
 * buildFarmReport({meta, honestRows, farmRows}) — assembles the full report:
 * `{meta, honest: {summary, rows}, farm: {F: {V: {summary, rows}}}, verdict}`.
 * `farmRows` is `{"1": {noStairs: rows, hoarder: rows}, ...}` (only the
 * measured floor keys need be present). Plain JSON data only — the whole
 * return value survives a `JSON.parse(JSON.stringify(...))` round trip
 * unchanged.
 */
export function buildFarmReport({ meta, honestRows, farmRows }) {
  const honestSummary = summarizeHonest(honestRows);
  const farm = {};
  const farmSummaries = {};
  for (const floorKey of Object.keys(farmRows)) {
    farm[floorKey] = {};
    farmSummaries[floorKey] = {};
    for (const variant of FARM_VARIANTS) {
      const rows = farmRows[floorKey][variant] || [];
      const summary = summarizeFarm(rows);
      farm[floorKey][variant] = { summary, rows };
      farmSummaries[floorKey][variant] = summary;
    }
  }
  const verdict = farmVerdict({ honest: honestSummary, farm: farmSummaries });
  return { meta, honest: { summary: honestSummary, rows: honestRows }, farm, verdict };
}

/** pct1(ratio) — a 0..1 ratio as a one-decimal percentage string. */
function pct1(ratio) {
  return `${(ratio * 100).toFixed(1)}%`;
}

/**
 * formatFarmReport(report) — the deterministic markdown block the CLI prints
 * and the ledger (docs/DAYS-FARMING.md, plan 82-02) pastes verbatim. No
 * commit hash, no timestamp — the same `report` object always renders the
 * same string. Headings are `###`/`####` only.
 */
export function formatFarmReport(report) {
  const { meta, honest, farm, verdict } = report;
  const lines = [];

  lines.push(
    `*seeds=${meta.seeds} (${meta.seedList})  farmFloors=[${meta.farmFloors.join(",")}]  caps: maxActions=${meta.caps.maxActions} maxDays=${meta.caps.maxDays}  bot: exploreBudget=${meta.bot.exploreBudget} campThreshold=${meta.bot.campThreshold}*`,
  );

  lines.push("");
  lines.push("### Honest baseline");
  lines.push("");
  lines.push("| runs | completed | stuck | days p50 | days p90 | days p99 | days max |");
  lines.push("|---|---|---|---|---|---|---|");
  lines.push(
    `| ${honest.summary.runs} | ${honest.summary.completed} | ${honest.summary.stuck} | ${honest.summary.days.p50} | ${honest.summary.days.p90} | ${honest.summary.days.p99} | ${honest.summary.days.max} |`,
  );
  lines.push("");
  lines.push("| floor-1 deaths n | days p50 | days p90 | days p99 | days max |");
  lines.push("|---|---|---|---|---|");
  lines.push(
    `| ${honest.summary.floor1Deaths.n} | ${honest.summary.floor1Deaths.days.p50} | ${honest.summary.floor1Deaths.days.p90} | ${honest.summary.floor1Deaths.days.p99} | ${honest.summary.floor1Deaths.days.max} |`,
  );

  for (const floorKey of Object.keys(farm).sort()) {
    lines.push("");
    lines.push(`### Farm floor ${floorKey}`);
    lines.push("");
    lines.push(
      "| variant | runs | counted | dead | unbounded (frozen clock) | leftFloor | notReached | days p50 | days p90 | days p99 | days max | starve % | rations bought | cooked | mean hungry nights | camp guard | breaker | boxed in |",
    );
    lines.push("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|");
    for (const variant of FARM_VARIANTS) {
      const s = farm[floorKey][variant].summary;
      lines.push(
        `| ${variant} | ${s.runs} | ${s.counted} | ${s.dead} | ${s.unbounded} (${s.unboundedFrozenClock}) | ${s.leftFloor} | ${s.notReached} | ${s.days.p50} | ${s.days.p90} | ${s.days.p99} | ${s.days.max} | ${pct1(s.starveShare)} | ${s.totals.rationsBought} | ${s.totals.cooked} | ${s.hungryNightsMean} | ${s.totals.campGuard} | ${s.totals.breaker} | ${s.totals.boxedIn} |`,
      );
    }

    const strongerKey = verdict.floors[floorKey] ? verdict.floors[floorKey].stronger : FARM_VARIANTS[0];
    const strongerSummary = farm[floorKey][strongerKey].summary;

    lines.push("");
    lines.push(`#### By race (stronger variant: ${strongerKey})`);
    lines.push("");
    lines.push("| race | n | days p50 | days max | unbounded |");
    lines.push("|---|---|---|---|---|");
    for (const race of Object.keys(strongerSummary.byRace).sort()) {
      const r = strongerSummary.byRace[race];
      lines.push(`| ${race} | ${r.n} | ${r.p50} | ${r.max} | ${r.unbounded} |`);
    }

    lines.push("");
    lines.push(`#### By class (stronger variant: ${strongerKey})`);
    lines.push("");
    lines.push("| class | n | days p50 | days max | unbounded |");
    lines.push("|---|---|---|---|---|");
    for (const cls of Object.keys(strongerSummary.byClass).sort()) {
      const r = strongerSummary.byClass[cls];
      lines.push(`| ${cls} | ${r.n} | ${r.p50} | ${r.max} | ${r.unbounded} |`);
    }
  }

  lines.push("");
  lines.push("### Verdict");
  lines.push("");
  lines.push("| floor | stronger | stronger p90 | honest p99 | cap hits | wins | reason |");
  lines.push("|---|---|---|---|---|---|---|");
  for (const floorKey of Object.keys(verdict.floors).sort()) {
    const f = verdict.floors[floorKey];
    lines.push(`| ${floorKey} | ${f.stronger} | ${f.strongerP90} | ${verdict.honestP99} | ${f.capHits} | ${f.wins} | ${f.reason} |`);
  }
  lines.push("");
  lines.push(`Branch: ${verdict.branch ?? "none"}`);
  lines.push(`Rule: ${verdict.ruleLine ?? verdict.note ?? "no rule (insufficient floors measured)"}`);

  return lines.join("\n");
}
