// content/achievements.js
//
// The achievement catalog: the single source for the Phase 99 tracker, the
// Phase 100 achievements list, the Phase 101 Play mirror and the Play Console
// import zip (tools/achievements-zip.mjs). Pure data (content-is-pure-data):
// no imports, no function leaves, browser-safe.
//
// 77 entries in list order. Every entry carries the same fourteen fields:
//   id           stable snake_case id; equals the icon file stem without the
//                ach_ prefix and the .png suffix. The track of a tiered entry
//                is its id without the _t<tier> suffix.
//   name         Play name. Unique, printable ASCII, no commas, <= 100 chars.
//                Goes to Play and freezes when the zip is imported.
//   description  Play description. Printable ASCII, no commas, <= 500 chars.
//                Goes to Play and freezes when the zip is imported.
//   line         the in-game unlock line. Never sent to Play, so it can be
//                reworded later.
//   trigger      a declarative rule from TRIGGER_VOCABULARY (below).
//   threshold    the number the measured value must reach, or null when the
//                trigger has no number. A threshold is met when the measured
//                value is AT LEAST the threshold.
//   tier         1..4 on a tiered entry, null otherwise.
//   points       Play points: 5..200 in multiples of 5 (Play caps a game at 2000).
//   initialState "Hidden" or "Revealed" (permanent once the zip is imported).
//   type         "standard" or "incremental" (permanent once the zip is imported).
//   steps        Play steps: equals threshold on an incremental entry, null
//                on a standard one (Play allows 1..10000).
//   reveals      ids this entry reveals when it unlocks (empty array if none).
//   listOrder    10 x position, so a later import can interleave new entries.
//   icon         { play, ingame } paths relative to achievements/, equal to
//                one row of achievements/manifest.json (file_play / file_ingame).
//
// Trigger kinds and their key sets (every key is present, null when unused):
//   lifetimeCounter  { kind, counter, group }  group is a BESTIARY key for kills
//   singleRunBest    { kind, metric, race, parentClass }  race / parentClass are
//                    RACES / CLASSES keys that filter which runs count
//   singleRunFlag    { kind, flag }  a numeric threshold is the floor on which
//                    the flag is judged; null means the moment the flag holds
//   deathCause       { kind, causes, floor }  causes are CAUSE_TEXT keys (null
//                    means any real death); floor is null or the death floor
//   lifetimeFlagPair { kind, flags }  met when both lifetime flags are set
//   distinctSetCount { kind, set }
//
// What each vocabulary word measures (Phase 99 implements it):
//   deaths     real deaths with abandons excluded.
//   kills      every foe that dies in the hero's fights whoever struck it (hero,
//              Joiner or summon) plus Walking Dead destroyed by Turn Undead.
//   joinersAccepted  joinerJoined events.
//   joinersFallen    memberDowned plus joinerMurdered events.
//   parleysWon       parleyWon events.
//   trapsSurvived    each trapSprung that does not end in a trap death.
//   depth      the best floor reached in a run (state.floor.depth).
//   days       state.day.
//   wilmstHeld the most wilmst held at once in a run (spending never counts
//              against it).
//   fleesWon   fled events with reason escaped in one run (door, cloaker,
//              tracked and smoke escapes do not count).
//   fullyDressed     all five equipment slots (weapon not Fists, armour not
//              Nothing, jewelry1, jewelry2, cloak) filled at the same moment.
//   nakedAtFirstStep all five slots empty at the hero's first step and none
//              filled again before the judged floor (bag items and the torch
//              do not count).
//   noHealingPotion  no potionDrunk of a healing potion by the hero in the run
//              (a Joiner's potion and the magic potions do not break it).
//   diseaseLeftOnOneHp / poisonLeftOnOneHp  lifetime flags set when that
//              affliction has once left the hero on exactly 1 HP.
//   subClassesDelved the distinct sub-classes a delve was started with (an
//              abandoned delve still counts as started).
//
// The name, description and line copy is written in plan 98-02; until then
// the three copy fields are empty strings.

export const TRIGGER_VOCABULARY = Object.freeze({
  kinds: Object.freeze(["lifetimeCounter", "singleRunBest", "singleRunFlag", "deathCause", "lifetimeFlagPair", "distinctSetCount"]),
  counters: Object.freeze(["deaths", "kills", "joinersAccepted", "joinersFallen", "parleysWon", "trapsSurvived"]),
  metrics: Object.freeze(["depth", "days", "wilmstHeld", "fleesWon"]),
  runFlags: Object.freeze(["fullyDressed", "nakedAtFirstStep", "noHealingPotion"]),
  lifetimeFlags: Object.freeze(["diseaseLeftOnOneHp", "poisonLeftOnOneHp"]),
  sets: Object.freeze(["subClassesDelved"]),
});

export const ACHIEVEMENTS = Object.freeze([
  {
    id: "depth_t1",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "singleRunBest", metric: "depth", race: null, parentClass: null },
    threshold: 5,
    tier: 1,
    points: 10,
    initialState: "Revealed",
    type: "incremental",
    steps: 5,
    reveals: ["death_falling"],
    listOrder: 10,
    icon: { play: "play/ach_depth_t1.png", ingame: "ingame/ach_depth_t1.png" },
  },
  {
    id: "depth_t2",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "singleRunBest", metric: "depth", race: null, parentClass: null },
    threshold: 10,
    tier: 2,
    points: 20,
    initialState: "Revealed",
    type: "incremental",
    steps: 10,
    reveals: [],
    listOrder: 20,
    icon: { play: "play/ach_depth_t2.png", ingame: "ingame/ach_depth_t2.png" },
  },
  {
    id: "depth_t3",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "singleRunBest", metric: "depth", race: null, parentClass: null },
    threshold: 15,
    tier: 3,
    points: 30,
    initialState: "Revealed",
    type: "incremental",
    steps: 15,
    reveals: [],
    listOrder: 30,
    icon: { play: "play/ach_depth_t3.png", ingame: "ingame/ach_depth_t3.png" },
  },
  {
    id: "unicorn",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "singleRunBest", metric: "depth", race: null, parentClass: null },
    threshold: 20,
    tier: null,
    points: 100,
    initialState: "Revealed",
    type: "incremental",
    steps: 20,
    reveals: [],
    listOrder: 40,
    icon: { play: "play/ach_unicorn.png", ingame: "ingame/ach_unicorn.png" },
  },
  {
    id: "death_falling",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "deathCause", causes: ["fall","gorge"], floor: null },
    threshold: null,
    tier: null,
    points: 5,
    initialState: "Hidden",
    type: "standard",
    steps: null,
    reveals: ["ether_entombed"],
    listOrder: 50,
    icon: { play: "play/ach_death_falling.png", ingame: "ingame/ach_death_falling.png" },
  },
  {
    id: "ether_entombed",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "deathCause", causes: ["entombed"], floor: null },
    threshold: null,
    tier: null,
    points: 10,
    initialState: "Hidden",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 60,
    icon: { play: "play/ach_ether_entombed.png", ingame: "ingame/ach_ether_entombed.png" },
  },
  {
    id: "fully_dressed",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "singleRunFlag", flag: "fullyDressed" },
    threshold: null,
    tier: null,
    points: 10,
    initialState: "Revealed",
    type: "standard",
    steps: null,
    reveals: ["naked_ambition"],
    listOrder: 70,
    icon: { play: "play/ach_fully_dressed.png", ingame: "ingame/ach_fully_dressed.png" },
  },
  {
    id: "naked_ambition",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "singleRunFlag", flag: "nakedAtFirstStep" },
    threshold: 5,
    tier: null,
    points: 25,
    initialState: "Hidden",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 80,
    icon: { play: "play/ach_naked_ambition.png", ingame: "ingame/ach_naked_ambition.png" },
  },
  {
    id: "teetotaler",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "singleRunFlag", flag: "noHealingPotion" },
    threshold: 5,
    tier: null,
    points: 15,
    initialState: "Revealed",
    type: "standard",
    steps: null,
    reveals: ["read_the_label"],
    listOrder: 90,
    icon: { play: "play/ach_teetotaler.png", ingame: "ingame/ach_teetotaler.png" },
  },
  {
    id: "read_the_label",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "deathCause", causes: ["potion"], floor: null },
    threshold: null,
    tier: null,
    points: 5,
    initialState: "Hidden",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 100,
    icon: { play: "play/ach_read_the_label.png", ingame: "ingame/ach_read_the_label.png" },
  },
  {
    id: "race_human",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "singleRunBest", metric: "depth", race: "Human", parentClass: null },
    threshold: 5,
    tier: null,
    points: 10,
    initialState: "Revealed",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 110,
    icon: { play: "play/ach_race_human.png", ingame: "ingame/ach_race_human.png" },
  },
  {
    id: "race_elven",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "singleRunBest", metric: "depth", race: "Elven", parentClass: null },
    threshold: 5,
    tier: null,
    points: 10,
    initialState: "Revealed",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 120,
    icon: { play: "play/ach_race_elven.png", ingame: "ingame/ach_race_elven.png" },
  },
  {
    id: "race_dwarven",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "singleRunBest", metric: "depth", race: "Dwarven", parentClass: null },
    threshold: 5,
    tier: null,
    points: 10,
    initialState: "Revealed",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 130,
    icon: { play: "play/ach_race_dwarven.png", ingame: "ingame/ach_race_dwarven.png" },
  },
  {
    id: "race_wilmsry",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "singleRunBest", metric: "depth", race: "Wilmsry", parentClass: null },
    threshold: 5,
    tier: null,
    points: 10,
    initialState: "Revealed",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 140,
    icon: { play: "play/ach_race_wilmsry.png", ingame: "ingame/ach_race_wilmsry.png" },
  },
  {
    id: "race_fridgian",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "singleRunBest", metric: "depth", race: "Fridgian", parentClass: null },
    threshold: 5,
    tier: null,
    points: 10,
    initialState: "Revealed",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 150,
    icon: { play: "play/ach_race_fridgian.png", ingame: "ingame/ach_race_fridgian.png" },
  },
  {
    id: "race_troll",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "singleRunBest", metric: "depth", race: "Troll", parentClass: null },
    threshold: 5,
    tier: null,
    points: 10,
    initialState: "Revealed",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 160,
    icon: { play: "play/ach_race_troll.png", ingame: "ingame/ach_race_troll.png" },
  },
  {
    id: "class_magic_user",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "singleRunBest", metric: "depth", race: null, parentClass: "Magic User" },
    threshold: 5,
    tier: null,
    points: 10,
    initialState: "Revealed",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 170,
    icon: { play: "play/ach_class_magic_user.png", ingame: "ingame/ach_class_magic_user.png" },
  },
  {
    id: "class_fighter",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "singleRunBest", metric: "depth", race: null, parentClass: "Fighter" },
    threshold: 5,
    tier: null,
    points: 10,
    initialState: "Revealed",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 180,
    icon: { play: "play/ach_class_fighter.png", ingame: "ingame/ach_class_fighter.png" },
  },
  {
    id: "class_thief",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "singleRunBest", metric: "depth", race: null, parentClass: "Thief" },
    threshold: 5,
    tier: null,
    points: 10,
    initialState: "Revealed",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 190,
    icon: { play: "play/ach_class_thief.png", ingame: "ingame/ach_class_thief.png" },
  },
  {
    id: "tourist",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "distinctSetCount", set: "subClassesDelved" },
    threshold: 24,
    tier: null,
    points: 30,
    initialState: "Revealed",
    type: "incremental",
    steps: 24,
    reveals: [],
    listOrder: 200,
    icon: { play: "play/ach_tourist.png", ingame: "ingame/ach_tourist.png" },
  },
  {
    id: "survivor_t1",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "singleRunBest", metric: "days", race: null, parentClass: null },
    threshold: 10,
    tier: 1,
    points: 5,
    initialState: "Revealed",
    type: "incremental",
    steps: 10,
    reveals: ["death_starvation"],
    listOrder: 210,
    icon: { play: "play/ach_survivor_t1.png", ingame: "ingame/ach_survivor_t1.png" },
  },
  {
    id: "survivor_t2",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "singleRunBest", metric: "days", race: null, parentClass: null },
    threshold: 25,
    tier: 2,
    points: 10,
    initialState: "Revealed",
    type: "incremental",
    steps: 25,
    reveals: [],
    listOrder: 220,
    icon: { play: "play/ach_survivor_t2.png", ingame: "ingame/ach_survivor_t2.png" },
  },
  {
    id: "survivor_t3",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "singleRunBest", metric: "days", race: null, parentClass: null },
    threshold: 50,
    tier: 3,
    points: 15,
    initialState: "Revealed",
    type: "incremental",
    steps: 50,
    reveals: [],
    listOrder: 230,
    icon: { play: "play/ach_survivor_t3.png", ingame: "ingame/ach_survivor_t3.png" },
  },
  {
    id: "survivor_t4",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "singleRunBest", metric: "days", race: null, parentClass: null },
    threshold: 100,
    tier: 4,
    points: 25,
    initialState: "Revealed",
    type: "incremental",
    steps: 100,
    reveals: [],
    listOrder: 240,
    icon: { play: "play/ach_survivor_t4.png", ingame: "ingame/ach_survivor_t4.png" },
  },
  {
    id: "death_starvation",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "deathCause", causes: ["starve"], floor: null },
    threshold: null,
    tier: null,
    points: 5,
    initialState: "Hidden",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 250,
    icon: { play: "play/ach_death_starvation.png", ingame: "ingame/ach_death_starvation.png" },
  },
  {
    id: "hoarder_t1",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "singleRunBest", metric: "wilmstHeld", race: null, parentClass: null },
    threshold: 2000,
    tier: 1,
    points: 5,
    initialState: "Revealed",
    type: "incremental",
    steps: 2000,
    reveals: [],
    listOrder: 260,
    icon: { play: "play/ach_hoarder_t1.png", ingame: "ingame/ach_hoarder_t1.png" },
  },
  {
    id: "hoarder_t2",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "singleRunBest", metric: "wilmstHeld", race: null, parentClass: null },
    threshold: 5000,
    tier: 2,
    points: 10,
    initialState: "Revealed",
    type: "incremental",
    steps: 5000,
    reveals: [],
    listOrder: 270,
    icon: { play: "play/ach_hoarder_t2.png", ingame: "ingame/ach_hoarder_t2.png" },
  },
  {
    id: "hoarder_t3",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "singleRunBest", metric: "wilmstHeld", race: null, parentClass: null },
    threshold: 8000,
    tier: 3,
    points: 15,
    initialState: "Revealed",
    type: "incremental",
    steps: 8000,
    reveals: [],
    listOrder: 280,
    icon: { play: "play/ach_hoarder_t3.png", ingame: "ingame/ach_hoarder_t3.png" },
  },
  {
    id: "hoarder_t4",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "singleRunBest", metric: "wilmstHeld", race: null, parentClass: null },
    threshold: 10000,
    tier: 4,
    points: 25,
    initialState: "Revealed",
    type: "incremental",
    steps: 10000,
    reveals: [],
    listOrder: 290,
    icon: { play: "play/ach_hoarder_t4.png", ingame: "ingame/ach_hoarder_t4.png" },
  },
  {
    id: "trap_survivor_t1",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "trapsSurvived", group: null },
    threshold: 10,
    tier: 1,
    points: 5,
    initialState: "Revealed",
    type: "incremental",
    steps: 10,
    reveals: ["death_trap"],
    listOrder: 300,
    icon: { play: "play/ach_trap_survivor_t1.png", ingame: "ingame/ach_trap_survivor_t1.png" },
  },
  {
    id: "trap_survivor_t2",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "trapsSurvived", group: null },
    threshold: 25,
    tier: 2,
    points: 10,
    initialState: "Revealed",
    type: "incremental",
    steps: 25,
    reveals: [],
    listOrder: 310,
    icon: { play: "play/ach_trap_survivor_t2.png", ingame: "ingame/ach_trap_survivor_t2.png" },
  },
  {
    id: "trap_survivor_t3",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "trapsSurvived", group: null },
    threshold: 50,
    tier: 3,
    points: 15,
    initialState: "Revealed",
    type: "incremental",
    steps: 50,
    reveals: [],
    listOrder: 320,
    icon: { play: "play/ach_trap_survivor_t3.png", ingame: "ingame/ach_trap_survivor_t3.png" },
  },
  {
    id: "trap_survivor_t4",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "trapsSurvived", group: null },
    threshold: 100,
    tier: 4,
    points: 25,
    initialState: "Revealed",
    type: "incremental",
    steps: 100,
    reveals: [],
    listOrder: 330,
    icon: { play: "play/ach_trap_survivor_t4.png", ingame: "ingame/ach_trap_survivor_t4.png" },
  },
  {
    id: "death_trap",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "deathCause", causes: ["trap"], floor: null },
    threshold: null,
    tier: null,
    points: 5,
    initialState: "Hidden",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 340,
    icon: { play: "play/ach_death_trap.png", ingame: "ingame/ach_death_trap.png" },
  },
  {
    id: "party_animal_t1",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "joinersAccepted", group: null },
    threshold: 10,
    tier: 1,
    points: 5,
    initialState: "Revealed",
    type: "incremental",
    steps: 10,
    reveals: [],
    listOrder: 350,
    icon: { play: "play/ach_party_animal_t1.png", ingame: "ingame/ach_party_animal_t1.png" },
  },
  {
    id: "party_animal_t2",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "joinersAccepted", group: null },
    threshold: 25,
    tier: 2,
    points: 10,
    initialState: "Revealed",
    type: "incremental",
    steps: 25,
    reveals: [],
    listOrder: 360,
    icon: { play: "play/ach_party_animal_t2.png", ingame: "ingame/ach_party_animal_t2.png" },
  },
  {
    id: "party_animal_t3",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "joinersAccepted", group: null },
    threshold: 50,
    tier: 3,
    points: 15,
    initialState: "Revealed",
    type: "incremental",
    steps: 50,
    reveals: [],
    listOrder: 370,
    icon: { play: "play/ach_party_animal_t3.png", ingame: "ingame/ach_party_animal_t3.png" },
  },
  {
    id: "party_animal_t4",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "joinersAccepted", group: null },
    threshold: 100,
    tier: 4,
    points: 25,
    initialState: "Revealed",
    type: "incremental",
    steps: 100,
    reveals: [],
    listOrder: 380,
    icon: { play: "play/ach_party_animal_t4.png", ingame: "ingame/ach_party_animal_t4.png" },
  },
  {
    id: "human_shields_t1",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "joinersFallen", group: null },
    threshold: 5,
    tier: 1,
    points: 5,
    initialState: "Revealed",
    type: "incremental",
    steps: 5,
    reveals: [],
    listOrder: 390,
    icon: { play: "play/ach_human_shields_t1.png", ingame: "ingame/ach_human_shields_t1.png" },
  },
  {
    id: "human_shields_t2",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "joinersFallen", group: null },
    threshold: 10,
    tier: 2,
    points: 10,
    initialState: "Revealed",
    type: "incremental",
    steps: 10,
    reveals: [],
    listOrder: 400,
    icon: { play: "play/ach_human_shields_t2.png", ingame: "ingame/ach_human_shields_t2.png" },
  },
  {
    id: "human_shields_t3",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "joinersFallen", group: null },
    threshold: 25,
    tier: 3,
    points: 15,
    initialState: "Revealed",
    type: "incremental",
    steps: 25,
    reveals: [],
    listOrder: 410,
    icon: { play: "play/ach_human_shields_t3.png", ingame: "ingame/ach_human_shields_t3.png" },
  },
  {
    id: "human_shields_t4",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "joinersFallen", group: null },
    threshold: 50,
    tier: 4,
    points: 25,
    initialState: "Revealed",
    type: "incremental",
    steps: 50,
    reveals: [],
    listOrder: 420,
    icon: { play: "play/ach_human_shields_t4.png", ingame: "ingame/ach_human_shields_t4.png" },
  },
  {
    id: "parlay_t1",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "parleysWon", group: null },
    threshold: 10,
    tier: 1,
    points: 5,
    initialState: "Revealed",
    type: "incremental",
    steps: 10,
    reveals: ["chicken"],
    listOrder: 430,
    icon: { play: "play/ach_parlay_t1.png", ingame: "ingame/ach_parlay_t1.png" },
  },
  {
    id: "parlay_t2",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "parleysWon", group: null },
    threshold: 25,
    tier: 2,
    points: 10,
    initialState: "Revealed",
    type: "incremental",
    steps: 25,
    reveals: [],
    listOrder: 440,
    icon: { play: "play/ach_parlay_t2.png", ingame: "ingame/ach_parlay_t2.png" },
  },
  {
    id: "parlay_t3",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "parleysWon", group: null },
    threshold: 50,
    tier: 3,
    points: 15,
    initialState: "Revealed",
    type: "incremental",
    steps: 50,
    reveals: [],
    listOrder: 450,
    icon: { play: "play/ach_parlay_t3.png", ingame: "ingame/ach_parlay_t3.png" },
  },
  {
    id: "parlay_t4",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "parleysWon", group: null },
    threshold: 100,
    tier: 4,
    points: 25,
    initialState: "Revealed",
    type: "incremental",
    steps: 100,
    reveals: [],
    listOrder: 460,
    icon: { play: "play/ach_parlay_t4.png", ingame: "ingame/ach_parlay_t4.png" },
  },
  {
    id: "chicken",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "singleRunBest", metric: "fleesWon", race: null, parentClass: null },
    threshold: 10,
    tier: null,
    points: 15,
    initialState: "Hidden",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 470,
    icon: { play: "play/ach_chicken.png", ingame: "ingame/ach_chicken.png" },
  },
  {
    id: "kills_beasts_t1",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Beasts" },
    threshold: 50,
    tier: 1,
    points: 5,
    initialState: "Revealed",
    type: "incremental",
    steps: 50,
    reveals: [],
    listOrder: 480,
    icon: { play: "play/ach_kills_beasts_t1.png", ingame: "ingame/ach_kills_beasts_t1.png" },
  },
  {
    id: "kills_beasts_t2",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Beasts" },
    threshold: 100,
    tier: 2,
    points: 10,
    initialState: "Revealed",
    type: "incremental",
    steps: 100,
    reveals: [],
    listOrder: 490,
    icon: { play: "play/ach_kills_beasts_t2.png", ingame: "ingame/ach_kills_beasts_t2.png" },
  },
  {
    id: "kills_beasts_t3",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Beasts" },
    threshold: 200,
    tier: 3,
    points: 15,
    initialState: "Revealed",
    type: "incremental",
    steps: 200,
    reveals: [],
    listOrder: 500,
    icon: { play: "play/ach_kills_beasts_t3.png", ingame: "ingame/ach_kills_beasts_t3.png" },
  },
  {
    id: "kills_beasts_t4",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Beasts" },
    threshold: 500,
    tier: 4,
    points: 25,
    initialState: "Revealed",
    type: "incremental",
    steps: 500,
    reveals: [],
    listOrder: 510,
    icon: { play: "play/ach_kills_beasts_t4.png", ingame: "ingame/ach_kills_beasts_t4.png" },
  },
  {
    id: "kills_demons_t1",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Demons" },
    threshold: 50,
    tier: 1,
    points: 5,
    initialState: "Revealed",
    type: "incremental",
    steps: 50,
    reveals: [],
    listOrder: 520,
    icon: { play: "play/ach_kills_demons_t1.png", ingame: "ingame/ach_kills_demons_t1.png" },
  },
  {
    id: "kills_demons_t2",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Demons" },
    threshold: 100,
    tier: 2,
    points: 10,
    initialState: "Revealed",
    type: "incremental",
    steps: 100,
    reveals: [],
    listOrder: 530,
    icon: { play: "play/ach_kills_demons_t2.png", ingame: "ingame/ach_kills_demons_t2.png" },
  },
  {
    id: "kills_demons_t3",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Demons" },
    threshold: 200,
    tier: 3,
    points: 15,
    initialState: "Revealed",
    type: "incremental",
    steps: 200,
    reveals: [],
    listOrder: 540,
    icon: { play: "play/ach_kills_demons_t3.png", ingame: "ingame/ach_kills_demons_t3.png" },
  },
  {
    id: "kills_demons_t4",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Demons" },
    threshold: 500,
    tier: 4,
    points: 25,
    initialState: "Revealed",
    type: "incremental",
    steps: 500,
    reveals: [],
    listOrder: 550,
    icon: { play: "play/ach_kills_demons_t4.png", ingame: "ingame/ach_kills_demons_t4.png" },
  },
  {
    id: "kills_humans_t1",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Humans" },
    threshold: 50,
    tier: 1,
    points: 5,
    initialState: "Revealed",
    type: "incremental",
    steps: 50,
    reveals: [],
    listOrder: 560,
    icon: { play: "play/ach_kills_humans_t1.png", ingame: "ingame/ach_kills_humans_t1.png" },
  },
  {
    id: "kills_humans_t2",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Humans" },
    threshold: 100,
    tier: 2,
    points: 10,
    initialState: "Revealed",
    type: "incremental",
    steps: 100,
    reveals: [],
    listOrder: 570,
    icon: { play: "play/ach_kills_humans_t2.png", ingame: "ingame/ach_kills_humans_t2.png" },
  },
  {
    id: "kills_humans_t3",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Humans" },
    threshold: 200,
    tier: 3,
    points: 15,
    initialState: "Revealed",
    type: "incremental",
    steps: 200,
    reveals: [],
    listOrder: 580,
    icon: { play: "play/ach_kills_humans_t3.png", ingame: "ingame/ach_kills_humans_t3.png" },
  },
  {
    id: "kills_humans_t4",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Humans" },
    threshold: 500,
    tier: 4,
    points: 25,
    initialState: "Revealed",
    type: "incremental",
    steps: 500,
    reveals: [],
    listOrder: 590,
    icon: { play: "play/ach_kills_humans_t4.png", ingame: "ingame/ach_kills_humans_t4.png" },
  },
  {
    id: "kills_lair_beasts_t1",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Lair Beasts" },
    threshold: 50,
    tier: 1,
    points: 5,
    initialState: "Revealed",
    type: "incremental",
    steps: 50,
    reveals: [],
    listOrder: 600,
    icon: { play: "play/ach_kills_lair_beasts_t1.png", ingame: "ingame/ach_kills_lair_beasts_t1.png" },
  },
  {
    id: "kills_lair_beasts_t2",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Lair Beasts" },
    threshold: 100,
    tier: 2,
    points: 10,
    initialState: "Revealed",
    type: "incremental",
    steps: 100,
    reveals: [],
    listOrder: 610,
    icon: { play: "play/ach_kills_lair_beasts_t2.png", ingame: "ingame/ach_kills_lair_beasts_t2.png" },
  },
  {
    id: "kills_lair_beasts_t3",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Lair Beasts" },
    threshold: 200,
    tier: 3,
    points: 15,
    initialState: "Revealed",
    type: "incremental",
    steps: 200,
    reveals: [],
    listOrder: 620,
    icon: { play: "play/ach_kills_lair_beasts_t3.png", ingame: "ingame/ach_kills_lair_beasts_t3.png" },
  },
  {
    id: "kills_lair_beasts_t4",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Lair Beasts" },
    threshold: 500,
    tier: 4,
    points: 25,
    initialState: "Revealed",
    type: "incremental",
    steps: 500,
    reveals: [],
    listOrder: 630,
    icon: { play: "play/ach_kills_lair_beasts_t4.png", ingame: "ingame/ach_kills_lair_beasts_t4.png" },
  },
  {
    id: "kills_magical_t1",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Magical" },
    threshold: 50,
    tier: 1,
    points: 5,
    initialState: "Revealed",
    type: "incremental",
    steps: 50,
    reveals: [],
    listOrder: 640,
    icon: { play: "play/ach_kills_magical_t1.png", ingame: "ingame/ach_kills_magical_t1.png" },
  },
  {
    id: "kills_magical_t2",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Magical" },
    threshold: 100,
    tier: 2,
    points: 10,
    initialState: "Revealed",
    type: "incremental",
    steps: 100,
    reveals: [],
    listOrder: 650,
    icon: { play: "play/ach_kills_magical_t2.png", ingame: "ingame/ach_kills_magical_t2.png" },
  },
  {
    id: "kills_magical_t3",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Magical" },
    threshold: 200,
    tier: 3,
    points: 15,
    initialState: "Revealed",
    type: "incremental",
    steps: 200,
    reveals: [],
    listOrder: 660,
    icon: { play: "play/ach_kills_magical_t3.png", ingame: "ingame/ach_kills_magical_t3.png" },
  },
  {
    id: "kills_magical_t4",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Magical" },
    threshold: 500,
    tier: 4,
    points: 25,
    initialState: "Revealed",
    type: "incremental",
    steps: 500,
    reveals: [],
    listOrder: 670,
    icon: { play: "play/ach_kills_magical_t4.png", ingame: "ingame/ach_kills_magical_t4.png" },
  },
  {
    id: "kills_walking_dead_t1",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Walking Dead" },
    threshold: 50,
    tier: 1,
    points: 5,
    initialState: "Revealed",
    type: "incremental",
    steps: 50,
    reveals: [],
    listOrder: 680,
    icon: { play: "play/ach_kills_walking_dead_t1.png", ingame: "ingame/ach_kills_walking_dead_t1.png" },
  },
  {
    id: "kills_walking_dead_t2",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Walking Dead" },
    threshold: 100,
    tier: 2,
    points: 10,
    initialState: "Revealed",
    type: "incremental",
    steps: 100,
    reveals: [],
    listOrder: 690,
    icon: { play: "play/ach_kills_walking_dead_t2.png", ingame: "ingame/ach_kills_walking_dead_t2.png" },
  },
  {
    id: "kills_walking_dead_t3",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Walking Dead" },
    threshold: 200,
    tier: 3,
    points: 15,
    initialState: "Revealed",
    type: "incremental",
    steps: 200,
    reveals: [],
    listOrder: 700,
    icon: { play: "play/ach_kills_walking_dead_t3.png", ingame: "ingame/ach_kills_walking_dead_t3.png" },
  },
  {
    id: "kills_walking_dead_t4",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Walking Dead" },
    threshold: 500,
    tier: 4,
    points: 25,
    initialState: "Revealed",
    type: "incremental",
    steps: 500,
    reveals: [],
    listOrder: 710,
    icon: { play: "play/ach_kills_walking_dead_t4.png", ingame: "ingame/ach_kills_walking_dead_t4.png" },
  },
  {
    id: "frequent_flier_t1",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "deaths", group: null },
    threshold: 50,
    tier: 1,
    points: 5,
    initialState: "Revealed",
    type: "incremental",
    steps: 50,
    reveals: ["death_disease"],
    listOrder: 720,
    icon: { play: "play/ach_frequent_flier_t1.png", ingame: "ingame/ach_frequent_flier_t1.png" },
  },
  {
    id: "frequent_flier_t2",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "deaths", group: null },
    threshold: 100,
    tier: 2,
    points: 10,
    initialState: "Revealed",
    type: "incremental",
    steps: 100,
    reveals: [],
    listOrder: 730,
    icon: { play: "play/ach_frequent_flier_t2.png", ingame: "ingame/ach_frequent_flier_t2.png" },
  },
  {
    id: "frequent_flier_t3",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "deaths", group: null },
    threshold: 200,
    tier: 3,
    points: 15,
    initialState: "Revealed",
    type: "incremental",
    steps: 200,
    reveals: [],
    listOrder: 740,
    icon: { play: "play/ach_frequent_flier_t3.png", ingame: "ingame/ach_frequent_flier_t3.png" },
  },
  {
    id: "frequent_flier_t4",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeCounter", counter: "deaths", group: null },
    threshold: 500,
    tier: 4,
    points: 25,
    initialState: "Revealed",
    type: "incremental",
    steps: 500,
    reveals: [],
    listOrder: 750,
    icon: { play: "play/ach_frequent_flier_t4.png", ingame: "ingame/ach_frequent_flier_t4.png" },
  },
  {
    id: "death_disease",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "lifetimeFlagPair", flags: ["diseaseLeftOnOneHp","poisonLeftOnOneHp"] },
    threshold: null,
    tier: null,
    points: 15,
    initialState: "Hidden",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 760,
    icon: { play: "play/ach_death_disease.png", ingame: "ingame/ach_death_disease.png" },
  },
  {
    id: "special_snowflake",
    name: "",
    description: "",
    line: "",
    trigger: { kind: "deathCause", causes: null, floor: 1 },
    threshold: null,
    tier: null,
    points: 5,
    initialState: "Revealed",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 770,
    icon: { play: "play/ach_special_snowflake.png", ingame: "ingame/ach_special_snowflake.png" },
  },
]);
