// content/achievements.js
//
// The achievement catalog: the single source for the Phase 99 tracker, the
// Phase 100 achievements list, the Phase 101 Play mirror and the Play Console
// import zip (tools/achievements-zip.mjs). Pure data (content-is-pure-data):
// no imports, no function leaves, browser-safe.
//
// 77 entries in list order. Every entry carries the same fourteen fields:
//   id           stable snake_case id; equals the icon file stem without the
//                ach_ prefix and the .png suffix. The track of a tiered entry
//                is its id without the _t<tier> suffix.
//   name         Play name. Unique, printable ASCII, no commas, <= 100 chars.
//                Goes to Play and freezes when the zip is imported.
//   description  Play description. Printable ASCII, no commas, <= 500 chars.
//                Goes to Play and freezes when the zip is imported.
//   line         the in-game unlock line. Never sent to Play, so it can be
//                reworded later.
//   trigger      a declarative rule from TRIGGER_VOCABULARY (below).
//   threshold    the number the measured value must reach, or null when the
//                trigger has no number. A threshold is met when the measured
//                value is AT LEAST the threshold.
//   tier         1..4 on a tiered entry, null otherwise.
//   points       Play points: 5..200 in multiples of 5 (Play caps a game at 2000).
//   initialState "Hidden" or "Revealed" (permanent once the zip is imported).
//   type         "standard" or "incremental" (permanent once the zip is imported).
//   steps        Play steps: equals threshold on an incremental entry, null
//                on a standard one (Play allows 1..10000).
//   reveals      ids this entry reveals when it unlocks (empty array if none).
//   listOrder    10 x position, so a later import can interleave new entries.
//   icon         { play, ingame } paths relative to achievements/, equal to
//                one row of achievements/manifest.json (file_play / file_ingame).
//
// Trigger kinds and their key sets (every key is present, null when unused):
//   lifetimeCounter  { kind, counter, group }  group is a BESTIARY key for kills
//   singleRunBest    { kind, metric, race, parentClass }  race / parentClass are
//                    RACES / CLASSES keys that filter which runs count
//   singleRunFlag    { kind, flag }  a numeric threshold is the floor on which
//                    the flag is judged; null means the moment the flag holds
//   deathCause       { kind, causes, floor }  causes are CAUSE_TEXT keys (null
//                    means any real death); floor is null or the death floor
//   lifetimeFlagPair { kind, flags }  met when both lifetime flags are set
//   distinctSetCount { kind, set }
//
// What each vocabulary word measures (Phase 99 implements it):
//   deaths     real deaths with abandons excluded.
//   kills      every foe that dies in the hero's fights whoever struck it (hero,
//              Joiner or summon) plus Walking Dead destroyed by Turn Undead.
//   joinersAccepted  joinerJoined events.
//   joinersFallen    memberDowned plus joinerMurdered events.
//   parleysWon       parleyWon events.
//   trapsSurvived    each trapSprung that does not end in a trap death.
//   depth      the best floor reached in a run (state.floor.depth).
//   days       state.day.
//   wilmstHeld the most wilmst held at once in a run (spending never counts
//              against it).
//   fleesWon   fled events with reason escaped in one run (door, cloaker,
//              tracked and smoke escapes do not count).
//   fullyDressed     all five equipment slots (weapon not Fists, armour not
//              Nothing, jewelry1, jewelry2, cloak) filled at the same moment.
//   nakedAtFirstStep all five slots empty at the hero's first step and none
//              filled again before the judged floor (bag items and the torch
//              do not count).
//   noHealingPotion  no potionDrunk of a healing potion by the hero in the run
//              (a Joiner's potion and the magic potions do not break it).
//   diseaseLeftOnOneHp / poisonLeftOnOneHp  lifetime flags set when that
//              affliction has once left the hero on exactly 1 HP.
//   subClassesDelved the distinct sub-classes a delve was started with (an
//              abandoned delve still counts as started).
//
// The name, description and line copy is written in plan 98-02; until then
// the three copy fields are empty strings.

export const TRIGGER_VOCABULARY = Object.freeze({
  kinds: Object.freeze(["lifetimeCounter", "singleRunBest", "singleRunFlag", "deathCause", "lifetimeFlagPair", "distinctSetCount"]),
  counters: Object.freeze(["deaths", "kills", "joinersAccepted", "joinersFallen", "parleysWon", "trapsSurvived"]),
  metrics: Object.freeze(["depth", "days", "wilmstHeld", "fleesWon"]),
  runFlags: Object.freeze(["fullyDressed", "nakedAtFirstStep", "noHealingPotion"]),
  lifetimeFlags: Object.freeze(["diseaseLeftOnOneHp", "poisonLeftOnOneHp"]),
  sets: Object.freeze(["subClassesDelved"]),
});

export const ACHIEVEMENTS = Object.freeze([
  {
    id: "depth_t1",
    name: "Downward Mobility I",
    description: "Reach floor 5 in a single run. Most adventurers find the way down. Fewer find it on purpose.",
    line: "Floor 5, by the stairs. There is a quicker way down, and the dungeon would love to show you.",
    trigger: { kind: "singleRunBest", metric: "depth", race: null, parentClass: null },
    threshold: 5,
    tier: 1,
    points: 10,
    initialState: "Revealed",
    type: "incremental",
    steps: 5,
    reveals: ["death_falling"],
    listOrder: 10,
    icon: { play: "play/ach_depth_t1.png", ingame: "ingame/ach_depth_t1.png" },
  },
  {
    id: "depth_t2",
    name: "Downward Mobility II",
    description: "Reach floor 10 in a single run. The sun is now a rumour you heard as a child.",
    line: "Floor 10. Your career is going places, all of them further underground.",
    trigger: { kind: "singleRunBest", metric: "depth", race: null, parentClass: null },
    threshold: 10,
    tier: 2,
    points: 20,
    initialState: "Revealed",
    type: "incremental",
    steps: 10,
    reveals: [],
    listOrder: 20,
    icon: { play: "play/ach_depth_t2.png", ingame: "ingame/ach_depth_t2.png" },
  },
  {
    id: "depth_t3",
    name: "Downward Mobility III",
    description: "Reach floor 15 in a single run. At this depth even the monsters have stopped asking for directions.",
    line: "Floor 15. The Game Master has started taking notes, mostly for the inquest.",
    trigger: { kind: "singleRunBest", metric: "depth", race: null, parentClass: null },
    threshold: 15,
    tier: 3,
    points: 30,
    initialState: "Revealed",
    type: "incremental",
    steps: 15,
    reveals: [],
    listOrder: 30,
    icon: { play: "play/ach_depth_t3.png", ingame: "ingame/ach_depth_t3.png" },
  },
  {
    id: "unicorn",
    name: "Unicorn!",
    description: "Reach floor 20 in a single run. Scholars agree it can be done. Scholars have not tried.",
    line: "Floor 20. The Game Master checked the dice for weights. Twice.",
    trigger: { kind: "singleRunBest", metric: "depth", race: null, parentClass: null },
    threshold: 20,
    tier: null,
    points: 100,
    initialState: "Revealed",
    type: "incremental",
    steps: 20,
    reveals: [],
    listOrder: 40,
    icon: { play: "play/ach_unicorn.png", ingame: "ingame/ach_unicorn.png" },
  },
  {
    id: "death_falling",
    name: "Gravity Wins",
    description: "Die by falling off a wall you were climbing or by coming up short on a leap across a crevice. Gravity was never in doubt.",
    line: "Down is undefeated. Sideways, into solid rock, is still taking challengers.",
    trigger: { kind: "deathCause", causes: ["fall","gorge"], floor: null },
    threshold: null,
    tier: null,
    points: 5,
    initialState: "Hidden",
    type: "standard",
    steps: null,
    reveals: ["ether_entombed"],
    listOrder: 50,
    icon: { play: "play/ach_death_falling.png", ingame: "ingame/ach_death_falling.png" },
  },
  {
    id: "ether_entombed",
    name: "Solid Miscalculation",
    description: "Die inside a wall when your Cloak of Ether wears off mid-stroll. The wall was there first.",
    line: "Timing is everything. Yours was off by roughly one wall.",
    trigger: { kind: "deathCause", causes: ["entombed"], floor: null },
    threshold: null,
    tier: null,
    points: 10,
    initialState: "Hidden",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 60,
    icon: { play: "play/ach_ether_entombed.png", ingame: "ingame/ach_ether_entombed.png" },
  },
  {
    id: "fully_dressed",
    name: "Fully Dressed",
    description: "Fill all five gear slots at the same moment: a weapon (Fists do not count) and armour and a cloak and both jewelry slots. Dressed to be buried in.",
    line: "Every slot filled. Somewhere a braver fool is trying it with nothing at all.",
    trigger: { kind: "singleRunFlag", flag: "fullyDressed" },
    threshold: null,
    tier: null,
    points: 10,
    initialState: "Revealed",
    type: "standard",
    steps: null,
    reveals: ["naked_ambition"],
    listOrder: 70,
    icon: { play: "play/ach_fully_dressed.png", ingame: "ingame/ach_fully_dressed.png" },
  },
  {
    id: "naked_ambition",
    name: "Naked Ambition",
    description: "Take your first step with all five gear slots empty and keep them empty until you reach floor 5: Fists and no armour or cloak or jewelry. Bag items and the torch do not count.",
    line: "Floor 5 in nothing but optimism. The monsters were too embarrassed to look.",
    trigger: { kind: "singleRunFlag", flag: "nakedAtFirstStep" },
    threshold: 5,
    tier: null,
    points: 25,
    initialState: "Hidden",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 80,
    icon: { play: "play/ach_naked_ambition.png", ingame: "ingame/ach_naked_ambition.png" },
  },
  {
    id: "teetotaler",
    name: "Teetotaler",
    description: "Reach floor 5 in a single run without drinking a healing potion yourself. A Joiner drinking theirs and the magic potions do not break it.",
    line: "Floor 5 without a healing swig. Then again, not every bottle down here is the healing kind.",
    trigger: { kind: "singleRunFlag", flag: "noHealingPotion" },
    threshold: 5,
    tier: null,
    points: 15,
    initialState: "Revealed",
    type: "standard",
    steps: null,
    reveals: ["read_the_label"],
    listOrder: 90,
    icon: { play: "play/ach_teetotaler.png", ingame: "ingame/ach_teetotaler.png" },
  },
  {
    id: "read_the_label",
    name: "Read the Label",
    description: "Die by drinking the Death potion from an unlabelled bottle. The label would have helped. The label did not exist.",
    line: "Bold flavour. Strong finish. Very strong finish.",
    trigger: { kind: "deathCause", causes: ["potion"], floor: null },
    threshold: null,
    tier: null,
    points: 5,
    initialState: "Hidden",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 100,
    icon: { play: "play/ach_read_the_label.png", ingame: "ingame/ach_read_the_label.png" },
  },
  {
    id: "race_human",
    name: "Human Error",
    description: "Reach floor 10 with a Human. No bonuses and no penalties and nobody else to blame for how far this went.",
    line: "Floor 10 as a plain Human. The other races stopped pretending to be surprised a few floors back.",
    trigger: { kind: "singleRunBest", metric: "depth", race: "Human", parentClass: null },
    threshold: 10,
    tier: null,
    points: 20,
    initialState: "Revealed",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 110,
    icon: { play: "play/ach_race_human.png", ingame: "ingame/ach_race_human.png" },
  },
  {
    id: "race_elven",
    name: "Elf Preservation",
    description: "Reach floor 10 with an Elf. Thin bones and a deadly aim and very little room for error across ten whole floors.",
    line: "Floor 10 on a little over half a person's HP. Graceful and fragile and now frankly showing off.",
    trigger: { kind: "singleRunBest", metric: "depth", race: "Elven", parentClass: null },
    threshold: 10,
    tier: null,
    points: 20,
    initialState: "Revealed",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 120,
    icon: { play: "play/ach_race_elven.png", ingame: "ingame/ach_race_elven.png" },
  },
  {
    id: "race_dwarven",
    name: "Dwarfing Expectations",
    description: "Reach floor 10 with a Dwarf. Short on height and long on dents and by now mostly dents.",
    line: "Floor 10 as a Dwarf. The ceilings were never the problem. The dents are another matter.",
    trigger: { kind: "singleRunBest", metric: "depth", race: "Dwarven", parentClass: null },
    threshold: 10,
    tier: null,
    points: 20,
    initialState: "Revealed",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 130,
    icon: { play: "play/ach_race_dwarven.png", ingame: "ingame/ach_race_dwarven.png" },
  },
  {
    id: "race_wilmsry",
    name: "Wilmsry Loves Company",
    description: "Reach floor 10 with a Wilmsry. Heals fast and learns slowly and haggles with nearly anything. Somehow it added up.",
    line: "Floor 10 as a Wilmsry. You understood almost none of it and survived all of it twice over.",
    trigger: { kind: "singleRunBest", metric: "depth", race: "Wilmsry", parentClass: null },
    threshold: 10,
    tier: null,
    points: 20,
    initialState: "Revealed",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 140,
    icon: { play: "play/ach_race_wilmsry.png", ingame: "ingame/ach_race_wilmsry.png" },
  },
  {
    id: "race_fridgian",
    name: "Fridge Benefits",
    description: "Reach floor 10 with a Fridgian. No armour and no first strike and a temper that swings twice. Ten floors of temper.",
    line: "Floor 10 as a Fridgian. Thick hide, short fuse, and a very long list of foes who found out.",
    trigger: { kind: "singleRunBest", metric: "depth", race: "Fridgian", parentClass: null },
    threshold: 10,
    tier: null,
    points: 20,
    initialState: "Revealed",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 150,
    icon: { play: "play/ach_race_fridgian.png", ingame: "ingame/ach_race_fridgian.png" },
  },
  {
    id: "race_troll",
    name: "Troll Model",
    description: "Reach floor 10 with a Troll. Large and strong and eating for two and the rations have noticed.",
    line: "Floor 10 as a Troll. The rations did not make it, and neither did anything else edible, but you did.",
    trigger: { kind: "singleRunBest", metric: "depth", race: "Troll", parentClass: null },
    threshold: 10,
    tier: null,
    points: 20,
    initialState: "Revealed",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 160,
    icon: { play: "play/ach_race_troll.png", ingame: "ingame/ach_race_troll.png" },
  },
  {
    id: "class_magic_user",
    name: "Power User",
    description: "Reach floor 10 as a Magic User of any sub-class. A staff for show and a grimoire doing all the actual work. Ten floors of it.",
    line: "Floor 10 on spells and nerve, and still absolutely not on the staff.",
    trigger: { kind: "singleRunBest", metric: "depth", race: null, parentClass: "Magic User" },
    threshold: 10,
    tier: null,
    points: 20,
    initialState: "Revealed",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 170,
    icon: { play: "play/ach_class_magic_user.png", ingame: "ingame/ach_class_magic_user.png" },
  },
  {
    id: "class_fighter",
    name: "Fighting Chance",
    description: "Reach floor 10 as a Fighter of any sub-class. Hit things until the stairs appear and then keep hitting. It is a whole philosophy.",
    line: "Floor 10 by the time-honoured method of hitting everything in the way. Subtlety has yet to be consulted.",
    trigger: { kind: "singleRunBest", metric: "depth", race: null, parentClass: "Fighter" },
    threshold: 10,
    tier: null,
    points: 20,
    initialState: "Revealed",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 180,
    icon: { play: "play/ach_class_fighter.png", ingame: "ingame/ach_class_fighter.png" },
  },
  {
    id: "class_thief",
    name: "Honour Among Thieves",
    description: "Reach floor 10 as a Thief of any sub-class. You took everything not nailed down and two things that were. Floor 10 has noticed.",
    line: "Floor 10 as a Thief. The dungeon is checking its pockets and finding them lighter.",
    trigger: { kind: "singleRunBest", metric: "depth", race: null, parentClass: "Thief" },
    threshold: 10,
    tier: null,
    points: 20,
    initialState: "Revealed",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 190,
    icon: { play: "play/ach_class_thief.png", ingame: "ingame/ach_class_thief.png" },
  },
  {
    id: "tourist",
    name: "Tourist",
    description: "Start a delve with each of the 24 sub-classes. How far each one gets does not matter and an abandoned delve still counts as started. Sightseeing at its most fatal.",
    line: "All 24 sub-classes tried on for size. None of them fit, but you looked lovely in each.",
    trigger: { kind: "distinctSetCount", set: "subClassesDelved" },
    threshold: 24,
    tier: null,
    points: 30,
    initialState: "Revealed",
    type: "incremental",
    steps: 24,
    reveals: [],
    listOrder: 200,
    icon: { play: "play/ach_tourist.png", ingame: "ingame/ach_tourist.png" },
  },
  {
    id: "survivor_t1",
    name: "Survivor I",
    description: "Live 10 days in a single run. Ten sunrises you never saw.",
    line: "Ten days alive. The monsters keep score, and so does your stomach.",
    trigger: { kind: "singleRunBest", metric: "days", race: null, parentClass: null },
    threshold: 10,
    tier: 1,
    points: 5,
    initialState: "Revealed",
    type: "incremental",
    steps: 10,
    reveals: ["death_starvation"],
    listOrder: 210,
    icon: { play: "play/ach_survivor_t1.png", ingame: "ingame/ach_survivor_t1.png" },
  },
  {
    id: "survivor_t2",
    name: "Survivor II",
    description: "Live 25 days in a single run. Long enough to have a favourite corridor.",
    line: "25 days. You have stopped counting the walls and started naming them.",
    trigger: { kind: "singleRunBest", metric: "days", race: null, parentClass: null },
    threshold: 25,
    tier: 2,
    points: 10,
    initialState: "Revealed",
    type: "incremental",
    steps: 25,
    reveals: [],
    listOrder: 220,
    icon: { play: "play/ach_survivor_t2.png", ingame: "ingame/ach_survivor_t2.png" },
  },
  {
    id: "survivor_t3",
    name: "Survivor III",
    description: "Live 50 days in a single run. The dungeon has started forwarding your post.",
    line: "Fifty days. Less an adventurer now and more a tenant.",
    trigger: { kind: "singleRunBest", metric: "days", race: null, parentClass: null },
    threshold: 50,
    tier: 3,
    points: 15,
    initialState: "Revealed",
    type: "incremental",
    steps: 50,
    reveals: [],
    listOrder: 230,
    icon: { play: "play/ach_survivor_t3.png", ingame: "ingame/ach_survivor_t3.png" },
  },
  {
    id: "survivor_t4",
    name: "Survivor IV",
    description: "Live 100 days in a single run. Longer than some kingdoms and every previous version of you.",
    line: "A hundred days. The dungeon has run out of polite ways to ask you to leave.",
    trigger: { kind: "singleRunBest", metric: "days", race: null, parentClass: null },
    threshold: 100,
    tier: 4,
    points: 25,
    initialState: "Revealed",
    type: "incremental",
    steps: 100,
    reveals: [],
    listOrder: 240,
    icon: { play: "play/ach_survivor_t4.png", ingame: "ingame/ach_survivor_t4.png" },
  },
  {
    id: "death_starvation",
    name: "Empty Calories",
    description: "Starve to death. Rations cost almost nothing and weigh even less. You managed it anyway.",
    line: "Surrounded by things that wanted to eat you, and nothing for you to eat. Irony is not filling.",
    trigger: { kind: "deathCause", causes: ["starve"], floor: null },
    threshold: null,
    tier: null,
    points: 5,
    initialState: "Hidden",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 250,
    icon: { play: "play/ach_death_starvation.png", ingame: "ingame/ach_death_starvation.png" },
  },
  {
    id: "hoarder_t1",
    name: "Hoarder I",
    description: "Hold 2000 wilmst at once in a single run. Spending it afterwards never counts against you. Even the starter sack can manage this.",
    line: "2000 wilmst. A small fortune, in a small bag, in a large amount of danger.",
    trigger: { kind: "singleRunBest", metric: "wilmstHeld", race: null, parentClass: null },
    threshold: 2000,
    tier: 1,
    points: 5,
    initialState: "Revealed",
    type: "incremental",
    steps: 2000,
    reveals: [],
    listOrder: 260,
    icon: { play: "play/ach_hoarder_t1.png", ingame: "ingame/ach_hoarder_t1.png" },
  },
  {
    id: "hoarder_t2",
    name: "Hoarder II",
    description: "Hold 5000 wilmst at once in a single run. That takes a Medium bag or bigger. A dragon would call it a start.",
    line: "5000 wilmst. Rich enough to be robbed, poor enough to still be down here.",
    trigger: { kind: "singleRunBest", metric: "wilmstHeld", race: null, parentClass: null },
    threshold: 5000,
    tier: 2,
    points: 10,
    initialState: "Revealed",
    type: "incremental",
    steps: 5000,
    reveals: [],
    listOrder: 270,
    icon: { play: "play/ach_hoarder_t2.png", ingame: "ingame/ach_hoarder_t2.png" },
  },
  {
    id: "hoarder_t3",
    name: "Hoarder III",
    description: "Hold 8000 wilmst at once in a single run. That takes a Large bag or bigger and the posture of a pack mule.",
    line: "8000 wilmst. You jingle when you walk, which the monsters find very convenient.",
    trigger: { kind: "singleRunBest", metric: "wilmstHeld", race: null, parentClass: null },
    threshold: 8000,
    tier: 3,
    points: 15,
    initialState: "Revealed",
    type: "incremental",
    steps: 8000,
    reveals: [],
    listOrder: 280,
    icon: { play: "play/ach_hoarder_t3.png", ingame: "ingame/ach_hoarder_t3.png" },
  },
  {
    id: "hoarder_t4",
    name: "Hoarder IV",
    description: "Hold 10000 wilmst at once in a single run. That takes the Enormous bag and a complete lack of perspective.",
    line: "Ten thousand wilmst, all of it in a hole in the ground. Truly the dream.",
    trigger: { kind: "singleRunBest", metric: "wilmstHeld", race: null, parentClass: null },
    threshold: 10000,
    tier: 4,
    points: 25,
    initialState: "Revealed",
    type: "incremental",
    steps: 10000,
    reveals: [],
    listOrder: 290,
    icon: { play: "play/ach_hoarder_t4.png", ingame: "ingame/ach_hoarder_t4.png" },
  },
  {
    id: "trap_survivor_t1",
    name: "Still Standing I",
    description: "Survive 10 sprung traps across all your runs. Finding them with your feet is still finding them.",
    line: "Ten traps and still standing. The flagstones are patient. They only have to win once.",
    trigger: { kind: "lifetimeCounter", counter: "trapsSurvived", group: null },
    threshold: 10,
    tier: 1,
    points: 5,
    initialState: "Revealed",
    type: "incremental",
    steps: 10,
    reveals: ["death_trap"],
    listOrder: 300,
    icon: { play: "play/ach_trap_survivor_t1.png", ingame: "ingame/ach_trap_survivor_t1.png" },
  },
  {
    id: "trap_survivor_t2",
    name: "Still Standing II",
    description: "Survive 25 sprung traps across all your runs. Your boots have developed opinions.",
    line: "25 traps. You find them the traditional way, every single time.",
    trigger: { kind: "lifetimeCounter", counter: "trapsSurvived", group: null },
    threshold: 25,
    tier: 2,
    points: 10,
    initialState: "Revealed",
    type: "incremental",
    steps: 25,
    reveals: [],
    listOrder: 310,
    icon: { play: "play/ach_trap_survivor_t2.png", ingame: "ingame/ach_trap_survivor_t2.png" },
  },
  {
    id: "trap_survivor_t3",
    name: "Still Standing III",
    description: "Survive 50 sprung traps across all your runs. At this point it is less bad luck and more a method.",
    line: "Fifty traps. The people who build them have filed a complaint about you.",
    trigger: { kind: "lifetimeCounter", counter: "trapsSurvived", group: null },
    threshold: 50,
    tier: 3,
    points: 15,
    initialState: "Revealed",
    type: "incremental",
    steps: 50,
    reveals: [],
    listOrder: 320,
    icon: { play: "play/ach_trap_survivor_t3.png", ingame: "ingame/ach_trap_survivor_t3.png" },
  },
  {
    id: "trap_survivor_t4",
    name: "Still Standing IV",
    description: "Survive 100 sprung traps across all your runs. The traps have learned to recognise your footsteps.",
    line: "A hundred traps survived. Not lucky, exactly. Just a very slow learner with a lot of HP.",
    trigger: { kind: "lifetimeCounter", counter: "trapsSurvived", group: null },
    threshold: 100,
    tier: 4,
    points: 25,
    initialState: "Revealed",
    type: "incremental",
    steps: 100,
    reveals: [],
    listOrder: 330,
    icon: { play: "play/ach_trap_survivor_t4.png", ingame: "ingame/ach_trap_survivor_t4.png" },
  },
  {
    id: "death_trap",
    name: "Fatal Misstep",
    description: "Be killed by a trap. The trap would like to thank you for your cooperation.",
    line: "One wrong step. That was all the dungeon ever asked for.",
    trigger: { kind: "deathCause", causes: ["trap"], floor: null },
    threshold: null,
    tier: null,
    points: 5,
    initialState: "Hidden",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 340,
    icon: { play: "play/ach_death_trap.png", ingame: "ingame/ach_death_trap.png" },
  },
  {
    id: "party_animal_t1",
    name: "Party Animal I",
    description: "Accept 10 Joiners across all your delves. Friends are just HP that can talk.",
    line: "Ten Joiners welcomed aboard. Some of them even saw the next floor.",
    trigger: { kind: "lifetimeCounter", counter: "joinersAccepted", group: null },
    threshold: 10,
    tier: 1,
    points: 5,
    initialState: "Revealed",
    type: "incremental",
    steps: 10,
    reveals: [],
    listOrder: 350,
    icon: { play: "play/ach_party_animal_t1.png", ingame: "ingame/ach_party_animal_t1.png" },
  },
  {
    id: "party_animal_t2",
    name: "Party Animal II",
    description: "Accept 25 Joiners across all your delves. You gather companions the way a candle gathers moths.",
    line: "25 Joiners. Either you are very charming or the last ones did not work out.",
    trigger: { kind: "lifetimeCounter", counter: "joinersAccepted", group: null },
    threshold: 25,
    tier: 2,
    points: 10,
    initialState: "Revealed",
    type: "incremental",
    steps: 25,
    reveals: [],
    listOrder: 360,
    icon: { play: "play/ach_party_animal_t2.png", ingame: "ingame/ach_party_animal_t2.png" },
  },
  {
    id: "party_animal_t3",
    name: "Party Animal III",
    description: "Accept 50 Joiners across all your delves. Word has got around and somehow it has not been a warning.",
    line: "Fifty Joiners. Your recruitment pitch remains, essentially, 'follow me down the hole'.",
    trigger: { kind: "lifetimeCounter", counter: "joinersAccepted", group: null },
    threshold: 50,
    tier: 3,
    points: 15,
    initialState: "Revealed",
    type: "incremental",
    steps: 50,
    reveals: [],
    listOrder: 370,
    icon: { play: "play/ach_party_animal_t3.png", ingame: "ingame/ach_party_animal_t3.png" },
  },
  {
    id: "party_animal_t4",
    name: "Party Animal IV",
    description: "Accept 100 Joiners across all your delves. A small town's worth of company and a smaller town's worth of survivors.",
    line: "A hundred Joiners. You could found a village, if any of them were still around.",
    trigger: { kind: "lifetimeCounter", counter: "joinersAccepted", group: null },
    threshold: 100,
    tier: 4,
    points: 25,
    initialState: "Revealed",
    type: "incremental",
    steps: 100,
    reveals: [],
    listOrder: 380,
    icon: { play: "play/ach_party_animal_t4.png", ingame: "ingame/ach_party_animal_t4.png" },
  },
  {
    id: "human_shields_t1",
    name: "Human Shields I",
    description: "Lose 5 Joiners across all your delves. A Joiner who falls in a fight counts and so does one a Cutthroat murders on the stairs.",
    line: "Five Joiners lost. A natural leader, in the sense that people follow you to the end.",
    trigger: { kind: "lifetimeCounter", counter: "joinersFallen", group: null },
    threshold: 5,
    tier: 1,
    points: 5,
    initialState: "Revealed",
    type: "incremental",
    steps: 5,
    reveals: [],
    listOrder: 390,
    icon: { play: "play/ach_human_shields_t1.png", ingame: "ingame/ach_human_shields_t1.png" },
  },
  {
    id: "human_shields_t2",
    name: "Human Shields II",
    description: "Lose 10 Joiners across all your delves: those who fall in a fight and those a Cutthroat murders on the stairs. Your references are getting thin.",
    line: "Ten fallen Joiners. The recruitment notices now carry a small warning.",
    trigger: { kind: "lifetimeCounter", counter: "joinersFallen", group: null },
    threshold: 10,
    tier: 2,
    points: 10,
    initialState: "Revealed",
    type: "incremental",
    steps: 10,
    reveals: [],
    listOrder: 400,
    icon: { play: "play/ach_human_shields_t2.png", ingame: "ingame/ach_human_shields_t2.png" },
  },
  {
    id: "human_shields_t3",
    name: "Human Shields III",
    description: "Lose 25 Joiners across all your delves whether they fell in a fight or a Cutthroat murdered them on the stairs. Hiring is getting harder.",
    line: "25 Joiners gone. The ones still with you have started walking a little further back.",
    trigger: { kind: "lifetimeCounter", counter: "joinersFallen", group: null },
    threshold: 25,
    tier: 3,
    points: 15,
    initialState: "Revealed",
    type: "incremental",
    steps: 25,
    reveals: [],
    listOrder: 410,
    icon: { play: "play/ach_human_shields_t3.png", ingame: "ingame/ach_human_shields_t3.png" },
  },
  {
    id: "human_shields_t4",
    name: "Human Shields IV",
    description: "Lose 50 Joiners across all your delves. Falling in a fight counts and so does murder by a Cutthroat on the stairs. You are the reason they ask for contracts.",
    line: "Fifty Joiners. History will remember you as a leader. Briefly, and mostly on headstones.",
    trigger: { kind: "lifetimeCounter", counter: "joinersFallen", group: null },
    threshold: 50,
    tier: 4,
    points: 25,
    initialState: "Revealed",
    type: "incremental",
    steps: 50,
    reveals: [],
    listOrder: 420,
    icon: { play: "play/ach_human_shields_t4.png", ingame: "ingame/ach_human_shields_t4.png" },
  },
  {
    id: "parlay_t1",
    name: "Silver Tongue I",
    description: "Win 10 parleys across all your delves. Talking a fight down: the only weapon that never goes blunt.",
    line: "Ten fights talked down. When the words run out, your legs are a fine second opinion.",
    trigger: { kind: "lifetimeCounter", counter: "parleysWon", group: null },
    threshold: 10,
    tier: 1,
    points: 5,
    initialState: "Revealed",
    type: "incremental",
    steps: 10,
    reveals: ["chicken"],
    listOrder: 430,
    icon: { play: "play/ach_parlay_t1.png", ingame: "ingame/ach_parlay_t1.png" },
  },
  {
    id: "parlay_t2",
    name: "Silver Tongue II",
    description: "Win 25 parleys across all your delves. Some foes leave convinced. Most just leave confused.",
    line: "25 parleys won. Diplomacy: still cheaper than armour.",
    trigger: { kind: "lifetimeCounter", counter: "parleysWon", group: null },
    threshold: 25,
    tier: 2,
    points: 10,
    initialState: "Revealed",
    type: "incremental",
    steps: 25,
    reveals: [],
    listOrder: 440,
    icon: { play: "play/ach_parlay_t2.png", ingame: "ingame/ach_parlay_t2.png" },
  },
  {
    id: "parlay_t3",
    name: "Silver Tongue III",
    description: "Win 50 parleys across all your delves. You have argued with things that do not technically have ears.",
    line: "Fifty parleys. Somewhere a monster is telling its friends you made some very good points.",
    trigger: { kind: "lifetimeCounter", counter: "parleysWon", group: null },
    threshold: 50,
    tier: 3,
    points: 15,
    initialState: "Revealed",
    type: "incremental",
    steps: 50,
    reveals: [],
    listOrder: 450,
    icon: { play: "play/ach_parlay_t3.png", ingame: "ingame/ach_parlay_t3.png" },
  },
  {
    id: "parlay_t4",
    name: "Silver Tongue IV",
    description: "Win 100 parleys across all your delves. You could talk a wall into becoming a door.",
    line: "A hundred parleys. You have talked more monsters out of lunch than most heroes have fought.",
    trigger: { kind: "lifetimeCounter", counter: "parleysWon", group: null },
    threshold: 100,
    tier: 4,
    points: 25,
    initialState: "Revealed",
    type: "incremental",
    steps: 100,
    reveals: [],
    listOrder: 460,
    icon: { play: "play/ach_parlay_t4.png", ingame: "ingame/ach_parlay_t4.png" },
  },
  {
    id: "chicken",
    name: "Chicken",
    description: "Win 10 flee rolls in a single run. Only a won flee roll counts. Discretion is the better part of valour and all of the cardio.",
    line: "Ten clean getaways. Your legs have earned this more than you have.",
    trigger: { kind: "singleRunBest", metric: "fleesWon", race: null, parentClass: null },
    threshold: 10,
    tier: null,
    points: 15,
    initialState: "Hidden",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 470,
    icon: { play: "play/ach_chicken.png", ingame: "ingame/ach_chicken.png" },
  },
  {
    id: "kills_beasts_t1",
    name: "Body Count: Beasts I",
    description: "Have 50 Beasts fall in your fights across all your delves. Your Joiners' and summons' kills count too. The rats have started a newsletter.",
    line: "Fifty Beasts down. The wildlife has started travelling in pairs.",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Beasts" },
    threshold: 50,
    tier: 1,
    points: 5,
    initialState: "Revealed",
    type: "incremental",
    steps: 50,
    reveals: [],
    listOrder: 480,
    icon: { play: "play/ach_kills_beasts_t1.png", ingame: "ingame/ach_kills_beasts_t1.png" },
  },
  {
    id: "kills_beasts_t2",
    name: "Body Count: Beasts II",
    description: "Have 100 Beasts fall in your fights across all your delves. It counts whoever lands the last blow: you or a Joiner or a summon. You are now technically an ecosystem.",
    line: "A hundred Beasts. The food chain has a new top, and it is mostly bad decisions.",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Beasts" },
    threshold: 100,
    tier: 2,
    points: 10,
    initialState: "Revealed",
    type: "incremental",
    steps: 100,
    reveals: [],
    listOrder: 490,
    icon: { play: "play/ach_kills_beasts_t2.png", ingame: "ingame/ach_kills_beasts_t2.png" },
  },
  {
    id: "kills_beasts_t3",
    name: "Body Count: Beasts III",
    description: "Have 200 Beasts fall in your fights across all your delves. Joiners and summons may do the honours. The druids have been informed.",
    line: "The bats now flee on rumour alone.",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Beasts" },
    threshold: 200,
    tier: 3,
    points: 15,
    initialState: "Revealed",
    type: "incremental",
    steps: 200,
    reveals: [],
    listOrder: 500,
    icon: { play: "play/ach_kills_beasts_t3.png", ingame: "ingame/ach_kills_beasts_t3.png" },
  },
  {
    id: "kills_beasts_t4",
    name: "Body Count: Beasts IV",
    description: "Have 500 Beasts fall in your fights across all your delves. A Joiner or a summon striking the blow still counts. Extinction was never the plan. It was just the result.",
    line: "Five hundred Beasts. The dungeon has had to restock from the surface.",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Beasts" },
    threshold: 500,
    tier: 4,
    points: 25,
    initialState: "Revealed",
    type: "incremental",
    steps: 500,
    reveals: [],
    listOrder: 510,
    icon: { play: "play/ach_kills_beasts_t4.png", ingame: "ingame/ach_kills_beasts_t4.png" },
  },
  {
    id: "kills_demons_t1",
    name: "Body Count: Demons I",
    description: "Have 50 Demons fall in your fights across all your delves. A Joiner or a summon striking the blow still counts. They say they will be back. They always say that.",
    line: "Fifty Demons. The paperwork below is backed up for weeks.",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Demons" },
    threshold: 50,
    tier: 1,
    points: 5,
    initialState: "Revealed",
    type: "incremental",
    steps: 50,
    reveals: [],
    listOrder: 520,
    icon: { play: "play/ach_kills_demons_t1.png", ingame: "ingame/ach_kills_demons_t1.png" },
  },
  {
    id: "kills_demons_t2",
    name: "Body Count: Demons II",
    description: "Have 100 Demons fall in your fights across all your delves. Your Joiners' and summons' kills count too. The fires below report a staffing shortage.",
    line: "A hundred Demons. They have started describing you to each other in hushed tones.",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Demons" },
    threshold: 100,
    tier: 2,
    points: 10,
    initialState: "Revealed",
    type: "incremental",
    steps: 100,
    reveals: [],
    listOrder: 530,
    icon: { play: "play/ach_kills_demons_t2.png", ingame: "ingame/ach_kills_demons_t2.png" },
  },
  {
    id: "kills_demons_t3",
    name: "Body Count: Demons III",
    description: "Have 200 Demons fall in your fights across all your delves. Joiners and summons may do the honours. Your name is now used to frighten small imps.",
    line: "Something very old and very warm has added you to a list. Two hundred Demons will do that.",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Demons" },
    threshold: 200,
    tier: 3,
    points: 15,
    initialState: "Revealed",
    type: "incremental",
    steps: 200,
    reveals: [],
    listOrder: 540,
    icon: { play: "play/ach_kills_demons_t3.png", ingame: "ingame/ach_kills_demons_t3.png" },
  },
  {
    id: "kills_demons_t4",
    name: "Body Count: Demons IV",
    description: "Have 500 Demons fall in your fights across all your delves. It counts whoever lands the last blow: you or a Joiner or a summon. Below is now accepting complaints about you.",
    line: "Five hundred Demons. The underworld has lodged a formal complaint, in triplicate.",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Demons" },
    threshold: 500,
    tier: 4,
    points: 25,
    initialState: "Revealed",
    type: "incremental",
    steps: 500,
    reveals: [],
    listOrder: 550,
    icon: { play: "play/ach_kills_demons_t4.png", ingame: "ingame/ach_kills_demons_t4.png" },
  },
  {
    id: "kills_humans_t1",
    name: "Body Count: Humans I",
    description: "Have 50 Humans fall in your fights across all your delves. Your Joiners' and summons' kills count too. They came down here for the same reasons you did.",
    line: "Fifty Humans. In fairness, every one of them swung first. Probably.",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Humans" },
    threshold: 50,
    tier: 1,
    points: 5,
    initialState: "Revealed",
    type: "incremental",
    steps: 50,
    reveals: [],
    listOrder: 560,
    icon: { play: "play/ach_kills_humans_t1.png", ingame: "ingame/ach_kills_humans_t1.png" },
  },
  {
    id: "kills_humans_t2",
    name: "Body Count: Humans II",
    description: "Have 100 Humans fall in your fights across all your delves. It counts whoever lands the last blow: you or a Joiner or a summon. The surface has noticed a dip in adventurers.",
    line: "A hundred Humans. Every tavern on the surface has a poster with your face on it.",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Humans" },
    threshold: 100,
    tier: 2,
    points: 10,
    initialState: "Revealed",
    type: "incremental",
    steps: 100,
    reveals: [],
    listOrder: 570,
    icon: { play: "play/ach_kills_humans_t2.png", ingame: "ingame/ach_kills_humans_t2.png" },
  },
  {
    id: "kills_humans_t3",
    name: "Body Count: Humans III",
    description: "Have 200 Humans fall in your fights across all your delves. Joiners and summons may do the honours. Bandit recruitment is at an all-time low.",
    line: "You are now the scary story other delvers tell at camp.",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Humans" },
    threshold: 200,
    tier: 3,
    points: 15,
    initialState: "Revealed",
    type: "incremental",
    steps: 200,
    reveals: [],
    listOrder: 580,
    icon: { play: "play/ach_kills_humans_t3.png", ingame: "ingame/ach_kills_humans_t3.png" },
  },
  {
    id: "kills_humans_t4",
    name: "Body Count: Humans IV",
    description: "Have 500 Humans fall in your fights across all your delves. A Joiner or a summon striking the blow still counts. The surface is running out of people who fancy their chances.",
    line: "Five hundred Humans. Some of them had names. The dungeon kept a list.",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Humans" },
    threshold: 500,
    tier: 4,
    points: 25,
    initialState: "Revealed",
    type: "incremental",
    steps: 500,
    reveals: [],
    listOrder: 590,
    icon: { play: "play/ach_kills_humans_t4.png", ingame: "ingame/ach_kills_humans_t4.png" },
  },
  {
    id: "kills_lair_beasts_t1",
    name: "Body Count: Lair Beasts I",
    description: "Have 50 Lair Beasts fall in your fights across all your delves. A Joiner or a summon striking the blow still counts. They were at home. You were the visitor.",
    line: "Fifty Lair Beasts evicted. The goblin housing market is in freefall.",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Lair Beasts" },
    threshold: 50,
    tier: 1,
    points: 5,
    initialState: "Revealed",
    type: "incremental",
    steps: 50,
    reveals: [],
    listOrder: 600,
    icon: { play: "play/ach_kills_lair_beasts_t1.png", ingame: "ingame/ach_kills_lair_beasts_t1.png" },
  },
  {
    id: "kills_lair_beasts_t2",
    name: "Body Count: Lair Beasts II",
    description: "Have 100 Lair Beasts fall in your fights across all your delves. Your Joiners' and summons' kills count too. Every lair you visit gets a little roomier.",
    line: "A hundred Lair Beasts. Property values down here have never been better.",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Lair Beasts" },
    threshold: 100,
    tier: 2,
    points: 10,
    initialState: "Revealed",
    type: "incremental",
    steps: 100,
    reveals: [],
    listOrder: 610,
    icon: { play: "play/ach_kills_lair_beasts_t2.png", ingame: "ingame/ach_kills_lair_beasts_t2.png" },
  },
  {
    id: "kills_lair_beasts_t3",
    name: "Body Count: Lair Beasts III",
    description: "Have 200 Lair Beasts fall in your fights across all your delves. It counts whoever lands the last blow: you or a Joiner or a summon. Goblin parents use your name at bedtime.",
    line: "Word has reached the lairs. They have started locking their doors.",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Lair Beasts" },
    threshold: 200,
    tier: 3,
    points: 15,
    initialState: "Revealed",
    type: "incremental",
    steps: 200,
    reveals: [],
    listOrder: 620,
    icon: { play: "play/ach_kills_lair_beasts_t3.png", ingame: "ingame/ach_kills_lair_beasts_t3.png" },
  },
  {
    id: "kills_lair_beasts_t4",
    name: "Body Count: Lair Beasts IV",
    description: "Have 500 Lair Beasts fall in your fights across all your delves. Joiners and summons may do the honours. Not one lair on the map is still taking visitors.",
    line: "Five hundred Lair Beasts. You are the monster under their beds.",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Lair Beasts" },
    threshold: 500,
    tier: 4,
    points: 25,
    initialState: "Revealed",
    type: "incremental",
    steps: 500,
    reveals: [],
    listOrder: 630,
    icon: { play: "play/ach_kills_lair_beasts_t4.png", ingame: "ingame/ach_kills_lair_beasts_t4.png" },
  },
  {
    id: "kills_magical_t1",
    name: "Body Count: Magical I",
    description: "Have 50 Magical foes fall in your fights across all your delves. Your Joiners' and summons' kills count too. Magic is real and it is also beatable.",
    line: "Fifty Magical foes. It turns out wonder has HP.",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Magical" },
    threshold: 50,
    tier: 1,
    points: 5,
    initialState: "Revealed",
    type: "incremental",
    steps: 50,
    reveals: [],
    listOrder: 640,
    icon: { play: "play/ach_kills_magical_t1.png", ingame: "ingame/ach_kills_magical_t1.png" },
  },
  {
    id: "kills_magical_t2",
    name: "Body Count: Magical II",
    description: "Have 100 Magical foes fall in your fights across all your delves. A Joiner or a summon striking the blow still counts. The arcane is far less mysterious lying down.",
    line: "The shadows keep their distance now, which is very on brand for shadows.",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Magical" },
    threshold: 100,
    tier: 2,
    points: 10,
    initialState: "Revealed",
    type: "incremental",
    steps: 100,
    reveals: [],
    listOrder: 650,
    icon: { play: "play/ach_kills_magical_t2.png", ingame: "ingame/ach_kills_magical_t2.png" },
  },
  {
    id: "kills_magical_t3",
    name: "Body Count: Magical III",
    description: "Have 200 Magical foes fall in your fights across all your delves. Joiners and summons may do the honours. Mystery is overrated anyway.",
    line: "Two hundred Magical foes. Enchantment is down. Disenchantment is up.",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Magical" },
    threshold: 200,
    tier: 3,
    points: 15,
    initialState: "Revealed",
    type: "incremental",
    steps: 200,
    reveals: [],
    listOrder: 660,
    icon: { play: "play/ach_kills_magical_t3.png", ingame: "ingame/ach_kills_magical_t3.png" },
  },
  {
    id: "kills_magical_t4",
    name: "Body Count: Magical IV",
    description: "Have 500 Magical foes fall in your fights across all your delves. It counts whoever lands the last blow: you or a Joiner or a summon. The world is measurably less magical and it is your doing.",
    line: "Five hundred Magical foes. Wizards now cross the corridor when they see you coming.",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Magical" },
    threshold: 500,
    tier: 4,
    points: 25,
    initialState: "Revealed",
    type: "incremental",
    steps: 500,
    reveals: [],
    listOrder: 670,
    icon: { play: "play/ach_kills_magical_t4.png", ingame: "ingame/ach_kills_magical_t4.png" },
  },
  {
    id: "kills_walking_dead_t1",
    name: "Body Count: Walking Dead I",
    description: "Have 50 Walking Dead fall in your fights across all your delves. Your Joiners' and summons' kills count and so do Walking Dead destroyed by Turn Undead. They were dead already. You were just thorough.",
    line: "Fifty Walking Dead put back to bed. Sleep tight. Properly, this time.",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Walking Dead" },
    threshold: 50,
    tier: 1,
    points: 5,
    initialState: "Revealed",
    type: "incremental",
    steps: 50,
    reveals: [],
    listOrder: 680,
    icon: { play: "play/ach_kills_walking_dead_t1.png", ingame: "ingame/ach_kills_walking_dead_t1.png" },
  },
  {
    id: "kills_walking_dead_t2",
    name: "Body Count: Walking Dead II",
    description: "Have 100 Walking Dead fall in your fights across all your delves. Kills by Joiners and summons and Walking Dead destroyed by Turn Undead all count. A second death is still a death.",
    line: "A hundred Walking Dead. The graveyard would like a word about overtime.",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Walking Dead" },
    threshold: 100,
    tier: 2,
    points: 10,
    initialState: "Revealed",
    type: "incremental",
    steps: 100,
    reveals: [],
    listOrder: 690,
    icon: { play: "play/ach_kills_walking_dead_t2.png", ingame: "ingame/ach_kills_walking_dead_t2.png" },
  },
  {
    id: "kills_walking_dead_t3",
    name: "Body Count: Walking Dead III",
    description: "Have 200 Walking Dead fall in your fights across all your delves. Turn Undead counts and so do kills by your Joiners and summons. The crypts are finally quiet.",
    line: "The skeletons are staying in the closet, and you are the reason.",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Walking Dead" },
    threshold: 200,
    tier: 3,
    points: 15,
    initialState: "Revealed",
    type: "incremental",
    steps: 200,
    reveals: [],
    listOrder: 700,
    icon: { play: "play/ach_kills_walking_dead_t3.png", ingame: "ingame/ach_kills_walking_dead_t3.png" },
  },
  {
    id: "kills_walking_dead_t4",
    name: "Body Count: Walking Dead IV",
    description: "Have 500 Walking Dead fall in your fights across all your delves. Turn Undead counts and so does a Joiner or a summon striking the blow. Rest in peace was only ever a suggestion until you.",
    line: "Five hundred Walking Dead, each one returned to sender.",
    trigger: { kind: "lifetimeCounter", counter: "kills", group: "Walking Dead" },
    threshold: 500,
    tier: 4,
    points: 25,
    initialState: "Revealed",
    type: "incremental",
    steps: 500,
    reveals: [],
    listOrder: 710,
    icon: { play: "play/ach_kills_walking_dead_t4.png", ingame: "ingame/ach_kills_walking_dead_t4.png" },
  },
  {
    id: "frequent_flier_t1",
    name: "Frequent Flier I",
    description: "Die 50 times across all your runs. Abandoning a character does not count: the dungeon wants the real thing.",
    line: "Fifty deaths and all of them brisk. Some ailments down here prefer to take it slow.",
    trigger: { kind: "lifetimeCounter", counter: "deaths", group: null },
    threshold: 50,
    tier: 1,
    points: 5,
    initialState: "Revealed",
    type: "incremental",
    steps: 50,
    reveals: ["death_disease"],
    listOrder: 720,
    icon: { play: "play/ach_frequent_flier_t1.png", ingame: "ingame/ach_frequent_flier_t1.png" },
  },
  {
    id: "frequent_flier_t2",
    name: "Frequent Flier II",
    description: "Die 100 times across all your runs. Abandoned characters do not count. The graveyard has started a second row.",
    line: "A hundred deaths. The Game Master has stopped writing your name and bought a stamp.",
    trigger: { kind: "lifetimeCounter", counter: "deaths", group: null },
    threshold: 100,
    tier: 2,
    points: 10,
    initialState: "Revealed",
    type: "incremental",
    steps: 100,
    reveals: [],
    listOrder: 730,
    icon: { play: "play/ach_frequent_flier_t2.png", ingame: "ingame/ach_frequent_flier_t2.png" },
  },
  {
    id: "frequent_flier_t3",
    name: "Frequent Flier III",
    description: "Die 200 times across all your runs. Abandoned characters never count. The gravedigger knows your order by heart.",
    line: "Two hundred deaths. You have spent more time in the graveyard than in daylight.",
    trigger: { kind: "lifetimeCounter", counter: "deaths", group: null },
    threshold: 200,
    tier: 3,
    points: 15,
    initialState: "Revealed",
    type: "incremental",
    steps: 200,
    reveals: [],
    listOrder: 740,
    icon: { play: "play/ach_frequent_flier_t3.png", ingame: "ingame/ach_frequent_flier_t3.png" },
  },
  {
    id: "frequent_flier_t4",
    name: "Frequent Flier IV",
    description: "Die 500 times across all your runs with abandoned characters not counted. Commitment or stubbornness: the ledger cannot tell.",
    line: "Five hundred deaths. At this point the afterlife issues you a loyalty card.",
    trigger: { kind: "lifetimeCounter", counter: "deaths", group: null },
    threshold: 500,
    tier: 4,
    points: 25,
    initialState: "Revealed",
    type: "incremental",
    steps: 500,
    reveals: [],
    listOrder: 750,
    icon: { play: "play/ach_frequent_flier_t4.png", ingame: "ingame/ach_frequent_flier_t4.png" },
  },
  {
    id: "death_disease",
    name: "Terminal Condition",
    description: "Have Disease leave you on exactly 1 HP and have Poison leave you on exactly 1 HP. Once each in any of your runs. Not fatal. Just thorough.",
    line: "Disease and Poison both walked you to the edge and stopped. Professional courtesy.",
    trigger: { kind: "lifetimeFlagPair", flags: ["diseaseLeftOnOneHp","poisonLeftOnOneHp"] },
    threshold: null,
    tier: null,
    points: 15,
    initialState: "Hidden",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 760,
    icon: { play: "play/ach_death_disease.png", ingame: "ingame/ach_death_disease.png" },
  },
  {
    id: "special_snowflake",
    name: "Special Snowflake",
    description: "Die on floor 1. Abandoning a character there does not count: it has to be a real death. Most adventurers at least see the stairs.",
    line: "You're a special snowflake.",
    trigger: { kind: "deathCause", causes: null, floor: 1 },
    threshold: null,
    tier: null,
    points: 5,
    initialState: "Revealed",
    type: "standard",
    steps: null,
    reveals: [],
    listOrder: 770,
    icon: { play: "play/ach_special_snowflake.png", ingame: "ingame/ach_special_snowflake.png" },
  },
]);
