// src/browser/patchNotesData.js
//
// GENERATED by `node tools/patch-notes.mjs --write-module` — do not hand-edit.
// Phase 79.3, NOTES-01, D-19: bundled by tools/build-www.mjs#bundlePatchNotes
// from docs/patch-notes/<versionName>.md, so the dev loop and the shipped app
// read the exact same release notes. A test pins this file to the Markdown.
export const PATCH_NOTES = Object.freeze({ version: "2.1.0", markdown: "# Delve, Die, Repeat 2.1.0\n\n## Headline\nVersion 2.1.0. The full notes land before this build goes out; these are the first lines.\n- The ☰ menu gains PATCH NOTES and REPORT A BUG.\n\n## Interface\n- ☰ menu: nowhere to read what changed → a PATCH NOTES row shows this version's notes, even offline, and opens once by itself after an update.\n- ☰ menu: nowhere to report a bug → a REPORT A BUG row sends what you type and this run's Oracle to the developer, posted publicly on GitHub.\n" });
