// src/browser/patchNotesData.js
//
// GENERATED by `node tools/patch-notes.mjs --write-module` — do not hand-edit.
// Phase 79.3, NOTES-01, D-19: bundled by tools/build-www.mjs#bundlePatchNotes
// from docs/patch-notes/<versionName>.md, so the dev loop and the shipped app
// read the exact same release notes. A test pins this file to the Markdown.
export const PATCH_NOTES = Object.freeze({ version: "2.5.0", markdown: "# Delve, Die, Repeat 2.5.0\n\n## Headline\nAchievements are here: 77 of them to earn, and with Compete on they also unlock in Google Play Games for XP.\n\n## Interface\n- Earning an achievement puts a card on the rail, and anything your death earned shows on the death screen.\n- ☰ ACHIEVEMENTS lists every one with your progress, and a few stay secret until you stumble into them.\n- With Compete on and signed in, VIEW IN PLAY GAMES at the top of that list opens Play's own achievements screen.\n- With Compete on, your achievement progress is sent to Play Games, including anything you earned while it was off.\n" });
