// test/unit/roll-high-state-pins.test.js
//
// Phase 73 (ROLL-05, Plan 02): a bot-sweep state-hash pin, generated on the
// UNTOUCHED engine at the Phase 73 base — commit bef94aa (git rev-parse
// --short HEAD). See CONTEXT Area 3 ("Proof it changed nothing"): the parity
// fixtures only reach solo level-1 Beasts and Humans, so they cannot see a
// mis-flipped Skeleton, member, climb or trap. These eight runs (four solo,
// two party, two deep starts near depth 8/14) reach far wider ground.
//
// The switch (this phase, later plans) must change REPRESENTATION only —
// every check's threshold/roll direction mirrors, but which side WINS never
// changes. A moved hash here means a check site was flipped wrong: FIX THE
// SITE, never re-pin. Regenerate with `node tools/roll-high-baseline.mjs
// pins` only if a plan deliberately changes outcomes and declares why (it
// should not — see 73-CONTEXT.md's "byte-identical outcomes" requirement).

import test from "node:test";
import assert from "node:assert/strict";
import { PIN_RUNS, pinRun } from "./harness/rollHighBaseline.js";

// Generated by `node tools/roll-high-baseline.mjs pins` at commit bef94aa,
// each entry hashed identically across two independent runs before pinning.
const PINNED = {
  // "solo-1", "solo-2", "party-1" and "deep-8" re-pinned (Phase 75, Plan 05,
  // 2026-09-25): RULES-03's grant-time legality filter (engine/character.js
  // #grantableAt, used by rollGrimoire's low/high walks and checkLevel)
  // changes WHICH spells a gated Magic User sub-class (Warlock, Sorcerer,
  // Court Mage, Illusionist, Cleric, Apprentice) lands with at chargen — a
  // previously-granted-but-uncastable spell (e.g. a Court Mage's divination
  // spell, gated at 4) is skipped while walking the already-shuffled list,
  // so a DIFFERENT, immediately-castable spell fills that book slot instead.
  // Verified: newRun(seed).c.sub for every one of these four labels is a
  // gated Magic User sub-class (solo-1/party-1: Court Mage; solo-2:
  // Apprentice; deep-8: Court Mage) — the ONE declared change this plan
  // makes to chargen content — while "solo-thief-pilfer",
  // "solo-magicuser-sorcerer" (forced Sorcerer, whose seed's book happens to
  // draw no now-illegal spell) and "party-fighter-knight" (non-caster) stay
  // byte-identical, and "deep-14" (a Thief, unaffected by any Magic User
  // change) stays byte-identical too. Regenerated via
  // `node tools/roll-high-baseline.mjs pins` (each hashed identically twice).
  //
  // "solo-thief-pilfer" re-pinned again (Phase 75, Plan 12, 2026-09-25):
  // RULES-12's `resolvePendingTile` (a tile a wandering-monster check
  // interrupted mid-step now resolves once the fight settles, instead of
  // being silently dropped forever) changes a bot-visible OUTCOME for this
  // one Thief run — a resumed tile's feature firing where it previously
  // never did shifts the run's depth (5 -> 4) within 400 actions. Every
  // OTHER label re-measured byte-identical (RULES-15's fed-only book
  // refill never actually fires within any of these seeds' 400/300/93-
  // action budgets, and RULES-12 never fires for the other seven either) —
  // confirmed by re-running `node tools/roll-high-baseline.mjs pins` after
  // adding `pendingTile` to `EXTRA_VOLATILE_FIELDS`
  // (test/unit/harness/rollHighBaseline.js) so the field's mere PRESENCE
  // (vs. absence on a state that never set it) never itself moves a hash —
  // see that file's own doc comment for the "pure JSON-representation
  // noise" precedent (`pendingJoiner`). Regenerated via `node
  // tools/roll-high-baseline.mjs pins` (each hashed identically twice).
  //
  // "solo-thief-pilfer" re-pinned AGAIN (Phase 75.1, Plan 01, 2026-09-25):
  // RULES-09 removes the IDENT-07 heal-only refusal — a Pilfer's non-heal
  // magic-item use, which used to be a silent `useRefused {reason:"pilfer"}`
  // no-op burning ZERO rng draws, now actually resolves (a real use, or a
  // fumble), consuming real draws from the main rng cursor from that point
  // on. Bisected live: this forced Pilfer's first such use is an Amulet of
  // Light (`itemUsed`, kind "glow") at action 333 of 400 — exactly the
  // "newly allowed use" this plan's own interfaces block anticipated. The
  // outcome shape is unchanged (400 actions, not dead, depth 4) — only the
  // downstream rng-consumed state differs. Confirmed by reverting ONLY
  // tuning-bot.mjs's round-1-buff Pilfer skip in an isolated scratch copy
  // and re-measuring: the hash did NOT change (chooseCombatItem's own
  // "buff" branch never actually fires for this seed/force — no potion or
  // worn buff item is in this run's starting kit), ruling out Plan 01's
  // bot-tactics.mjs edit as the cause and isolating it to the engine's own
  // useItem change. Every OTHER label re-measured byte-identical (no other
  // pin ever exercises a Pilfer's non-heal item use within its own action
  // budget). Regenerated via `node tools/roll-high-baseline.mjs pins`
  // (each hashed identically twice).
  //
  // "solo-thief-pilfer" re-pinned YET AGAIN (Phase 75.1, Plan 06,
  // 2026-09-26) — see the "deep-14" comment block below for the full
  // RULES-10 rationale (the bot now reads a scroll for every class); this
  // Pilfer's own first scroll read lands at bot step 138 (`reader:
  // "intel"`), the outcome shape unchanged (400 actions, not dead, depth 4).
  //
  // "solo-2" and "party-fighter-knight" re-pinned (Phase 75.2, Plan 01,
  // 2026-09-26, RULES-11): size is now a real stat — a Dwarven character's
  // own face axis (unmasked; only the Dwarven damage axis is protected by
  // the signature rule) shaves one winning face off every foe trying to
  // land a blow on that body. "solo-2" is a forced-nothing chargen roll
  // whose seed lands a Dwarven Apprentice (verified: `newRun(202).c.race
  // === "Dwarven"`); its hero's own first foe swing carrying a `{name:
  // "size", delta: -1}` mod fires at bot action 9 (bisected live via
  // playRun's own onStep hook, scanning for the first event whose `mods`
  // include a "size" entry) — the depth shifts (4 -> 5) from there.
  // "party-fighter-knight" forces a Human Fighter/Knight hero, but its
  // seed's own Joiner (recruited by forceParty's real meetJoiner/
  // resolveJoiner draw) is Dwarven ("Hilda Stonecut", verified live); the
  // FIRST size-mod event is a `foeMissed` against THAT member at bot action
  // 100 (engine/combat.js#foeTurn's member branch, this plan's own new
  // term) — the hero's own race is unaffected (Human, size step 0), so this
  // is exactly the Joiner symmetry rule ("a Joiner gets size too... by the
  // same rule") reaching a real playthrough, not a hero-side change. Every
  // OTHER label re-measured byte-identical twice (no other pin's hero or
  // party carries a Dwarven/Elven/Troll within its own action budget —
  // solo-1/solo-thief-pilfer/solo-magicuser-sorcerer/party-1/deep-8/deep-14
  // are all Human/Wilmsry/Fridgian heroes with no sized party member).
  // Regenerated via `node tools/roll-high-baseline.mjs pins` (each hashed
  // identically twice).
  // "solo-1", "solo-2", "solo-thief-pilfer", "solo-magicuser-sorcerer" and
  // "party-1" re-pinned (Phase 78, Plan 01, 2026-09-26, CLIMB-01): every
  // step toward a wall or crevice now pauses on the pre-roll decision (a
  // `hazardChoice`, no dice) and the bot commits on its next action
  // (tools/lib/tuning-bot.mjs#decideAction), so each crossing WITHOUT the
  // tool costs one extra validated action inside the fixed 400-action
  // budget. Bisected live (a scratch trace of every step's full state hash,
  // `acts`/`pendingHazard` aside, against a plan-base copy of the engine,
  // with the pause steps dropped): solo-1 (4 uncarried pauses), solo-2 (3),
  // solo-magicuser-sorcerer (7) and party-1 (5) play the SAME game step for
  // step and simply stop that many game actions earlier. solo-thief-pilfer
  // (3 pauses) matches up to bot step 137, its first scroll read after a
  // crossing: the acts-keyed `scrollRead` derived stream (engine/magic.js)
  // sees an `acts` one higher per earlier pause, so the read that
  // deciphered now fumbles. `actions`/`dead`/`depth` are unchanged for all
  // five; party-fighter-knight, deep-8 and deep-14 cross no wall or crevice
  // within their budgets and re-measured byte-identical. Regenerated via
  // `node tools/roll-high-baseline.mjs pins` (hashed identically three
  // times).
  //
  // "solo-1", "solo-2", "solo-thief-pilfer", "solo-magicuser-sorcerer",
  // "party-1", "party-fighter-knight" and "deep-8" re-pinned (Phase 79,
  // quick fix 79-02c, 2026-09-27): per-floor heal removed (user ruling
  // 2026-09-27, "We shouldn't heal at all when we go down a floor"). A
  // DECLARED outcome change. Traced live (base 08969929 vs the fix, a
  // scratch trace of every bot step's full state hash through playRun's
  // onStep hook): each label's FIRST divergence is exactly its first
  // descent that used to push `floorRegen`, and the two runs agree on every
  // earlier step. solo-1 step 205 (base +18 hp, 72/72 vs now 54/72), solo-2
  // step 103 (+9), solo-thief-pilfer step 74 (+4), solo-magicuser-sorcerer
  // step 85 (+4), party-1 step 147 (+7), party-fighter-knight step 318
  // (+17), deep-8 step 77 (+15). The regen drew no rng, so the draw stream
  // is the same; only hp, and the bot's later choices from it, move.
  // actions/dead/depth are unchanged except deep-8 (250 -> 262 actions,
  // still dead on floor 10). "deep-14" re-measured byte-identical (it dies
  // on floor 14 before any descent). Regenerated via
  // `node tools/roll-high-baseline.mjs pins` (hashed identically twice).
  //
  // "solo-1", "solo-2" and "solo-magicuser-sorcerer" re-pinned (quick
  // 260927-rsx, user ruling 2026-09-27: every spell cast on a foe can be
  // resisted, half its intel in faces on a d20, from a derived stream).
  // Traced against extracted trees (git archive 4407e350, the base, and
  // e1f9dc0c, the resist rule alone) with a per-step state-hash trace: the
  // first divergence is the hero's own Freeze resisted by its target —
  // solo-1 bot step 111 (Dante, 6 faces, rolled 20), solo-2 step 10
  // (Philly, 2 faces, rolled 19), solo-magicuser-sorcerer step 100 (Drekk,
  // 2 faces, rolled 19) — every earlier step byte-identical. Quick
  // 260927-opf (once-per-fight strikes) moves none of the three. solo-1
  // stays 400 / alive / floor 5; solo-2 floor 5 -> 4; the Sorcerer floor
  // 4 -> 3. Regenerated via `node tools/roll-high-baseline.mjs pins`
  // (each hashed identically twice).
  // User rulings 2026-09-28 (plan 79.2-01, "freeze should never kill
  // outright. It should deal its damage and freeze an enemy for 1d4 rounds";
  // "if it hits and resists, deal damage, but no freeze"): "solo-1",
  // "solo-2", "solo-magicuser-sorcerer", "party-1" and "deep-8" re-pinned.
  // Traced against an extracted tree (git archive 992b1dfa, the base) with a
  // per-bot-step state-hash trace: each label's first divergence is a
  // Freeze — solo-1 bot step 103 (the hero's Freeze on a China Wolf, 6
  // damage: it was frozen solid and killed, now frozen for its d4 of 3),
  // solo-2 step 9 (the hero's Freeze on Philly, 2 damage, now frozen 3),
  // solo-magicuser-sorcerer step 100 (the hero's Freeze on Drekk: resisted
  // before the throw, now the 1 damage lands and the resist stops only the
  // freeze), party-1 step 186 (the Joiner Aldric Corrin's Freeze on a
  // Gremlin: 6 damage, then resisted, where it was frozen solid and killed)
  // and deep-8 step 10 (the hero's Freeze on a Poltergeist, 8 damage, now
  // frozen 2) — every earlier step byte-identical. solo-1 400/alive, floor
  // 5 -> 4; solo-2 400/alive/4 -> 298/dead/3; the Sorcerer floor 3 -> 4;
  // party-1 floor 4 -> 3; deep-8 262/dead/10 -> 117/dead/9. Every other
  // label re-measured byte-identical. Regenerated via
  // `node tools/roll-high-baseline.mjs pins` (each hashed identically twice).
  // Quick 260928-sq2 (user ruling 2026-09-28, "square spell damage just like
  // we do with weapons damage"): a spell's damage is its dice + the caster's
  // level², replacing x max(1, level - spell level). "solo-1", "solo-2",
  // "party-1" and "deep-8" re-pinned. Traced against an extracted tree (git
  // archive d98639e9, the base) with a per-bot-step state-hash trace: each
  // first divergence is a Freeze hit's damage — solo-1 bot step 103 (the
  // hero's Freeze on a China Wolf, 6 -> 7), solo-2 step 9 (the hero's Freeze
  // on Philly, 2 -> 4 applied), party-1 step 186 (the Joiner Aldric
  // Corrin's Freeze on a Gremlin, 6 -> 7: now a kill, where it was resisted
  // and stood) and deep-8 step 10 (the level-5 hero's Freeze on a
  // Poltergeist, 2 x 4 = 8 -> 2 + 25 = 27: now a kill, where it was frozen
  // 2) — every earlier step byte-identical. solo-1 400/alive, floor 4 -> 5;
  // solo-2 298/dead/3 -> 400/alive/4; party-1 400/alive/3 -> 375/dead/3;
  // deep-8 117/dead/9 -> 262/dead/10. solo-thief-pilfer,
  // solo-magicuser-sorcerer, party-fighter-knight and deep-14 re-measured
  // byte-identical. Regenerated via `node tools/roll-high-baseline.mjs pins`
  // (each hashed identically twice).
  // Phase 79.2 early-floor lock (user ruling 2026-09-27, locked by
  // RF-79.2-02-3): every one of the eight labels re-pinned. The lock moved
  // HERO_HP_SCALE 1.25 -> 1.4, HERO_SP_SCALE 0.28 -> 0.23, FOE_HP_SCALE.base
  // 0.9 -> 1.2, FOE_HIT_SCALE { 0.6, 0.01 } -> { 0.84, 0.02 } and
  // FOE_LEVEL.base 0.9 -> 1.0. Traced with a scratch per-bot-step trace
  // (playRun's onStep, stateHash of every step) run twice on the locked
  // engine: once under setDialsForTuning(79.2's fit/start.json), which
  // reproduced every old pin below byte for byte, and once under the locked
  // DIALS. Every label's first differing state is bot step 1, and the only
  // differing fields there are c.maxWP/c.wp: chargen's heroMaxWpFor reads
  // HERO_HP_SCALE (solo-1 36 -> 41, solo-2 36 -> 41, solo-thief-pilfer
  // 50 -> 56, solo-magicuser-sorcerer 38 -> 42, party-1 43 -> 48,
  // party-fighter-knight 68 -> 76, deep-8 63 -> 70, deep-14 80 -> 89). The
  // first differing EVENT is: solo-1 step 13 (a Shriek's wp 3 -> 4,
  // FOE_HP_SCALE), solo-2 step 7 (Philly 5 -> 6, FOE_HP_SCALE),
  // solo-thief-pilfer step 44 (Ned 7 -> 10, FOE_HP_SCALE),
  // solo-magicuser-sorcerer step 86 (the descend spGained 20 -> 16,
  // HERO_SP_SCALE), party-1 step 97 (a Bat/Rat kill's spGained 4 -> 3,
  // HERO_SP_SCALE), party-fighter-knight step 98 (three Neds 7 -> 10,
  // FOE_HP_SCALE), deep-8 step 9 (Poltergeist 10 -> 13 and Rinkle 16 -> 21,
  // FOE_HP_SCALE) and deep-14 step 9 (Table 4's -10 HP row, dotHpFor 13 ->
  // 14, HERO_HP_SCALE). Old -> new (actions / dead / depth): solo-1
  // 400/false/5 -> 253/true/3; solo-2 400/false/4 -> 294/true/3;
  // solo-thief-pilfer 400/false/4 (unchanged); solo-magicuser-sorcerer
  // 400/false/4 -> 400/false/5; party-1 375/true/3 -> 373/true/3;
  // party-fighter-knight 400/false/4 -> 200/true/2; deep-8 262/true/10 ->
  // 225/true/10; deep-14 154/true/15 -> 50/true/14. Regenerated via
  // `node tools/roll-high-baseline.mjs pins` (each hashed identically twice).
  // "solo-1", "solo-2", "solo-magicuser-sorcerer" and "deep-8" re-pinned (Phase 90 plan 06,
  // SPELL-12, 2026-10-01): Lesser Summon and Phantom Host left the spell list (33 rows -> 31), so a
  // scroll's `rng.pick(options)` lands on another row. Traced with a per-bot-step state-hash trace
  // against an extracted tree of the plan base c5017f16 (playRun's onStep): solo-1 (a Court Mage)
  // matches for 25 steps, then its first scroll read picks Heal (cast free) where the base picked
  // Shield (copied into the book); solo-2 (an Apprentice), solo-magicuser-sorcerer and deep-8 (a Court
  // Mage) differ at step 0, their first scroll read (solo-2: Freeze for Stun; the Sorcerer: Insane for
  // Summon; deep-8: Strength for Doze). solo-2's chargen also draws one fewer main-rng value (Phantom
  // Host left the Apprentice's pool). Every draw in the run moves from there. Old -> new (actions /
  // dead / depth): solo-1 253/true/3 -> 353/true/4; solo-2 294/true/3 -> 368/true/4;
  // solo-magicuser-sorcerer 400/false/4 -> 400/false/5; deep-8 225/true/10 -> 300/false/11.
  // "solo-thief-pilfer", "party-1", "party-fighter-knight" and "deep-14" re-measured byte-identical.
  // Only these four labels were
  // pasted, by hand, from `node tools/roll-high-baseline.mjs pins` (each hashed identically twice);
  // `save` was never run.
  // "solo-1", "solo-2", "solo-magicuser-sorcerer", "party-1" and "deep-8" re-pinned (Phase 90 plan 07,
  // SPELL-10, 2026-10-01): the four Special spells (Open/Lock, Fly, Enchant Character, Speed of Sound)
  // joined the spell list (31 rows -> 35), so a scroll's `rng.pick(options)` lands on another row (17
  // rows at depth 1, not 15), and a Special-school book (Wizard, Sorcerer, Illusionist, Summoner,
  // Apprentice) can hold a derived-stream splice of one. Traced with a per-bot-step event trace (playRun's
  // onStep) against an extracted tree of the plan base 6ac6aa63: solo-1 (a Court Mage) matches for 25
  // steps, then its first scroll read picks Shield, copied into the book, where the base picked Heal;
  // solo-magicuser-sorcerer, party-1 and deep-8 differ at step 0, their first scroll read (the Sorcerer:
  // Turn Walking Dead for Insane; party-1: Strength for Shield; deep-8: Doze for Strength); solo-2 (an
  // Apprentice) differs at step 35, where its book (Open/Lock and Enchant Character were spliced into
  // it) lets it cast Freeze where the base cast Mirror Self. No chargen cursor moved (the new rows are
  // roll: derived), so every divergence is a different spell, never a different draw count. Every draw
  // in the run moves from there. Old -> new (actions / dead / depth): solo-1 353/true/4 -> 253/true/3;
  // solo-2 368/true/4 -> 368/true/4 (hash only); solo-magicuser-sorcerer 400/false/5 -> 150/true/2;
  // party-1 400/false/3 -> 400/false/3 (hash only); deep-8 300/false/11 -> 109/true/9.
  // "solo-thief-pilfer", "party-fighter-knight" and "deep-14" re-measured byte-identical. Only these five
  // labels were pasted, by hand, from `node tools/roll-high-baseline.mjs pins` (each hashed identically
  // twice); `save` was never run.
  // "solo-2", "solo-magicuser-sorcerer" and "deep-8" re-pinned (Phase 90 plan 08, SPELL-10, 2026-10-01):
  // the three control spells (Stop Time, Senseless, Duplicate Foe) joined the spell list (35 rows -> 38),
  // so a scroll's `rng.pick(options)` lands on another row (18 rows at depth 1, 27, 33 and 38 deeper, not 17, 25, 31 and 35), and a Special
  // or Illusion book (Wizard, Sorcerer, Illusionist, Summoner, Apprentice) can hold a derived-stream splice
  // of one, which also shifts the other spliced rows' positions. Traced with a per-bot-step state-hash
  // trace (playRun's onStep) against an extracted tree of the plan base 49425bac: solo-2 (an Apprentice)
  // differs at step 0 (its book now holds Senseless, so its first scroll read, at depth 1, is copied or
  // cast as a different spell: scrollTooAdvanced then a Map the Floor cast, where the base cast and was
  // refused); solo-magicuser-sorcerer differs at step 0 (the book's Enchant Character became Stop Time);
  // deep-8 matches for 80 steps, then its first scroll read picks a spell the book copies
  // (scrollCopiedToGrimoire), where the base free-cast Sense Presence. No chargen cursor moved (the new
  // rows are roll: derived), so every divergence is a different spell, never a different draw count.
  // Old -> new (actions / dead / depth): solo-2 368/true/4 -> 239/true/2; solo-magicuser-sorcerer
  // 150/true/2 -> 313/true/3; deep-8 109/true/9 -> 300/false/11. "solo-1", "solo-thief-pilfer", "party-1",
  // "party-fighter-knight" and "deep-14" re-measured byte-identical. Only these three labels were pasted,
  // by hand, from the live pin run (each hashed identically twice); `save` was never run.
  "solo-1": { actions: 253, dead: true, depth: 3, hash: "47082481220cb07ea9857d986d10ca090337de206997be53411bf393261fa91c" },
  // Phase 89 plan 09 (TEXT-01 for items, ITEM-01, 2026-09-30): six labels re-recorded,
  // "solo-2", "solo-thief-pilfer", "solo-magicuser-sorcerer", "party-1",
  // "party-fighter-knight" and "deep-8"; "solo-1" and "deep-14" are unchanged. The
  // reworded item texts (content/treasure-tables.js, potions.js, bags.js) ride the hashed
  // state on items a run carries, wears or is offered. Proven text-only by running all
  // eight pins from a scratch copy of the tree with only those three content files at
  // the plan base (dd49e8d5): every label then hashes to its previous pin, with the same
  // actions, dead and depth. Only the six moved labels were edited (pasted by hand;
  // `roll-high-baseline.mjs save` was not run).
  // "solo-2" re-recorded (Phase 89 plan 09, TEXT-01, 2026-09-30): the item objects the run
  // ends holding carry reworded `txt` (see the block comment above "solo-2"). 89-09's
  // measurement: with the three content text files at the plan base, this label hashes
  // to 0f319aa8bc87aac8b3ba71b22a21f96108f8a7d12d52ff36539382422ada9c3f; actions, dead and depth are unchanged.
  "solo-2": { actions: 239, dead: true, depth: 2, hash: "a89a5ab088f5571855f9a864dabe2dde34d72c31908d0822924d96c7a41b6f04" },
  // "solo-thief-pilfer" re-recorded (Phase 89 plan 03, ITEM-01, 2026-09-30): this
  // run's bag ends holding a Poplar Staff (a Pilfer can never wield it), and the
  // item object rides the hashed state. Its row changed: use "heal" -> "partyHeal"
  // and text "1d20+10 hp to up to 6" -> "heals you and every Joiner with you
  // d20+10 hp each". Proven text/use-only: swapping the old use and text back into
  // the new run's final state re-hashes to the old pin
  // 845bfc4cc24d7e5201c5012bf4184cfaca52c08f06c7de20a04ea88d270eb3b0 (no Pendant
  // is worn or used; nothing in the run uses the staff, so no heal die is drawn).
  // 400 / false / 4 unchanged. Only this label was re-recorded (pasted by hand from
  // `node tools/roll-high-baseline.mjs pins`, hashed identically twice;
  // `roll-high-baseline.mjs save` was not run).
  // "solo-thief-pilfer" re-recorded (Phase 89 plan 09, TEXT-01, 2026-09-30): the item objects the run
  // ends holding carry reworded `txt` (see the block comment above "solo-2"). 89-09's
  // measurement: with the three content text files at the plan base, this label hashes
  // to 5f0056f4ce094913f13f5040dced0980c394662932edeb6a24b2f1f5f303d8ca; actions, dead and depth are unchanged.
  "solo-thief-pilfer": { actions: 400, dead: false, depth: 4, hash: "4f510d2220ef9d022210f3165eff5800d941f543f7b88d23ecb19c0960e3c1db" },
  // "solo-magicuser-sorcerer", "party-1" and "party-fighter-knight" re-pinned
  // (Phase 89, Plan 04, 2026-09-30, ITEM-07: "let their armor soak damage.
  // Just like players."): a foe's landed blow on a Joiner now rolls the
  // Joiner's own armour soak (engine/combat.js#applyFoeDamageToMember, a
  // derived-stream die, no main-rng draw) and wears the Joiner's armour.
  // Each run carries a Joiner (the bot accepts one when it has none, so even
  // "solo-magicuser-sorcerer" fights beside a Thief). Bisected with a
  // per-step state-hash trace against the base 688c537d: the FIRST
  // divergence is exactly the first soaked Joiner blow. solo-magicuser-
  // sorcerer step 365 (Google on Cedric Thorne: 9 taken and the Joiner downed
  // at the base, soaked with Leather's durability 15 -> 6 at the new engine);
  // party-1 step 222 (Hair on Aldric Corrin: 7 soaked, Cloth 12 -> 5);
  // party-fighter-knight step 107 (Ned on Hilda Stonecut, two blows of 9 and
  // 3 soaked, Leather 15 -> 8). A soaked blow leaves the Joiner's hp higher,
  // so the fight and the stream move on from there. solo-magicuser-sorcerer
  // 400/alive/5 -> 400/alive/5; party-1 373/dead/3 -> 372/dead/3; party-
  // fighter-knight 400/alive/3 -> 400/alive/4. The other five labels
  // re-measured byte-identical. Only these three labels were pasted, by hand,
  // from `node tools/roll-high-baseline.mjs pins` (each hashed identically
  // twice); `save` was never run.
  // "solo-magicuser-sorcerer" re-pinned again (Phase 89, Plan 05, 2026-09-30,
  // ITEM-07: "let joiners use items they have ... Just like players."): a
  // Joiner now joins dressed (engine/encounters.js#resolveJoiner runs
  // reconcileWorn), so a carried cloak moves from its bag into its worn map.
  // The run recruits Cedric Thorne, a Cutthroat, with a Cloak of Speed at bot
  // step 249 (joinerJoined, wore ["Cloak of Speed"]); the per-step state-hash
  // trace against the base 3d2f5d3b diverges exactly there and nowhere earlier.
  // It is a pure state-shape move: every step's event list and every party
  // hp line are identical to the base for all 400 steps, and undoing the
  // dressing in the final state (the cloak back in items, `worn` deleted)
  // re-hashes to the old pin 565c5fcb... exactly. No draw, rule or outcome
  // moved (400 / alive / 5 unchanged). The bot never uses a Joiner's items.
  // The other seven labels re-measured byte-identical. Only this label was
  // pasted, by hand, from `node tools/roll-high-baseline.mjs pins` (hashed
  // identically twice); `save` was never run.
  // "solo-magicuser-sorcerer", "party-1" and "party-fighter-knight" re-pinned
  // (Phase 89, Plan 06, 2026-09-30, ITEM-07, the in-fight half: "let joiners
  // use items they have ... Just like players."): on its own turn a Joiner now
  // uses its items automatically (engine/combat.js#alliesTurn): a ready worn
  // item in round 1 as a free use, one of its own potions at or below one
  // third of its HP INSTEAD of acting, and two swings under its own Speed.
  // Bisected with a per-step state-hash trace against the base 859a8d1f: the
  // FIRST divergence of each label is exactly the first new Joiner item line.
  // solo-magicuser-sorcerer step 355 (Cedric Thorne puts on his Cloak of Speed
  // in round 1 against a Skeleton and Google: itemUsed, itemEffectStarted);
  // party-1 step 230 (Aldric Corrin, at a third of his HP or less, drinks a
  // potion against Hair: memberPotionDrunk 13, instead of the swing that left
  // him downed at the base); party-fighter-knight step 257 (Hilda Stonecut
  // drinks her last potion against Dante instead of Second Wind). Every draw
  // the policy makes is a derived stream, so the main rng is untouched up to
  // each divergence and the fights run differently from there. Shapes:
  // solo-magicuser-sorcerer 400/alive/5 -> 400/alive/4; party-1 372/dead/3 ->
  // 400/alive/3 (the Joiner's potion kept the run alive); party-fighter-knight
  // 400/alive/4 -> 400/alive/4 (hash only). The other five labels re-measured
  // byte-identical. Only these three labels were pasted, by hand, from `node
  // tools/roll-high-baseline.mjs pins` (each hashed identically twice);
  // `save` was never run.
  // "solo-magicuser-sorcerer" re-recorded (Phase 89 plan 09, TEXT-01, 2026-09-30): the item objects the run
  // ends holding carry reworded `txt` (see the block comment above "solo-2"). 89-09's
  // measurement: with the three content text files at the plan base, this label hashes
  // to 992002f4edb013af107541738a89ebcbf6da7dd1afe8bfd4c914d651f0d7ecf6; actions, dead and depth are unchanged.
  // "solo-magicuser-sorcerer" and "deep-8" re-pinned (Phase 90 plan 09, SPELL-10, 2026-10-01): the last three
  // slate spells (Door Illusion, Chameleon Tongue, Size of the Behemoth) joined the spell list (38 rows -> 41), so a
  // scroll's `rng.pick(options)` lands on another row (19 rows at depth 1, 29, 36 and 41 deeper, not 18, 27, 33 and
  // 38). No chargen cursor moved (the new rows are roll: derived, and the Illusionist's two grants are on the derived
  // stream), so every divergence is a different spell, never a different draw count. Traced with a per-bot-step
  // state-hash trace (playRun's onStep) against an extracted tree of the plan base a060c0b6: both labels
  // differ at their first scroll read. solo-magicuser-sorcerer at step 0 (the depth-1 read picks Sense Presence,
  // which the Sorcerer free-casts as a scroll too advanced to copy, where the base read Turn Walking Dead, refused);
  // deep-8 matches for 80 steps, then its first read picks Death (copied into the book) where the base picked
  // Regeneration (copied). Old -> new (actions / dead / depth): solo-magicuser-sorcerer 313/true/3 -> 400/false/4;
  // deep-8 300/false/11 -> 300/false/11 (the hash only). "solo-1", "solo-2", "solo-thief-pilfer", "party-1",
  // "party-fighter-knight" and "deep-14" re-measured byte-identical. Only these two labels were pasted, by hand,
  // from `node tools/roll-high-baseline.mjs pins` (each hashed identically twice); `save` was never run.
  "solo-magicuser-sorcerer": { actions: 400, dead: false, depth: 4, hash: "f49b9400c6a21cc711ade269aa67dd9347ac7d00312f664a8f32be9fc13c15c5" },
  // "party-1" re-recorded (Phase 89 plan 09, TEXT-01, 2026-09-30): the item objects the run
  // ends holding carry reworded `txt` (see the block comment above "solo-2"). 89-09's
  // measurement: with the three content text files at the plan base, this label hashes
  // to a2bb10bccfbc83ff5d9d8431b7247c1d382b9d3ff8aa3ddf7c346304d5638faa; actions, dead and depth are unchanged.
  // "party-1" re-pinned (Phase 90 plan 10, SPELL-10, 2026-10-01: a Joiner Magic User casts by the new
  // policy, engine/combat.js#pickMemberSpell). Bisected with a per-step event-payload trace against the
  // plan base 3d875dd0 (an extracted tree, the same playRun onStep trace): the two runs match on every
  // action and every event payload through bot step 364; the FIRST divergence is step 365, three live foes,
  // round 2: the Joiner (Aldric Corrin, a Court Mage with Doze in its book) casts Doze as the room control
  // (allyCast, resist lines, dozed) where the base cast its best attack spell (Freeze: allyCast,
  // allySpellHit), and step 367 adds its first memberHealed (a heal at half its hit points). The base
  // run carries on to 400 alive; this one dies at action 372 (depth 3). 400/alive/3 -> 372/dead/3. The
  // hash moves at step 230 already (a transient `opened` flag on the Joiner's combat entry), before any
  // event differs. The other seven labels except "party-fighter-knight" (below) re-measured
  // byte-identical. Only the moved labels were pasted, by hand, from `node tools/roll-high-baseline.mjs
  // pins` (each hashed identically twice); `save` was never run.
  "party-1": { actions: 372, dead: true, depth: 3, hash: "f24df6a58db5056ae63950787e4e6ab5d6de23caff4d468b9360b8176f4d6659" },
  // "party-fighter-knight" and "deep-8" re-pinned (Phase 75.2, Plan 02,
  // 2026-09-26, RULES-11): NOT a gameplay-decision change — bisected live
  // (playRun's own onStep hook, scanning every step's c.items/c.worn for a
  // carried Enlarge potion or Gauntlet of the Giant) confirmed NEITHER run
  // ever fires an `itemEffectStarted` for either item; the sole divergence
  // is the Gauntlet of the Giant's rewritten `txt` field (content/
  // treasure-tables.js — "one size larger... +2 damage, and one face
  // easier for foes to hit", replacing the old "mind the ceilings"
  // wording), carried verbatim in this harness's full, unstripped state
  // hash once the item enters the bag: "party-fighter-knight" picks one up
  // at bot action 111 (still unused at action 400); "deep-8" at bot action
  // 16 (still unused at action 93, when the run ends in death). Every
  // OTHER label re-measured byte-identical (no other pin's hero or party
  // ever carries a Gauntlet of the Giant or an Enlarge potion within its
  // own action budget). `actions`/`dead`/`depth` are UNCHANGED for both —
  // only the hash moved, exactly as expected for a purely cosmetic content
  // edit reaching a real playthrough's serialized state. Regenerated via
  // `node tools/roll-high-baseline.mjs pins` (each hashed identically
  // twice).
  //
  // "party-fighter-knight" re-pinned AGAIN (Phase 79, quick fix 79-02b,
  // 2026-09-27, user ruling "Joiners use only their own defences against
  // foe swings"): a DECLARED outcome change. Traced live (base 90fa443 vs
  // the fix, playRun's onStep event streams): the first divergence is bot
  // step 99, the foe Ned's swing at the Joiner Hilda Stonecut, a Dwarven
  // Fighter/Woodsman beside a Human Knight hero. The foe die against her
  // was the HERO's (foeDie(c, f): d20, atLeast 17); it is now her OWN
  // race's (foeDie(sheet, f), the Dwarven foeStrikeStep: d12, atLeast 9).
  // Same draw, same position; only the face and later outcomes move —
  // depth 3 -> 4 within the same 400 actions. Every other label
  // re-measured byte-identical (solo runs never take the member branch;
  // party-1's Joiner has no personal term the fix moves). Regenerated via
  // `node tools/roll-high-baseline.mjs pins` (hashed identically twice).
  //
  // "party-fighter-knight" and "deep-8" re-pinned (Phase 79, Plan 05,
  // 2026-09-27, ROLL-04): item TEXT only. The roll-under item texts were
  // rewritten roll-high, and each run ends holding one: this run carries an
  // "Invisible potion (clear)" whose txt now states the foe's top face;
  // "deep-8" carries a set of Lockpicks whose txt reads "6–10 on d10" (was
  // "1–5"). Traced: putting the old txt back into each run's final state
  // re-hashes to the previous pin exactly, and actions/dead/depth are
  // unchanged. Regenerated via `node tools/roll-high-baseline.mjs pins`.
  // Merged 2026-09-27 (orchestrator): BOTH causes apply together, so the
  // value below was re-measured on the merged tree: depth 4 (the Joiner die) and the new item text, hashed identically twice.
  // Re-pinned again (quick fix 79-02c): per-floor heal removed (user ruling
  // 2026-09-27); first divergence bot step 318, see the "solo-1" block above.
  // Re-pinned again (quick 260928-hrs, user ruling 2026-09-28, "Use the same
  // half-intel scale for heroes now"): the hero resists a foe's spell or
  // ability on max(1, round(intel / 2)) faces, and every hero rolls. This
  // run's Knight has intel 2, so canon never rolled for it. Traced with a
  // scratch playRun onStep trace of every heroResisted/heroResistFailed:
  // the first is bot step 139, Krupke's Weaken at the hero (a new d20 in
  // the main-rng slot canon's gated d20 used, roll 10 vs 20, failed), so the
  // Weaken still lands and only the stream moves from there. It is the only
  // label with a hero resist within its budget (the other seven heroes meet
  // no hero-targeted foe ability and re-measured byte-identical). 200/dead/2
  // -> 180/dead/2. Regenerated via `node tools/roll-high-baseline.mjs pins`
  // (each hashed identically twice).
  // Re-pinned again (quick 260928-nrf, user ruling 2026-09-28, Joiners
  // resist: "Yes, same scale"). Bisected per rule commit (a scratch tree per
  // commit, the same playRun onStep trace): the Thief flee, Sweep, Kata/Feint
  // and Acrobat commits leave this run byte-identical; the Joiner-resist
  // commit moves it. First divergence bot step 134: Krupke's Freeze at the
  // Joiner Hilda Stonecut (a Woodsman, intel 9) now rolls her resist, a new
  // main-rng d20 between the target pick and the damage dice (roll 12 vs
  // 16–20, failed), so the Freeze still lands but its damage die moves (3 ->
  // 6) and the stream moves from there. 180/dead/2 -> 400/alive/3.
  // Regenerated via `node tools/roll-high-baseline.mjs pins`.
  // Re-pinned (Phase 89, Plan 04, ITEM-07): see the block above the
  // "solo-magicuser-sorcerer" entry. 400/alive/3 -> 400/alive/4.
  // Re-pinned again (Phase 89, Plan 06, ITEM-07): see the block above the
  // "solo-magicuser-sorcerer" entry. 400/alive/4 -> 400/alive/4 (hash only).
  // "party-fighter-knight" re-recorded (Phase 89 plan 09, TEXT-01, 2026-09-30): the item objects the run
  // ends holding carry reworded `txt` (see the block comment above "solo-2"). 89-09's
  // measurement: with the three content text files at the plan base, this label hashes
  // to 27bca013003f99a9ec9c21cdc744a16bca36627ed6163c4f5eae6b476d6e6aac; actions, dead and depth are unchanged.
  // "party-fighter-knight" re-pinned (Phase 90 plan 02, ABIL-07, 2026-09-30:
  // Pommel Strike is a real strike that also stuns, report #4). Bisected with a
  // per-step state-hash trace against the plan base 63c5fcae (a scratch tree,
  // the same playRun onStep trace): steps 1-99 are byte-identical and the FIRST
  // divergence is bot step 100, the hero's round-1 opener. The base's Pommel
  // Strike only stunned (abilityUsed, pommelStruck, then the Joiner's strike
  // killed the foe); the new one swings (stealthStrike, struck via
  // pommelStrike, foeKilled), so the stream moves on from there. 400/alive/4
  // -> 297/dead/3. The other seven labels re-measured byte-identical. Only this
  // label was pasted, by hand, from `node tools/roll-high-baseline.mjs pins`
  // (hashed identically twice); `save` was never run.
  // "party-fighter-knight" re-pinned (Phase 90 plan 10, ABIL-06, Q10 A, 2026-10-01: a Joiner uses Stealth,
  // Hardiness and Ambidextrous). Bisected the same way against the plan base 3d875dd0: the event streams
  // match through bot step 101 and the FIRST payload divergence is step 102, the foe's swing at the Joiner
  // Hilda Stonecut (a Dwarven Fighter/Woodsman with Hardiness): memberStruck 3 -> 1 (Hardiness, -3, floor 1).
  // Her second wind is later not needed where the base needed it (step 220), so the stream moves on; the
  // hash moves at step 102 as well through the transient `opened` flag on her combat entry. 297/dead/3 ->
  // 400/alive/3. Only the moved labels were pasted, by hand, from `node tools/roll-high-baseline.mjs pins`
  // (each hashed identically twice); `save` was never run.
  "party-fighter-knight": { actions: 400, dead: false, depth: 3, hash: "a803f03bd07c6eb7c7aa415e67c63185b591ce83c2dd80ef11549ee7682a324c" },
  // "deep-8" and "deep-14" first re-pinned (Phase 75, Plan 02, 2026-09-25):
  // RULES-02 deliberately cut WILMST_CACHE_PER_DEPTH 300 -> 100
  // (engine/encounters.js). "deep-8" re-pinned AGAIN here (Plan 05) — see
  // the RULES-03 comment block above; "deep-14" (a Thief) is unaffected by
  // either plan's change and keeps its Plan 02 value. Both re-measured
  // byte-identical again by Plan 12 — see the "solo-thief-pilfer" comment
  // block above. "deep-8" re-pinned YET AGAIN by Phase 75.2, Plan 02 (see
  // the "party-fighter-knight" comment block above) — a Gauntlet of the
  // Giant's rewritten `txt`, not a decision change; "deep-14" re-measured
  // byte-identical (no Gauntlet/Enlarge within its own action budget).
  // "deep-8" re-pinned YET AGAIN (Phase 75.3, Plan 01, 2026-09-26, RULES-16):
  // "solo fights fade with depth" — a floor-8 fight (the 5-9 band) that used
  // to draw a first d4 of 2 (solo, no second draw) now RAISES that same
  // first roll to 2 foes (soloOnlyOnOneFrom: 5); this run's own FIRST
  // encounterStarted event (floor 8, non-wandering) is exactly that fight —
  // bisected live (a scratch harness running this run once under the
  // shipped dials and once with FOE_COUNT_DEPTH forced to its identity
  // {0,0,0}, which this plan's own foe-count-depth.test.js proves reproduces
  // today's count at every depth) confirms the two logs agree on every
  // earlier fight (there are none — this is action 0's first encounter) and
  // diverge at this one fight alone: 1 foe under identity, 2 foes under the
  // shipped RULES-16 dial. `actions`/`dead`/`depth` all moved too (250/true/10
  // vs the prior 93/true/9) — an EXPECTED outcome shift, not a bug: a
  // tougher floor-8 opener changes how the rest of this 300-action-budget
  // run plays out, which is this phase's entire point (the user's own
  // Troll-Summoner complaint was exactly "too many solo fights past floor
  // 5"). Regenerated via `node tools/roll-high-baseline.mjs pins` (hashed
  // identically twice).
  // "deep-8" re-pinned (Phase 79, Plan 05): its Lockpicks txt, see the
  // "party-fighter-knight" comment above.
  // Re-pinned again (quick fix 79-02c): per-floor heal removed (user ruling
  // 2026-09-27); first divergence bot step 77 (a floor-9 arrival that used
  // to heal +15), 250 -> 262 actions, still dead on floor 10. See the
  // "solo-1" block above.
  // Re-pinned again (user rulings 2026-09-28, Freeze): first divergence bot
  // step 10, see the "solo-1" block above.
  // Re-pinned again (quick 260928-sq2, spell damage adds level²): first
  // divergence bot step 10, the same Freeze now a kill; see the "solo-1"
  // block above.
  // "deep-8" re-recorded (Phase 89 plan 09, TEXT-01, 2026-09-30): the item objects the run
  // ends holding carry reworded `txt` (see the block comment above "solo-2"). 89-09's
  // measurement: with the three content text files at the plan base, this label hashes
  // to 0d9ca103d12007b9066ef0d5a5578995a4fc13f45dbde4419df5b2c817c9c263; actions, dead and depth are unchanged.
  // "deep-8" re-pinned (Phase 90 plan 09, SPELL-10, 2026-10-01): see the block comment above "solo-magicuser-sorcerer".
  "deep-8": { actions: 300, dead: false, depth: 11, hash: "85673de6ad134f2a1fda38d548ba5b92997817bdb295f1117ebe2a44df3ad7af" },
  // "solo-thief-pilfer" and "deep-14" re-pinned (Phase 75.1, Plan 06,
  // 2026-09-26): RULES-10 removes canRead's blanket class/skill gate — the
  // bot (tools/lib/tuning-bot.mjs#decideAction) now reads a carried scroll
  // out of combat for EVERY class, not only a Magic User/Runes-Signs holder.
  // Both moved labels are Thieves (solo-thief-pilfer: a forced Pilfer;
  // deep-14: an Acrobat) — NEITHER is a Magic User, so this is not a STOP.
  // Bisected live (playRun's own onStep hook, watching for the first
  // `scrollRead` event): solo-thief-pilfer's first scroll read lands at bot
  // step 138 (`reader: "intel"`), deep-14's at step 168 (`reader: "intel"`)
  // — in both cases the FIRST divergence-causing event is exactly this
  // plan's own new intel-read roll, previously unreachable for either
  // character (the old canRead-gated bot never dispatched `readScroll` for
  // a non-Magic-User/non-Runes reader at all). Every OTHER label re-measured
  // byte-identical (no other pin's Thief/Fighter ever carries a scroll
  // within its own action budget, and every Magic User label — solo-1,
  // solo-2, solo-magicuser-sorcerer, party-1 — is unaffected, since its own
  // `readScroll` path is byte-identical to before this phase). Regenerated
  // via `node tools/roll-high-baseline.mjs pins` (each hashed identically
  // twice).
  // "deep-14" re-pinned YET AGAIN (Phase 75.3, Plan 01, 2026-09-26, RULES-16):
  // "solo fights fade with depth" — a floor-14 fight (the 10-19 band, "never
  // solo") that used to draw a first d4 of 1 (canon solo, 1 foe) now floors
  // at 2 via `foeCountMinFor` (atLeastTwoFrom: 10); this run's own FIRST
  // encounterStarted event (floor 14, non-wandering) is exactly that fight —
  // bisected the same way as "deep-8" above (a scratch harness comparing the
  // shipped dials against FOE_COUNT_DEPTH forced to identity {0,0,0}): the
  // two logs agree on every earlier fight (there are none — action 0's first
  // encounter) and diverge at this one fight alone: 1 foe under identity, 2
  // under the shipped dial. `actions`/`dead`/`depth` all moved too (52/true/14
  // vs the prior 300/false/16) — an EXPECTED outcome shift (a harder floor-14
  // opener kills this run 52 actions in, instead of surviving 300 and
  // reaching floor 16), not a bug. Regenerated via `node
  // tools/roll-high-baseline.mjs pins` (hashed identically twice).
  // "deep-14" re-pinned (quick 260927-opf, user ruling 2026-09-27: the
  // one-shot strikes are once per fight). Traced against e1f9dc0c (the
  // spell-resist rule alone, byte-identical to the base for this Thief):
  // at bot step 19 this Acrobat's Silent Step is once per fight, so its
  // record is the per-fight mark (998 rounds left) instead of a 3-round
  // cooldown, and the bot aims it like every once-a-fight foe ability
  // (tools/lib/tuning-bot.mjs#hardestFoeIndex: the second Drarl, not the
  // first); the fight plays out differently from there (step 21: a Poisoned
  // Edge where the old run drank a potion). 52 / dead / floor 14 -> 154 /
  // dead / floor 15. Regenerated via `node tools/roll-high-baseline.mjs
  // pins` (hashed identically twice).
  // Re-pinned (quick 260928-nrf, user ruling 2026-09-28, "Acrobat: foes hit
  // on top 4"). This run's hero is an Acrobat. Bisected per rule commit: the
  // Thief flee +3 commit changes only the step-50 fleeRolled range (7 vs
  // 9–20 -> 7 vs 11–20, a fail either way; the hash does not move), Sweep,
  // Kata/Feint and the Joiner resist leave it byte-identical, and the
  // Acrobat commit moves it. First divergence bot step 20: a Drarl's swing
  // rolls 5, which missed against the old 6-or-better (top three faces of
  // its d8) and now lands against 5-or-better (top four) for 21, so the
  // fight plays out differently from there. 50/dead/14 -> 35/dead/14.
  // Regenerated via `node tools/roll-high-baseline.mjs pins`.
  //
  // "deep-14" re-recorded (Phase 88 plan 04, ITEM-03, 2026-09-30): this Thief's
  // starting cloak is a Cloak of Regeneration, and its item TEXT changed ("used,
  // a d6 hp back at once; then twenty squares of rest before it works again" ->
  // "used, a d6 hp back every ten squares you walk, three times; then fifty
  // squares before it will do it again"). The item object rides the hashed
  // state, so the hash moves from step 0. Traced against a `git archive` of the
  // base (3cce3352) with a per-step wp/steps/event trace: all 35 steps are
  // identical (the bot never uses the cloak in this run, so no heal tick fires
  // and no rng draw differs). Proven text-only: swapping the old text back into
  // the new run's final state re-hashes to the old pin
  // 20cec0b202a6c373cb6eff068d72045cd43c0524ac492e75bcdc2e2c01ed8d75. Only this
  // label was re-recorded (pasted by hand; `roll-high-baseline.mjs save` was not
  // run). 35 / dead / 14 unchanged.
  "deep-14": { actions: 35, dead: true, depth: 14, hash: "fe2e796aa947d051f39955a2534b9dc0af989fc2af5dbc6da0cd956dc70792f1" },
};

test("PIN_RUNS/PINNED cover the same labels, 1:1", () => {
  assert.deepStrictEqual(
    PIN_RUNS.map((r) => r.label).sort(),
    Object.keys(PINNED).sort(),
  );
});

for (const cfg of PIN_RUNS) {
  test(`roll-high baseline pin: ${cfg.label}`, () => {
    const result = pinRun(cfg);
    assert.deepStrictEqual(
      { actions: result.actions, dead: result.dead, depth: result.depth, hash: result.hash },
      PINNED[cfg.label],
      `${cfg.label} diverged from its Phase 73 base pin — a check site was flipped wrong; fix the site, never re-pin`,
    );
  });
}
