// test/unit/roll-high-state-pins.test.js
//
// Phase 73 (ROLL-05, Plan 02): a bot-sweep state-hash pin, generated on the
// UNTOUCHED engine at the Phase 73 base — commit bef94aa (git rev-parse
// --short HEAD). See CONTEXT Area 3 ("Proof it changed nothing"): the parity
// fixtures only reach solo level-1 Beasts and Humans, so they cannot see a
// mis-flipped Skeleton, member, climb or trap. These eight runs (four solo,
// two party, two deep starts near depth 8/14) reach far wider ground.
//
// The switch (this phase, later plans) must change REPRESENTATION only —
// every check's threshold/roll direction mirrors, but which side WINS never
// changes. A moved hash here means a check site was flipped wrong: FIX THE
// SITE, never re-pin. Regenerate with `node tools/roll-high-baseline.mjs
// pins` only if a plan deliberately changes outcomes and declares why (it
// should not — see 73-CONTEXT.md's "byte-identical outcomes" requirement).

import test from "node:test";
import assert from "node:assert/strict";
import { PIN_RUNS, pinRun } from "./harness/rollHighBaseline.js";

// Generated by `node tools/roll-high-baseline.mjs pins` at commit bef94aa,
// each entry hashed identically across two independent runs before pinning.
const PINNED = {
  // "solo-1", "solo-2", "party-1" and "deep-8" re-pinned (Phase 75, Plan 05,
  // 2026-09-25): RULES-03's grant-time legality filter (engine/character.js
  // #grantableAt, used by rollGrimoire's low/high walks and checkLevel)
  // changes WHICH spells a gated Magic User sub-class (Warlock, Sorcerer,
  // Court Mage, Illusionist, Cleric, Apprentice) lands with at chargen — a
  // previously-granted-but-uncastable spell (e.g. a Court Mage's divination
  // spell, gated at 4) is skipped while walking the already-shuffled list,
  // so a DIFFERENT, immediately-castable spell fills that book slot instead.
  // Verified: newRun(seed).c.sub for every one of these four labels is a
  // gated Magic User sub-class (solo-1/party-1: Court Mage; solo-2:
  // Apprentice; deep-8: Court Mage) — the ONE declared change this plan
  // makes to chargen content — while "solo-thief-pilfer",
  // "solo-magicuser-sorcerer" (forced Sorcerer, whose seed's book happens to
  // draw no now-illegal spell) and "party-fighter-knight" (non-caster) stay
  // byte-identical, and "deep-14" (a Thief, unaffected by any Magic User
  // change) stays byte-identical too. Regenerated via
  // `node tools/roll-high-baseline.mjs pins` (each hashed identically twice).
  //
  // "solo-thief-pilfer" re-pinned again (Phase 75, Plan 12, 2026-09-25):
  // RULES-12's `resolvePendingTile` (a tile a wandering-monster check
  // interrupted mid-step now resolves once the fight settles, instead of
  // being silently dropped forever) changes a bot-visible OUTCOME for this
  // one Thief run — a resumed tile's feature firing where it previously
  // never did shifts the run's depth (5 -> 4) within 400 actions. Every
  // OTHER label re-measured byte-identical (RULES-15's fed-only book
  // refill never actually fires within any of these seeds' 400/300/93-
  // action budgets, and RULES-12 never fires for the other seven either) —
  // confirmed by re-running `node tools/roll-high-baseline.mjs pins` after
  // adding `pendingTile` to `EXTRA_VOLATILE_FIELDS`
  // (test/unit/harness/rollHighBaseline.js) so the field's mere PRESENCE
  // (vs. absence on a state that never set it) never itself moves a hash —
  // see that file's own doc comment for the "pure JSON-representation
  // noise" precedent (`pendingJoiner`). Regenerated via `node
  // tools/roll-high-baseline.mjs pins` (each hashed identically twice).
  //
  // "solo-thief-pilfer" re-pinned AGAIN (Phase 75.1, Plan 01, 2026-09-25):
  // RULES-09 removes the IDENT-07 heal-only refusal — a Pilfer's non-heal
  // magic-item use, which used to be a silent `useRefused {reason:"pilfer"}`
  // no-op burning ZERO rng draws, now actually resolves (a real use, or a
  // fumble), consuming real draws from the main rng cursor from that point
  // on. Bisected live: this forced Pilfer's first such use is an Amulet of
  // Light (`itemUsed`, kind "glow") at action 333 of 400 — exactly the
  // "newly allowed use" this plan's own interfaces block anticipated. The
  // outcome shape is unchanged (400 actions, not dead, depth 4) — only the
  // downstream rng-consumed state differs. Confirmed by reverting ONLY
  // tuning-bot.mjs's round-1-buff Pilfer skip in an isolated scratch copy
  // and re-measuring: the hash did NOT change (chooseCombatItem's own
  // "buff" branch never actually fires for this seed/force — no potion or
  // worn buff item is in this run's starting kit), ruling out Plan 01's
  // bot-tactics.mjs edit as the cause and isolating it to the engine's own
  // useItem change. Every OTHER label re-measured byte-identical (no other
  // pin ever exercises a Pilfer's non-heal item use within its own action
  // budget). Regenerated via `node tools/roll-high-baseline.mjs pins`
  // (each hashed identically twice).
  //
  // "solo-thief-pilfer" re-pinned YET AGAIN (Phase 75.1, Plan 06,
  // 2026-09-26) — see the "deep-14" comment block below for the full
  // RULES-10 rationale (the bot now reads a scroll for every class); this
  // Pilfer's own first scroll read lands at bot step 138 (`reader:
  // "intel"`), the outcome shape unchanged (400 actions, not dead, depth 4).
  //
  // "solo-2" and "party-fighter-knight" re-pinned (Phase 75.2, Plan 01,
  // 2026-09-26, RULES-11): size is now a real stat — a Dwarven character's
  // own face axis (unmasked; only the Dwarven damage axis is protected by
  // the signature rule) shaves one winning face off every foe trying to
  // land a blow on that body. "solo-2" is a forced-nothing chargen roll
  // whose seed lands a Dwarven Apprentice (verified: `newRun(202).c.race
  // === "Dwarven"`); its hero's own first foe swing carrying a `{name:
  // "size", delta: -1}` mod fires at bot action 9 (bisected live via
  // playRun's own onStep hook, scanning for the first event whose `mods`
  // include a "size" entry) — the depth shifts (4 -> 5) from there.
  // "party-fighter-knight" forces a Human Fighter/Knight hero, but its
  // seed's own Joiner (recruited by forceParty's real meetJoiner/
  // resolveJoiner draw) is Dwarven ("Hilda Stonecut", verified live); the
  // FIRST size-mod event is a `foeMissed` against THAT member at bot action
  // 100 (engine/combat.js#foeTurn's member branch, this plan's own new
  // term) — the hero's own race is unaffected (Human, size step 0), so this
  // is exactly the Joiner symmetry rule ("a Joiner gets size too... by the
  // same rule") reaching a real playthrough, not a hero-side change. Every
  // OTHER label re-measured byte-identical twice (no other pin's hero or
  // party carries a Dwarven/Elven/Troll within its own action budget —
  // solo-1/solo-thief-pilfer/solo-magicuser-sorcerer/party-1/deep-8/deep-14
  // are all Human/Wilmsry/Fridgian heroes with no sized party member).
  // Regenerated via `node tools/roll-high-baseline.mjs pins` (each hashed
  // identically twice).
  // "solo-1", "solo-2", "solo-thief-pilfer", "solo-magicuser-sorcerer" and
  // "party-1" re-pinned (Phase 78, Plan 01, 2026-09-26, CLIMB-01): every
  // step toward a wall or crevice now pauses on the pre-roll decision (a
  // `hazardChoice`, no dice) and the bot commits on its next action
  // (tools/lib/tuning-bot.mjs#decideAction), so each crossing WITHOUT the
  // tool costs one extra validated action inside the fixed 400-action
  // budget. Bisected live (a scratch trace of every step's full state hash,
  // `acts`/`pendingHazard` aside, against a plan-base copy of the engine,
  // with the pause steps dropped): solo-1 (4 uncarried pauses), solo-2 (3),
  // solo-magicuser-sorcerer (7) and party-1 (5) play the SAME game step for
  // step and simply stop that many game actions earlier. solo-thief-pilfer
  // (3 pauses) matches up to bot step 137, its first scroll read after a
  // crossing: the acts-keyed `scrollRead` derived stream (engine/magic.js)
  // sees an `acts` one higher per earlier pause, so the read that
  // deciphered now fumbles. `actions`/`dead`/`depth` are unchanged for all
  // five; party-fighter-knight, deep-8 and deep-14 cross no wall or crevice
  // within their budgets and re-measured byte-identical. Regenerated via
  // `node tools/roll-high-baseline.mjs pins` (hashed identically three
  // times).
  //
  // "solo-1", "solo-2", "solo-thief-pilfer", "solo-magicuser-sorcerer",
  // "party-1", "party-fighter-knight" and "deep-8" re-pinned (Phase 79,
  // quick fix 79-02c, 2026-09-27): per-floor heal removed (user ruling
  // 2026-09-27, "We shouldn't heal at all when we go down a floor"). A
  // DECLARED outcome change. Traced live (base 08969929 vs the fix, a
  // scratch trace of every bot step's full state hash through playRun's
  // onStep hook): each label's FIRST divergence is exactly its first
  // descent that used to push `floorRegen`, and the two runs agree on every
  // earlier step. solo-1 step 205 (base +18 hp, 72/72 vs now 54/72), solo-2
  // step 103 (+9), solo-thief-pilfer step 74 (+4), solo-magicuser-sorcerer
  // step 85 (+4), party-1 step 147 (+7), party-fighter-knight step 318
  // (+17), deep-8 step 77 (+15). The regen drew no rng, so the draw stream
  // is the same; only hp, and the bot's later choices from it, move.
  // actions/dead/depth are unchanged except deep-8 (250 -> 262 actions,
  // still dead on floor 10). "deep-14" re-measured byte-identical (it dies
  // on floor 14 before any descent). Regenerated via
  // `node tools/roll-high-baseline.mjs pins` (hashed identically twice).
  //
  // "solo-1", "solo-2" and "solo-magicuser-sorcerer" re-pinned (quick
  // 260927-rsx, user ruling 2026-09-27: every spell cast on a foe can be
  // resisted, half its intel in faces on a d20, from a derived stream).
  // Traced against extracted trees (git archive 4407e350, the base, and
  // e1f9dc0c, the resist rule alone) with a per-step state-hash trace: the
  // first divergence is the hero's own Freeze resisted by its target —
  // solo-1 bot step 111 (Dante, 6 faces, rolled 20), solo-2 step 10
  // (Philly, 2 faces, rolled 19), solo-magicuser-sorcerer step 100 (Drekk,
  // 2 faces, rolled 19) — every earlier step byte-identical. Quick
  // 260927-opf (once-per-fight strikes) moves none of the three. solo-1
  // stays 400 / alive / floor 5; solo-2 floor 5 -> 4; the Sorcerer floor
  // 4 -> 3. Regenerated via `node tools/roll-high-baseline.mjs pins`
  // (each hashed identically twice).
  // User rulings 2026-09-28 (plan 79.2-01, "freeze should never kill
  // outright. It should deal its damage and freeze an enemy for 1d4 rounds";
  // "if it hits and resists, deal damage, but no freeze"): "solo-1",
  // "solo-2", "solo-magicuser-sorcerer", "party-1" and "deep-8" re-pinned.
  // Traced against an extracted tree (git archive 992b1dfa, the base) with a
  // per-bot-step state-hash trace: each label's first divergence is a
  // Freeze — solo-1 bot step 103 (the hero's Freeze on a China Wolf, 6
  // damage: it was frozen solid and killed, now frozen for its d4 of 3),
  // solo-2 step 9 (the hero's Freeze on Philly, 2 damage, now frozen 3),
  // solo-magicuser-sorcerer step 100 (the hero's Freeze on Drekk: resisted
  // before the throw, now the 1 damage lands and the resist stops only the
  // freeze), party-1 step 186 (the Joiner Aldric Corrin's Freeze on a
  // Gremlin: 6 damage, then resisted, where it was frozen solid and killed)
  // and deep-8 step 10 (the hero's Freeze on a Poltergeist, 8 damage, now
  // frozen 2) — every earlier step byte-identical. solo-1 400/alive, floor
  // 5 -> 4; solo-2 400/alive/4 -> 298/dead/3; the Sorcerer floor 3 -> 4;
  // party-1 floor 4 -> 3; deep-8 262/dead/10 -> 117/dead/9. Every other
  // label re-measured byte-identical. Regenerated via
  // `node tools/roll-high-baseline.mjs pins` (each hashed identically twice).
  // Quick 260928-sq2 (user ruling 2026-09-28, "square spell damage just like
  // we do with weapons damage"): a spell's damage is its dice + the caster's
  // level², replacing x max(1, level - spell level). "solo-1", "solo-2",
  // "party-1" and "deep-8" re-pinned. Traced against an extracted tree (git
  // archive d98639e9, the base) with a per-bot-step state-hash trace: each
  // first divergence is a Freeze hit's damage — solo-1 bot step 103 (the
  // hero's Freeze on a China Wolf, 6 -> 7), solo-2 step 9 (the hero's Freeze
  // on Philly, 2 -> 4 applied), party-1 step 186 (the Joiner Aldric
  // Corrin's Freeze on a Gremlin, 6 -> 7: now a kill, where it was resisted
  // and stood) and deep-8 step 10 (the level-5 hero's Freeze on a
  // Poltergeist, 2 x 4 = 8 -> 2 + 25 = 27: now a kill, where it was frozen
  // 2) — every earlier step byte-identical. solo-1 400/alive, floor 4 -> 5;
  // solo-2 298/dead/3 -> 400/alive/4; party-1 400/alive/3 -> 375/dead/3;
  // deep-8 117/dead/9 -> 262/dead/10. solo-thief-pilfer,
  // solo-magicuser-sorcerer, party-fighter-knight and deep-14 re-measured
  // byte-identical. Regenerated via `node tools/roll-high-baseline.mjs pins`
  // (each hashed identically twice).
  // Phase 79.2 early-floor lock (user ruling 2026-09-27, locked by
  // RF-79.2-02-3): every one of the eight labels re-pinned. The lock moved
  // HERO_HP_SCALE 1.25 -> 1.4, HERO_SP_SCALE 0.28 -> 0.23, FOE_HP_SCALE.base
  // 0.9 -> 1.2, FOE_HIT_SCALE { 0.6, 0.01 } -> { 0.84, 0.02 } and
  // FOE_LEVEL.base 0.9 -> 1.0. Traced with a scratch per-bot-step trace
  // (playRun's onStep, stateHash of every step) run twice on the locked
  // engine: once under setDialsForTuning(79.2's fit/start.json), which
  // reproduced every old pin below byte for byte, and once under the locked
  // DIALS. Every label's first differing state is bot step 1, and the only
  // differing fields there are c.maxWP/c.wp: chargen's heroMaxWpFor reads
  // HERO_HP_SCALE (solo-1 36 -> 41, solo-2 36 -> 41, solo-thief-pilfer
  // 50 -> 56, solo-magicuser-sorcerer 38 -> 42, party-1 43 -> 48,
  // party-fighter-knight 68 -> 76, deep-8 63 -> 70, deep-14 80 -> 89). The
  // first differing EVENT is: solo-1 step 13 (a Shriek's wp 3 -> 4,
  // FOE_HP_SCALE), solo-2 step 7 (Philly 5 -> 6, FOE_HP_SCALE),
  // solo-thief-pilfer step 44 (Ned 7 -> 10, FOE_HP_SCALE),
  // solo-magicuser-sorcerer step 86 (the descend spGained 20 -> 16,
  // HERO_SP_SCALE), party-1 step 97 (a Bat/Rat kill's spGained 4 -> 3,
  // HERO_SP_SCALE), party-fighter-knight step 98 (three Neds 7 -> 10,
  // FOE_HP_SCALE), deep-8 step 9 (Poltergeist 10 -> 13 and Rinkle 16 -> 21,
  // FOE_HP_SCALE) and deep-14 step 9 (Table 4's -10 HP row, dotHpFor 13 ->
  // 14, HERO_HP_SCALE). Old -> new (actions / dead / depth): solo-1
  // 400/false/5 -> 253/true/3; solo-2 400/false/4 -> 294/true/3;
  // solo-thief-pilfer 400/false/4 (unchanged); solo-magicuser-sorcerer
  // 400/false/4 -> 400/false/5; party-1 375/true/3 -> 373/true/3;
  // party-fighter-knight 400/false/4 -> 200/true/2; deep-8 262/true/10 ->
  // 225/true/10; deep-14 154/true/15 -> 50/true/14. Regenerated via
  // `node tools/roll-high-baseline.mjs pins` (each hashed identically twice).
  "solo-1": { actions: 253, dead: true, depth: 3, hash: "47082481220cb07ea9857d986d10ca090337de206997be53411bf393261fa91c" },
  "solo-2": { actions: 294, dead: true, depth: 3, hash: "0f319aa8bc87aac8b3ba71b22a21f96108f8a7d12d52ff36539382422ada9c3f" },
  "solo-thief-pilfer": { actions: 400, dead: false, depth: 4, hash: "845bfc4cc24d7e5201c5012bf4184cfaca52c08f06c7de20a04ea88d270eb3b0" },
  "solo-magicuser-sorcerer": { actions: 400, dead: false, depth: 5, hash: "3ae31ce819ca2a515d231e1a81d97bcc808096c62d31bf338f6285482d5f2689" },
  "party-1": { actions: 373, dead: true, depth: 3, hash: "bb3e4f6b079e75a6232571ca0e27879befa51370e39889c15be8e3464e3b329d" },
  // "party-fighter-knight" and "deep-8" re-pinned (Phase 75.2, Plan 02,
  // 2026-09-26, RULES-11): NOT a gameplay-decision change — bisected live
  // (playRun's own onStep hook, scanning every step's c.items/c.worn for a
  // carried Enlarge potion or Gauntlet of the Giant) confirmed NEITHER run
  // ever fires an `itemEffectStarted` for either item; the sole divergence
  // is the Gauntlet of the Giant's rewritten `txt` field (content/
  // treasure-tables.js — "one size larger... +2 damage, and one face
  // easier for foes to hit", replacing the old "mind the ceilings"
  // wording), carried verbatim in this harness's full, unstripped state
  // hash once the item enters the bag: "party-fighter-knight" picks one up
  // at bot action 111 (still unused at action 400); "deep-8" at bot action
  // 16 (still unused at action 93, when the run ends in death). Every
  // OTHER label re-measured byte-identical (no other pin's hero or party
  // ever carries a Gauntlet of the Giant or an Enlarge potion within its
  // own action budget). `actions`/`dead`/`depth` are UNCHANGED for both —
  // only the hash moved, exactly as expected for a purely cosmetic content
  // edit reaching a real playthrough's serialized state. Regenerated via
  // `node tools/roll-high-baseline.mjs pins` (each hashed identically
  // twice).
  //
  // "party-fighter-knight" re-pinned AGAIN (Phase 79, quick fix 79-02b,
  // 2026-09-27, user ruling "Joiners use only their own defences against
  // foe swings"): a DECLARED outcome change. Traced live (base 90fa443 vs
  // the fix, playRun's onStep event streams): the first divergence is bot
  // step 99, the foe Ned's swing at the Joiner Hilda Stonecut, a Dwarven
  // Fighter/Woodsman beside a Human Knight hero. The foe die against her
  // was the HERO's (foeDie(c, f): d20, atLeast 17); it is now her OWN
  // race's (foeDie(sheet, f), the Dwarven foeStrikeStep: d12, atLeast 9).
  // Same draw, same position; only the face and later outcomes move —
  // depth 3 -> 4 within the same 400 actions. Every other label
  // re-measured byte-identical (solo runs never take the member branch;
  // party-1's Joiner has no personal term the fix moves). Regenerated via
  // `node tools/roll-high-baseline.mjs pins` (hashed identically twice).
  //
  // "party-fighter-knight" and "deep-8" re-pinned (Phase 79, Plan 05,
  // 2026-09-27, ROLL-04): item TEXT only. The roll-under item texts were
  // rewritten roll-high, and each run ends holding one: this run carries an
  // "Invisible potion (clear)" whose txt now states the foe's top face;
  // "deep-8" carries a set of Lockpicks whose txt reads "6–10 on d10" (was
  // "1–5"). Traced: putting the old txt back into each run's final state
  // re-hashes to the previous pin exactly, and actions/dead/depth are
  // unchanged. Regenerated via `node tools/roll-high-baseline.mjs pins`.
  // Merged 2026-09-27 (orchestrator): BOTH causes apply together, so the
  // value below was re-measured on the merged tree: depth 4 (the Joiner die) and the new item text, hashed identically twice.
  // Re-pinned again (quick fix 79-02c): per-floor heal removed (user ruling
  // 2026-09-27); first divergence bot step 318, see the "solo-1" block above.
  "party-fighter-knight": { actions: 200, dead: true, depth: 2, hash: "78644698316b137b3a0d5a8d9dd36e39e4da39feec6982b66cc2f90da4c701ac" },
  // "deep-8" and "deep-14" first re-pinned (Phase 75, Plan 02, 2026-09-25):
  // RULES-02 deliberately cut WILMST_CACHE_PER_DEPTH 300 -> 100
  // (engine/encounters.js). "deep-8" re-pinned AGAIN here (Plan 05) — see
  // the RULES-03 comment block above; "deep-14" (a Thief) is unaffected by
  // either plan's change and keeps its Plan 02 value. Both re-measured
  // byte-identical again by Plan 12 — see the "solo-thief-pilfer" comment
  // block above. "deep-8" re-pinned YET AGAIN by Phase 75.2, Plan 02 (see
  // the "party-fighter-knight" comment block above) — a Gauntlet of the
  // Giant's rewritten `txt`, not a decision change; "deep-14" re-measured
  // byte-identical (no Gauntlet/Enlarge within its own action budget).
  // "deep-8" re-pinned YET AGAIN (Phase 75.3, Plan 01, 2026-09-26, RULES-16):
  // "solo fights fade with depth" — a floor-8 fight (the 5-9 band) that used
  // to draw a first d4 of 2 (solo, no second draw) now RAISES that same
  // first roll to 2 foes (soloOnlyOnOneFrom: 5); this run's own FIRST
  // encounterStarted event (floor 8, non-wandering) is exactly that fight —
  // bisected live (a scratch harness running this run once under the
  // shipped dials and once with FOE_COUNT_DEPTH forced to its identity
  // {0,0,0}, which this plan's own foe-count-depth.test.js proves reproduces
  // today's count at every depth) confirms the two logs agree on every
  // earlier fight (there are none — this is action 0's first encounter) and
  // diverge at this one fight alone: 1 foe under identity, 2 foes under the
  // shipped RULES-16 dial. `actions`/`dead`/`depth` all moved too (250/true/10
  // vs the prior 93/true/9) — an EXPECTED outcome shift, not a bug: a
  // tougher floor-8 opener changes how the rest of this 300-action-budget
  // run plays out, which is this phase's entire point (the user's own
  // Troll-Summoner complaint was exactly "too many solo fights past floor
  // 5"). Regenerated via `node tools/roll-high-baseline.mjs pins` (hashed
  // identically twice).
  // "deep-8" re-pinned (Phase 79, Plan 05): its Lockpicks txt, see the
  // "party-fighter-knight" comment above.
  // Re-pinned again (quick fix 79-02c): per-floor heal removed (user ruling
  // 2026-09-27); first divergence bot step 77 (a floor-9 arrival that used
  // to heal +15), 250 -> 262 actions, still dead on floor 10. See the
  // "solo-1" block above.
  // Re-pinned again (user rulings 2026-09-28, Freeze): first divergence bot
  // step 10, see the "solo-1" block above.
  // Re-pinned again (quick 260928-sq2, spell damage adds level²): first
  // divergence bot step 10, the same Freeze now a kill; see the "solo-1"
  // block above.
  "deep-8": { actions: 225, dead: true, depth: 10, hash: "0d9ca103d12007b9066ef0d5a5578995a4fc13f45dbde4419df5b2c817c9c263" },
  // "solo-thief-pilfer" and "deep-14" re-pinned (Phase 75.1, Plan 06,
  // 2026-09-26): RULES-10 removes canRead's blanket class/skill gate — the
  // bot (tools/lib/tuning-bot.mjs#decideAction) now reads a carried scroll
  // out of combat for EVERY class, not only a Magic User/Runes-Signs holder.
  // Both moved labels are Thieves (solo-thief-pilfer: a forced Pilfer;
  // deep-14: an Acrobat) — NEITHER is a Magic User, so this is not a STOP.
  // Bisected live (playRun's own onStep hook, watching for the first
  // `scrollRead` event): solo-thief-pilfer's first scroll read lands at bot
  // step 138 (`reader: "intel"`), deep-14's at step 168 (`reader: "intel"`)
  // — in both cases the FIRST divergence-causing event is exactly this
  // plan's own new intel-read roll, previously unreachable for either
  // character (the old canRead-gated bot never dispatched `readScroll` for
  // a non-Magic-User/non-Runes reader at all). Every OTHER label re-measured
  // byte-identical (no other pin's Thief/Fighter ever carries a scroll
  // within its own action budget, and every Magic User label — solo-1,
  // solo-2, solo-magicuser-sorcerer, party-1 — is unaffected, since its own
  // `readScroll` path is byte-identical to before this phase). Regenerated
  // via `node tools/roll-high-baseline.mjs pins` (each hashed identically
  // twice).
  // "deep-14" re-pinned YET AGAIN (Phase 75.3, Plan 01, 2026-09-26, RULES-16):
  // "solo fights fade with depth" — a floor-14 fight (the 10-19 band, "never
  // solo") that used to draw a first d4 of 1 (canon solo, 1 foe) now floors
  // at 2 via `foeCountMinFor` (atLeastTwoFrom: 10); this run's own FIRST
  // encounterStarted event (floor 14, non-wandering) is exactly that fight —
  // bisected the same way as "deep-8" above (a scratch harness comparing the
  // shipped dials against FOE_COUNT_DEPTH forced to identity {0,0,0}): the
  // two logs agree on every earlier fight (there are none — action 0's first
  // encounter) and diverge at this one fight alone: 1 foe under identity, 2
  // under the shipped dial. `actions`/`dead`/`depth` all moved too (52/true/14
  // vs the prior 300/false/16) — an EXPECTED outcome shift (a harder floor-14
  // opener kills this run 52 actions in, instead of surviving 300 and
  // reaching floor 16), not a bug. Regenerated via `node
  // tools/roll-high-baseline.mjs pins` (hashed identically twice).
  // "deep-14" re-pinned (quick 260927-opf, user ruling 2026-09-27: the
  // one-shot strikes are once per fight). Traced against e1f9dc0c (the
  // spell-resist rule alone, byte-identical to the base for this Thief):
  // at bot step 19 this Acrobat's Silent Step is once per fight, so its
  // record is the per-fight mark (998 rounds left) instead of a 3-round
  // cooldown, and the bot aims it like every once-a-fight foe ability
  // (tools/lib/tuning-bot.mjs#hardestFoeIndex: the second Drarl, not the
  // first); the fight plays out differently from there (step 21: a Poisoned
  // Edge where the old run drank a potion). 52 / dead / floor 14 -> 154 /
  // dead / floor 15. Regenerated via `node tools/roll-high-baseline.mjs
  // pins` (hashed identically twice).
  "deep-14": { actions: 50, dead: true, depth: 14, hash: "930b575e1cbfad83a7aa0221d4e756cca8398c22316128c9461047cb0a023631" },
};

test("PIN_RUNS/PINNED cover the same labels, 1:1", () => {
  assert.deepStrictEqual(
    PIN_RUNS.map((r) => r.label).sort(),
    Object.keys(PINNED).sort(),
  );
});

for (const cfg of PIN_RUNS) {
  test(`roll-high baseline pin: ${cfg.label}`, () => {
    const result = pinRun(cfg);
    assert.deepStrictEqual(
      { actions: result.actions, dead: result.dead, depth: result.depth, hash: result.hash },
      PINNED[cfg.label],
      `${cfg.label} diverged from its Phase 73 base pin — a check site was flipped wrong; fix the site, never re-pin`,
    );
  });
}
