// test/unit/roll-high-state-pins.test.js
//
// Phase 73 (ROLL-05, Plan 02): a bot-sweep state-hash pin, generated on the
// UNTOUCHED engine at the Phase 73 base — commit bef94aa (git rev-parse
// --short HEAD). See CONTEXT Area 3 ("Proof it changed nothing"): the parity
// fixtures only reach solo level-1 Beasts and Humans, so they cannot see a
// mis-flipped Skeleton, member, climb or trap. These eight runs (four solo,
// two party, two deep starts near depth 8/14) reach far wider ground.
//
// The switch (this phase, later plans) must change REPRESENTATION only —
// every check's threshold/roll direction mirrors, but which side WINS never
// changes. A moved hash here means a check site was flipped wrong: FIX THE
// SITE, never re-pin. Regenerate with `node tools/roll-high-baseline.mjs
// pins` only if a plan deliberately changes outcomes and declares why (it
// should not — see 73-CONTEXT.md's "byte-identical outcomes" requirement).

import test from "node:test";
import assert from "node:assert/strict";
import { PIN_RUNS, pinRun } from "./harness/rollHighBaseline.js";

// Generated by `node tools/roll-high-baseline.mjs pins` at commit bef94aa,
// each entry hashed identically across two independent runs before pinning.
const PINNED = {
  // "solo-1", "solo-2", "party-1" and "deep-8" re-pinned (Phase 75, Plan 05,
  // 2026-09-25): RULES-03's grant-time legality filter (engine/character.js
  // #grantableAt, used by rollGrimoire's low/high walks and checkLevel)
  // changes WHICH spells a gated Magic User sub-class (Warlock, Sorcerer,
  // Court Mage, Illusionist, Cleric, Apprentice) lands with at chargen — a
  // previously-granted-but-uncastable spell (e.g. a Court Mage's divination
  // spell, gated at 4) is skipped while walking the already-shuffled list,
  // so a DIFFERENT, immediately-castable spell fills that book slot instead.
  // Verified: newRun(seed).c.sub for every one of these four labels is a
  // gated Magic User sub-class (solo-1/party-1: Court Mage; solo-2:
  // Apprentice; deep-8: Court Mage) — the ONE declared change this plan
  // makes to chargen content — while "solo-thief-pilfer",
  // "solo-magicuser-sorcerer" (forced Sorcerer, whose seed's book happens to
  // draw no now-illegal spell) and "party-fighter-knight" (non-caster) stay
  // byte-identical, and "deep-14" (a Thief, unaffected by any Magic User
  // change) stays byte-identical too. Regenerated via
  // `node tools/roll-high-baseline.mjs pins` (each hashed identically twice).
  //
  // "solo-thief-pilfer" re-pinned again (Phase 75, Plan 12, 2026-09-25):
  // RULES-12's `resolvePendingTile` (a tile a wandering-monster check
  // interrupted mid-step now resolves once the fight settles, instead of
  // being silently dropped forever) changes a bot-visible OUTCOME for this
  // one Thief run — a resumed tile's feature firing where it previously
  // never did shifts the run's depth (5 -> 4) within 400 actions. Every
  // OTHER label re-measured byte-identical (RULES-15's fed-only book
  // refill never actually fires within any of these seeds' 400/300/93-
  // action budgets, and RULES-12 never fires for the other seven either) —
  // confirmed by re-running `node tools/roll-high-baseline.mjs pins` after
  // adding `pendingTile` to `EXTRA_VOLATILE_FIELDS`
  // (test/unit/harness/rollHighBaseline.js) so the field's mere PRESENCE
  // (vs. absence on a state that never set it) never itself moves a hash —
  // see that file's own doc comment for the "pure JSON-representation
  // noise" precedent (`pendingJoiner`). Regenerated via `node
  // tools/roll-high-baseline.mjs pins` (each hashed identically twice).
  //
  // "solo-thief-pilfer" re-pinned AGAIN (Phase 75.1, Plan 01, 2026-09-25):
  // RULES-09 removes the IDENT-07 heal-only refusal — a Pilfer's non-heal
  // magic-item use, which used to be a silent `useRefused {reason:"pilfer"}`
  // no-op burning ZERO rng draws, now actually resolves (a real use, or a
  // fumble), consuming real draws from the main rng cursor from that point
  // on. Bisected live: this forced Pilfer's first such use is an Amulet of
  // Light (`itemUsed`, kind "glow") at action 333 of 400 — exactly the
  // "newly allowed use" this plan's own interfaces block anticipated. The
  // outcome shape is unchanged (400 actions, not dead, depth 4) — only the
  // downstream rng-consumed state differs. Confirmed by reverting ONLY
  // tuning-bot.mjs's round-1-buff Pilfer skip in an isolated scratch copy
  // and re-measuring: the hash did NOT change (chooseCombatItem's own
  // "buff" branch never actually fires for this seed/force — no potion or
  // worn buff item is in this run's starting kit), ruling out Plan 01's
  // bot-tactics.mjs edit as the cause and isolating it to the engine's own
  // useItem change. Every OTHER label re-measured byte-identical (no other
  // pin ever exercises a Pilfer's non-heal item use within its own action
  // budget). Regenerated via `node tools/roll-high-baseline.mjs pins`
  // (each hashed identically twice).
  "solo-1": { actions: 400, dead: false, depth: 5, hash: "ce883a88443d0e1a2ff1547974c0f9ce5c2a647f479e9ef8de4d7bf4644f8ca6" },
  "solo-2": { actions: 400, dead: false, depth: 4, hash: "b4daf5d20b7f4d3b36d55c1790f53f0d9610d64e3c45a9d81e3700e451ee3e4f" },
  "solo-thief-pilfer": { actions: 400, dead: false, depth: 4, hash: "cbc2eb2768e9586b2437c032c5a23b082e20116391b02ede004dfaed32bd6e4b" },
  "solo-magicuser-sorcerer": { actions: 400, dead: false, depth: 4, hash: "444ec2ca839587b2249e6f89828a40fef887b2668b935c228a510e99c4ac4207" },
  "party-1": { actions: 400, dead: false, depth: 4, hash: "ab7a42cbfcc8f9cad5845ce73e5f51b59a1942f4cb0ff25c1e2a78591c0aa61d" },
  "party-fighter-knight": { actions: 400, dead: false, depth: 3, hash: "1ad4462f4a8b7017cc14d5bf5f566677f8efda6d0cd4f6fab06cfb94b928370d" },
  // "deep-8" and "deep-14" first re-pinned (Phase 75, Plan 02, 2026-09-25):
  // RULES-02 deliberately cut WILMST_CACHE_PER_DEPTH 300 -> 100
  // (engine/encounters.js). "deep-8" re-pinned AGAIN here (Plan 05) — see
  // the RULES-03 comment block above; "deep-14" (a Thief) is unaffected by
  // either plan's change and keeps its Plan 02 value. Both re-measured
  // byte-identical again by Plan 12 — see the "solo-thief-pilfer" comment
  // block above.
  "deep-8": { actions: 93, dead: true, depth: 9, hash: "74fedc2dd92b7a34da2bc505dcd7c2575b43726e24b6b07e23b39c5f40f9cace" },
  "deep-14": { actions: 300, dead: false, depth: 16, hash: "68598e3d89c5f13798f21a13af02144dc9e43c5ea05548b4cb6b189a22df41bc" },
};

test("PIN_RUNS/PINNED cover the same labels, 1:1", () => {
  assert.deepStrictEqual(
    PIN_RUNS.map((r) => r.label).sort(),
    Object.keys(PINNED).sort(),
  );
});

for (const cfg of PIN_RUNS) {
  test(`roll-high baseline pin: ${cfg.label}`, () => {
    const result = pinRun(cfg);
    assert.deepStrictEqual(
      { actions: result.actions, dead: result.dead, depth: result.depth, hash: result.hash },
      PINNED[cfg.label],
      `${cfg.label} diverged from its Phase 73 base pin — a check site was flipped wrong; fix the site, never re-pin`,
    );
  });
}
